### ISSUE TITLE
change log for 1.x to 2.x?

### ISSUE THREAD

**Issue by gdi2290** [inikulin/parse5#100]
is there a list of breaking changes from 1.x to 2.x?

**Comment by inikulin** [comment]
https://github.com/inikulin/parse5/wiki/Documentation#version-history

**Comment by gdi2290** [comment]
thanks

**Comment by inikulin** [comment]
You are welcome. Actually it's the second question of this kind, so I'm starting to doubt that documentation is obvious and accessible. I wonder if I should high light it somehow in the [README](https://github.com/inikulin/parse5#readme). Any suggestions?

**Comment by gdi2290** [comment]
what's confusing are the release https://github.com/inikulin/parse5/releases after linking there it's asumed that it wasn't written so when you click on the docs when you see `Version history` you can also assume it's a link to releases. Version history is important enough to have on the readme even though it's in the doc

**Comment by inikulin** [comment]
@gdi2290 Thank you for the feedback. So, explicit link to the `Version history` in README should work I guess.

**Comment by domenic** [comment]
I think filling in each release on GitHub with a link to the corresponding version history heading would be good. Project watchers also get an email each time you create a GitHub release so it's a good notification channel.

**Comment by inikulin** [comment]
@domenic I like this idea, thanks.
