### ISSUE TITLE
Parse5.SaxParser vs HtmlParser2: performance and memory issues

### ISSUE THREAD

**Issue by ivan-kleshnin** [inikulin/parse5#102]
I made two testbenches for **HtmlParser2** and **Parse5.SaxParser**

### HtmlParser2
https://gist.github.com/ivan-kleshnin/fcf6353242f3a4a462e7

### Parse5.SaxParser
https://gist.github.com/ivan-kleshnin/bb571f51d47aaebee16a

File `huge.html` is **112mb** file containing **120472** paragraphs.
I uploaded it [here](http://www.filedropper.com/huge)  but you can easily make something similar.

---

Results are quite shocking :fearful: 

### HtmlParser2
```
stopped (4.41 seconds)
Mem before: 18.68 mb
Mem after: 16.32 mb
Mem max: 0b
```

### Parse5.SaxParser
```
stopped (1.62 minutes)
Mem before: 19.63 mb
Mem after: 125.46 mb
Mem max: 1.04 gb
```

There should be some bug explaining that. I would simply use **HtmlParser2** 
but I like **Parse5** API better so I hope you will fix that.

**Comment by inikulin** [comment]
Well, the thing is that SAXParser uses spec-compliant tokenizer under the hood. And the problem with the HTML5 tokenization is that it requires rollbacks to operate properly. So, in general there is no other way to correctly parse document, except buffering it is a whole (see similar discussion in Servo's about Servo's HTML parser: https://github.com/servo/html5ever/issues/149#issuecomment-120991146). Everything else that happens in this benchmark is the effects of this buffering. 

On the other hand, is there any real-life task that requires parsing of the 122Mb HTML document? I can fix it partially by introducing some heuristics, like limiting buffer size to 10Mb. But still, parser will have some significant memory footprint on large files. And, in theory, this may break parser in some very rare cases. 

Conclusion: if you are going to parse 112Mb HTML files in production then I think htmlparser2 is the way to go. If not, then consider trying benchmarking with file sizes that you expect in real life scenario.

**Comment by inikulin** [comment]
However, I have some crazy idea. Need to try and test it. Stay tuned :radio:

**Comment by thisconnect** [comment]
I personally would opt for speed. Are there situations where you parse huge files and have limited or low memory?

In my application I only need speed and have plenty of memory. Wondering what situations people need low memory footprint.

**Comment by ivan-kleshnin** [comment]
> I personally would opt for speed. Are there situations where you parse huge files and have limited or low memory?

I would opt for memory because if I want speed I use non-sax parsers which are both more convenient and more performant. Stream machinery is generally slower (in my experience). Anyway, you can trade one for other but now we have problems with both. I'm not well aware of HTML5-compliant parsing specifics so I can't really advice anything.

**Comment by inikulin** [comment]
> (Parser5.SaxParser) than without streams (Parser5.DefaultParser)

This new info changes things drastically. Can you provide benchmarking info for parse5.SAXParser vs parse5.Parser?

**Comment by ivan-kleshnin** [comment]
> This new info changes things drastically. Can you provide benchmarking info for parse5.SAXParser vs parse5.Parser?

I'll try to prepare such testbench. Maybe tomorrow.

**Comment by inikulin** [comment]
Unfortunately, currently I'm extremely busy with other projects, so I will not be able to deliver this fast :cry:. However, if someone is willing to be an awesome person who going to implement this, here is the idea how it can be done: for streaming parsing we can remove the leading part of the buffer if it will no longer partisipate in tokenization. Once we emit a token we can slice buffer at token's end position (see location info code for the example of how the end position can be determined). The only tricky part that is left is to keep indices in sync (we need actual indices for the location info). That's it.

**Comment by inikulin** [comment]
Yet another optimization: token recycling. Create pool of free token objects. Reuse tokens that are not in use anymore. This should reduce GC load and also reduce memory consumption on big inputs.

**Comment by RReverser** [comment]
@inikulin Modern GCs are good enough to reuse small objects on their own, I doubt that will give you any significant win. But might be worth trying, I'm just a random guy on internet :)

**Comment by inikulin** [comment]
We have 10xInput size memory consumption here. I can't think of any object that produced in such a large scale in parser except tokens. It's just a guess, but looks like GC just can't get in time to clean up or reallocate all tokens produced by parser on large inputs, therefore producing less objects may make a trick here.
