### ISSUE TITLE
Expose createTextNode() on default tree adapter

### ISSUE THREAD

**Issue by steffans** [inikulin/parse5#1031]
Would be great if the createTextNode() function is also exposed on the default tree adapter to allow overrides an reuse logic of other tree adapter functions.

**Comment by fb55** [comment]
PRs welcome!

**Comment by 43081j** [comment]
If anyone does tackle this, it'd be helpful to also open a PR in [parse5-tools](https://github.com/parse5/parse5-tools) since it currently provides its own `createTextNode` thanks to the lack of one here.

so you could remove that and just alias the new one you introduce here

**Comment by fb55** [comment]
Closed in #1040
