### ISSUE TITLE
 parse5.serialize can't  serialize childNode  which is fragment

### ISSUE THREAD

**Issue by rachardking** [inikulin/parse5#106]
why?
what can i do ?

  if (childNodes) {
        for (var i = 0, cnLength = childNodes.length; i < cnLength; i++) {
            var currentNode = childNodes[i];

            if (this.treeAdapter.isElementNode(currentNode))
                this._serializeElement(currentNode);

            else if (this.treeAdapter.isTextNode(currentNode))
                this._serializeTextNode(currentNode);

            else if (this.treeAdapter.isCommentNode(currentNode))
                this._serializeCommentNode(currentNode);

            else if (this.treeAdapter.isDocumentTypeNode(currentNode))
                this._serializeDocumentTypeNode(currentNode);
        }
    }

**Comment by inikulin** [comment]
Hi.
Can you provide more info: HTML input, expected results, actual results, code snippet you are using

**Comment by rachardking** [comment]
`
node = {
    childNodes:[
        {
            nodeName:'#text'
            value:'test'
        },
        {
            nodeName: '#document-fragment'
            childNodes:[]
        }
    ]
}
`
when serialize, it can't serialize the fragment and the fragment's childNodes

**Comment by inikulin** [comment]
This is incorrect HTML AST - document can't be a child node of any other node (with the exception for the template elements)

**Comment by rachardking** [comment]
but in  your dom operate, like this
```
var appendChild = exports.appendChild = function (parentNode, newNode) {
    parentNode.childNodes.push(newNode);
    newNode.parentNode = parentNode;
};

```

is doesn't consider the fragment node

**Comment by rachardking** [comment]
but  in real dom, it's can do

**Comment by inikulin** [comment]
parse5 doesn't provide DOM. For the full-featured DOM implementation, please take a look at [jsdom](https://github.com/tmpvar/jsdom). It uses parse5 under the hood.

**Comment by daniellizik** [comment]
Was wondering how to do this but figured you can just mock the ast yourself:

```js
import { serialize } from 'parse5'
const serializeFragment = (node) => {
  return serialize({
    nodeName: '#document-fragment',
    childNodes: [node]
  })
}
```

that is working nicely for me
