### ISSUE TITLE
Implement input byte stream decoding

### ISSUE THREAD

**Issue by inikulin** [inikulin/parse5#111]
https://html.spec.whatwg.org/multipage/syntax.html#the-input-byte-stream

**Comment by inikulin** [comment]
I thought the primary adopter of this will be jsdom, but they just landed encoding support on their side. However, it's missing quick encoding lookup algorithm, but I'm not sure it will give any significant performance gain in single-threaded Node.js land. Is there anyone else interested in this feature?

**Comment by RReverser** [comment]
Do you mean actual encoding conversion or encoding detection or replacement of specific characters? First one is already covered by built-in `string_decoder`, other two should be easy to do.

**Comment by inikulin** [comment]
BOM + `<meta>` encoding detection (fast lookup algorithm from the spec) and actual decoding. `string_decoder` will not work for us, because we need to support all this encodings: https://encoding.spec.whatwg.org/#names-and-labels. So we will need something like `inconv-lite` + label converter.

**Comment by inikulin** [comment]
I believe decoding shouldn't be implemented on our side, since it's not something HTML specific. Adopters will need it anyway to decode other resources and more likely they will have their implementation. The only thing that we can do on our side is [Decoding prescan](https://html.spec.whatwg.org/multipage/syntax.html#prescan-a-byte-stream-to-determine-its-encoding), but since no one showed interest in it, I'll close this issue for now. Feel free to file another issue if you are interested in this feature.
