### ISSUE TITLE
Not able to detect tag when using SAXParser

### ISSUE THREAD

**Issue by gameboyzone** [inikulin/parse5#112]
Hello,
**Here's my markup -**

<!DOCTYPE html>
<html>
	<head></head>
<body>
	<uitag component-type="para" class="bold">
		Hello this is Hardik Shah
	</uitag>

	<uitag component-type="header" class="someClass" hasUnderline="true">
		More Facts
	</uitag>
</body>
</html>

**Here's my code for server.js. I'm unable to detect uitag**

var file = fs.readFileSync('Markup.html', 'utf8');
//var file = fs.createWriteStream('Markup.html');
var parser2 = new parse5.SAXParser();

parser2.on('doctype', function(name, publicId, systemId) {
	//Process doctype info and stop parsing
	
	console.log('');
	console.log('** Example 4: Doctype encountered **');
	
	//parser.stop();
});

parser2.on('uitag', function(name, attrs, selfClosing) {
	var type = parse5.treeAdapters.default.getAttrList(scriptElement)[0].value;
	
	console.log('');
	console.log('** Example 4: Component Type **');
	console.log(type);
	
	//resume();
});

parser2.on('finish', function(text) {
	//var body = parser.document.childNodes[1].childNodes[2];
	
	console.log('');
	console.log('** Example 4: Tree **');
	console.log(parser2);
});

parser2.end(file);

**Comment by gameboyzone** [comment]
@inikulin

**Comment by inikulin** [comment]
Hi.

SAXParser doesn't have events for the particular tags, use [startTag event](https://github.com/inikulin/parse5/wiki/Documentation#starttag-name-attrs-selfclosing-location) instead:
```js
parser2.on('startTag', function(name, attrs, selfClosing) {
    if(name === 'uitag')
        // do your stuff
});
```
Also, note that things like this
```js
var body = parser.document.childNodes[1].childNodes[2];
```
won't work with SAXParser, since it's not construction any tree.

**Comment by gameboyzone** [comment]
Thanks @inikulin.

I figured the difference between DOM parser and SAX Parser with a bit of reading and got the fundamental point - it's an event driven parser. Guess the project Wiki can include a few links to these concepts for beginners.

**Comment by inikulin** [comment]
>  Guess the project Wiki can include a few links to these concepts for beginners.

It's already does (https://github.com/inikulin/parse5/wiki/Documentation#new-saxparseroptions):
> Streaming [SAX](https://en.wikipedia.org/wiki/Simple_API_for_XML)-style HTML parser. A [transform stream](https://nodejs.org/api/stream.html#stream_class_stream_transform) (which means you can pipe *through* it, see example).
