### ISSUE TITLE
Backwards Compatibility with HTML4

### ISSUE THREAD

**Issue by pedro93** [inikulin/parse5#113]
I think the title says it all. Is this lib backwards compatible with the HTML4 specification as defined in https://www.w3.org/TR/html4/types.html?
Is it compliant in its integrity with tags like CDATA supported?
How backwards compatible can we assume this lib to be or is it exclusively HTML5-compliant and ignores anything outside it?

Thanks :)

P.S: I apologize if this is the incorrect platform to ask this question.

**Comment by inikulin** [comment]
Here is the complete list of differences in syntax of HTML5 and HTML4: https://html-differences.whatwg.org/#syntax. In general: HTML5 parser can parse any HTML4 document, but resulting AST will not be equivalent to the one produced with the HTML4 parser.
