### ISSUE TITLE
Add content wrapper for a given node? 

### ISSUE THREAD

**Issue by pedro93** [inikulin/parse5#117]
This is merely a suggestion.
For any given node add a method to the TreeAdapter Object to retrieve a node's content regardless of its type. 
For instance, for a text node this can be the node.value, for comments: node.data and for element nodes this could be a string with the nodes attributes and content if it exists.

**Comment by inikulin** [comment]
Tree adapters maintain the minimum set of methods required for building and serializing HTML ASTs. Is there any parse5-related case there such method should be implemented in tree adapter, why it can't be external helper method?

**Comment by pedro93** [comment]
Right now, unless written by each developer, there is no way (in so far as I know) for a user of this library to get information solely about a node (without parent, sibling and children information), a level-0 obj serialization.

I just thought that such a method (node.content()) would be helpful for developers to debug or maybe just filter-out alot of "needless" information. 

Whether this method should be in the tree adapter or not I do not know, I merely suggested it to be there as most node-manipulation and data-retrieval functions are there.

**Comment by inikulin** [comment]
I'm afraid I still don't understand reasoning about this being a part of parse5: 
 - If you need this for debugging purpose then debugger watches works just fine for node; 
 - if you need to take a quick look at AST produced by parse5 for the particular markup you can use [online playground](http://astexplorer.net/#/1CHlCXc4n4); 
- If you need to serialize AST, you will need some circular JSON serializer anyway to preserve correct tree structure;
- If you need to log your nodes somehow for your project then such logging should be implemented in your application, so it will meet requirements for your target output medium and format.

**Comment by pedro93** [comment]
Im my case I am creating a DOM diff tool.
During my algorithm's execution it modifies the AST in recursive fashion which leads to difficult debugging. 

 - Adding a breakpoint in a function which has to execute 10s of times is not helpful.

 - Playgrounds don't help because the AST is quite big and modified during execution

 - I merely want the top level information of a node, no circular serialization required.

 - I agree that depending on the project, different information needs to be logged, hence my question about a wrapper and not a fixed function.

I have come to realize that more often than not, I need to log some nodes in order to validate some internal information. This information resides at the node level, I have created a logger function specifically for this reason:

```js
NodeManager.prototype.getNodeContent = function (node) {
    if(treeAPI.isCommentNode(node)){
        return node.data;
    }
    else if(treeAPI.isTextNode(node) ){
        return node.value;
    }
    else if(treeAPI.isElementNode(node)){
        return {type: node.type, name: node.name, attribs: node.attribs };
    }
    else
        return node.type;
};
```

Something like this is likely to be useful not only to myself but others. I am of the opinion that something like this or a wrapper, even if requiring a user created logging function would be useful

**Comment by inikulin** [comment]
I do agree that it might be really useful. As I said before tree adapters maintain the minimal set of methods required to make parse5 work with the given tree format. Therefore I'm trying to avoid adding optional things there, since it creates additional burden for the tree adapter implementors which might not give any valuable benefits for them. Philosophy here is pretty simple: everything that could not be here - should not be here. There are couple of utils libraries for parse5: [dom5](https://github.com/PolymerLabs/dom5) and [parse5-utils](https://github.com/webdeps/parse5-utils). This thing could be a good addition for these libraries. Or even better you can come up with your own library (none of them support parse5 >=2.0.0 currently) and share you experience with the world.

**Comment by inikulin** [comment]
BTW, you can mixin this functionality to nodes by using custom tree adapter:
```js
const parse5 = require('parse5');
const defaultTreeAdapter = parse5.treeAdapters.default;

const myAdapter = Object.create(defaultTreeAdapter);

myAdapter.createElement = (tagName, namespaceURI, attrs) => {
    const element = defaultTreeAdapter.createElement(tagName, namespaceURI, attrs);

    element.getContent = () => {/*your method code here*/};
    return element;
};

// Same for other node types...

// Usage
const doc = parse5.parse('<div>42</div>', { treeAdapter: myAdapter });

doc.getContent();
```

**Comment by pedro93** [comment]
Thank you for the information. I will look into the libs you referenced 👍
