### ISSUE TITLE
Don't inherit from Object when creating collections

### ISSUE THREAD

**Issue by deckar01** [inikulin/parse5#119]
The safe way to create a hash / map / dictionary is with `Object.create(null)` to prevent collisions with the `Object` prototype, then applying needed prototype methods à la carte `Object.prototype.foo.call(hash, arg1, arg2, ...)`.

http://www.devthought.com/2012/01/18/an-object-is-not-a-hash/

Context:

 > > But the better fix would be for parse5 to use Object.create(null) when creating objects-as-maps

https://github.com/tmpvar/jsdom/pull/1444#issuecomment-207897088

 > Agreed. Can you create an issue in parse5 repo, please?

https://github.com/tmpvar/jsdom/pull/1444#issuecomment-208235893

**Comment by deckar01** [comment]
I'm not sure what the strategy should be here. My intuition is that any maps that are exposed by the API should be fixed, but that seems like a recipe for incompatibility. This is not a common pattern, so it will be difficult to document and support.

It almost feels like there needs to be a Dictionary datatype that adheres to the Object interface, but implements `Object.create(null)` as the underlying storage mechanism.

In any case this is effectively a major revision that breaks backwards compatibility.

**Comment by inikulin** [comment]
I don't see how we will be able to break anything here. We need this primarily for the internal maps. The only maps exposed externally are attribute dictionaries in `htmlparser2` adapters. But I don't think we can break someone's code here either.

**Comment by deckar01** [comment]
If anyone is accessing [functions from the object prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype) on those attribute dictionaries, they will have to migrate to `Object.prototype.call()`.

Example: https://github.com/tmpvar/jsdom/pull/1444/commits/cb5addd666ccfde4f85c2b00f1f64363da8a6cd5#diff-563a86e009c6f9fbb49da85d81ad9c3bR246

This technically is part of the interface currently, but I understand the argument that it could be considered undefined behavior, therefore subject to change in a patch or minor revision.

**Comment by inikulin** [comment]
Ok, let's mark it as breaking since it's already used in the wild this way. Not a big deal to release a major, I have some pending breaking changes anyway. Thank you for bringing my attention to this.

**Comment by deckar01** [comment]
Thanks for working on this @inikulin.
