### ISSUE TITLE
text node data trim?

### ISSUE THREAD

**Issue by pedro93** [inikulin/parse5#120]
Is it possible to tell the library to trim the data processed in text nodes in order to ignore text nodes with only whitespaces? 
In a similar fashion to what the XML parser Xerces does:

https://xerces.apache.org/xerces-c/apiDocs-3/classXMLString.html#a2fd275970f10b9b602a96bf4dcd4d8c6

**Comment by inikulin** [comment]
No, it's impossible. Moreover HTML5 parser decisions are based on the content of the text nodes in some cases. However, you can achieve desired functionality by traversing AST and remove text nodes with only whitespace as post-processing stage.
