### ISSUE TITLE
TypeError: parse5.TreeSerializer is not a function

### ISSUE THREAD

**Issue by noahehall** [inikulin/parse5#121]
similar to issue #68

calling this function:
var document = parse5.parseFragment(thisChart);

causes my chaijs script to fail when running on gitlab on ubuntu/debian.

However, the code runs fine on mac osx 10

**Comment by inikulin** [comment]
So it's serializer issue (as issue title suggests) or `parseFragment` issue? Did you check that `thisChart` is string and not a buffer? Also, I can't make any assumption on the nature of this issue without proper small reproduction code.

**Comment by noahehall** [comment]
HI @inikulin 

Thanks for the quick reply
i'll input some code on the next comment

**Comment by noahehall** [comment]
Seems gitlab has an issue with returning a string,
var thisChart = helpers.chartData(cv[0],cv[1],cv[2]);
var document = parse5.parseFragment(thisChart);

when I console thisChart its undefined, hence the error with parse5

**Comment by inikulin** [comment]
So, I guess I can close issue now?

**Comment by noahehall** [comment]
Yes!

**Comment by noahehall** [comment]
Just for closure, there was a module 'numeral' that was inside 'Dependencies' in package.json, but not inside 'DevDepenencies', causing a module that used it to fail
