### ISSUE TITLE
Filter out text elements according to rule during stream parse

### ISSUE THREAD

**Issue by pedro93** [inikulin/parse5#123]
Is it possible to detect text elements during a stream parse and depending on a test of the text content, ignore the node in the final AST produced?

**Comment by inikulin** [comment]
Yes, you can implement [custom tree adapter](https://github.com/inikulin/parse5/wiki/Documentation#q-i-want-to-work-with-my-own-document-tree-format-how-can-i-do-this) which will filter text nodes content on insertion into AST.

**Comment by inikulin** [comment]
BTW, seems like you can achieve functionality you've asked for in #120 using this approach.
