### ISSUE TITLE
[Typescript] Attribute interface is wrong (wrong property name for "name").

### ISSUE THREAD

**Issue by Supamiu** [inikulin/parse5#124]
This issue is a d.ts problem. in parse5/index.d.ts, you have this interface : 

```
export interface Attribute {
        key: string;
        value: string;
    }
```

But if you get a node and log its attributes, you have this:

```
{ name: 'foo', value: 'bar' }
```

Proof:

```
import * as parse5 from "parse5";
import {treeAdapters} from "parse5";
let example = "<div foo='bar'></div>";
let node = parse5.parseFragment(example);
console.log(treeAdapters.default.getAttrList(node.childNodes[0]));
```

then check index.d.ts to see that the interface is not the good one (property "key" should be named "name").

**Comment by RReverser** [comment]
Cool, want to send a PR?

**Comment by inikulin** [comment]
I guess this issue relates to [DefinetlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) because we don't ship any `.d.ts.` files.

**Comment by Supamiu** [comment]
I'll send a PR to DefinetlyTyped then, thank you for your answer @inikulin.

**Comment by RReverser** [comment]
@inikulin I think it would be nice to ship them by the way, as their new `typings` approach allows libraries to ship & maintain their own typings without need to update anything in the DefinitelyTyped.

**Comment by inikulin** [comment]
Makes sense. Is there any tool that allows generate `.d.ts` from jsdoc comments?

**Comment by RReverser** [comment]
Well, I know they've added jsdoc support as part of https://github.com/Microsoft/TypeScript/issues/4789 meta-issue which allows to detect JSDoc types as if they were native TypeScript types, but I'm not sure if there's a tool to generate definitions out of that info.

**Comment by RReverser** [comment]
Some interesting links here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2103

**Comment by RReverser** [comment]
We might want to try https://github.com/fivetran/typescript-closure-tools - I suppose Closure annotations are compatible with JSDoc?

**Comment by inikulin** [comment]
Created separate issue: #125

**Comment by Supamiu** [comment]
Issue created on DefinetlyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9235
