### ISSUE TITLE
Ship TypeScript type definitions

### ISSUE THREAD

**Issue by inikulin** [inikulin/parse5#125]
See https://github.com/inikulin/parse5/issues/124#issuecomment-217394932

**Comment by inikulin** [comment]
@RReverser Can you give some examples of packages that ships TS definitions? I haven't worked closely with TS, so I would like to learn how it's usually done.

**Comment by RReverser** [comment]
@inikulin Lots has changed recently, I wrote them when it was only possible to install them from DefinitelyTyped and not as part of the package so that it would be recognized. Need to check docs.

**Comment by fictitious** [comment]
For current typescript version (2.0), they recommend to distribute type definitions in the same npm package. Typescript will use `types` field in package.json to find it.  [The documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) says

> If your package has a main .js file, you will need to indicate the main declaration file in your package.json file as well. Set the types property to point to your bundled declaration file.

For compatibility with previous typescript versions, you might want to publish on DefinitelyTyped. From the same document:

> Publish to @types
> Packages on under the @types organization are published automatically from DefinitelyTyped using the types-publisher tool. To get your declarations published as an @types package, please submit a pull request to https://github.com/DefinitelyTyped/DefinitelyTyped. You can find more details in the contribution guidelines page.

**Comment by RReverser** [comment]
@fictitious Thank you for clarifications!

> For compatibility with previous typescript versions, you might want to publish on DefinitelyTyped. 

Even in previous versions you can still pass path to definition under `node_modules` manually to `tsconfig`, so I don't think that part is needed.

**Comment by inikulin** [comment]
OK, I've tried to start working on this, using https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/parse5/parse5.d.ts as a starting point. But I've encountered a problem that it relies on node.js API definitions. How such issues are resolved in TS land: should we ship `node.d.ts` as well or we can reference it from DefinetlyTyped somehow?

**Comment by RReverser** [comment]
@inikulin You just use as it's already used in that file:

```
/// <reference path="../node/node.d.ts" />
```

Then, when definitions are published, TSD will automatically parse and add such references as dependencies. For example, when you now install `npm install @types/parse5` you can see that it also installs `@types/node`.

**Comment by inikulin** [comment]
@RReverser Oh, cool, thanks

**Comment by inikulin** [comment]
OK, I've been playing around with it whole evening and it's really cool that we've decided to implement it: I've found a couple of bugs in the docs, also our docs was a bit inconsistent regarding types. And now I'm planning to get rid of JSDOC for API reference: we'll use [typedoc](https://github.com/TypeStrong/typedoc) instead. So we'll have new nice type-consistent documentation and up-to-date TypeScript definitions. Which, I think, is pretty awesome.

**Comment by RReverser** [comment]
@inikulin Sounds like next step is to revisit idea of moving to TypeScript from #58 to avoid such docs bugs in future 😄

**Comment by MeirionHughes** [comment]
@inikulin if you're shipping the d.ts files within the npm module, and those definitions explicitly use node.js classes, then the new approach is to have a npm dependency to `@types/node`. At least that is my understanding.

**Comment by inikulin** [comment]
@MeirionHughes thank you for the clarification! Already found in TypeScript Handbook

**Comment by inikulin** [comment]
PR is here: https://github.com/inikulin/parse5/pull/164 Everyone interested are welcome to review.

**Comment by thisconnect** [comment]
So new documentation is going to be under http://inikulin.github.io/parse5 ?
I like that a lot, as browsing github wiki on mobile isn't great

**Comment by inikulin** [comment]
@thisconnect 
> So new documentation is going to be under http://inikulin.github.io/parse5 ?

Correct.

**Comment by inikulin** [comment]
@thisconnect Moreover, new documentation will have responsive design.
