### ISSUE TITLE
Serialize node with deep option

### ISSUE THREAD

**Issue by pedro93** [inikulin/parse5#126]
Is it possible to serialize a node but not its child elements? Having an option such as deep serialize being the default is the current implementation.
e.g:
´´´js
const parse5 = require('parse5');
//node is { type: 'tag', name: 'p', attribs: {} }
var content = parse5.serialize(node.parent, { treeAdapter: parse5.treeAdapters.htmlparser2, deep:false });
//content should now be "<p></p>"
´´´

**Comment by RReverser** [comment]
@pedro93 Just remove child elements before serialization, or clone only what you need into a new object. I don't think this needs to be a built-in.

**Comment by pedro93** [comment]
I was hoping there was a simpler solution, thank you for the quick answer @RReverser

**Comment by RReverser** [comment]
@pedro93 More configs for all the possible use-cases is certainly not a simpler solution in any library. APIs should be as minimal as possible to cover all the basic functionality, while keeping everything else for the userland code. Anyway, glad I could help.
