### ISSUE TITLE
Streaming implementation buffers text infinitely

### ISSUE THREAD

**Issue by RReverser** [inikulin/parse5#130]
If chunk has ended in DATA / RCDATA / ... states, it's possible to emit most of the collected text (before the entity or smth else) without buffering it between chunks. Currently, parse5 attempts to collect all the text into the internal buffer until it finds a beginning of the new token (like a starting tag), and only then emits altogether which is highly inefficient for documents containing long text chunks.

**Comment by inikulin** [comment]
Yap, #102 - related

**Comment by RReverser** [comment]
And maybe partially to #52 (although obviously not the biggest source :) ).

**Comment by inikulin** [comment]
The thing is that we need to figure out some heuristics for flushing unused data. I'm not sure, but I have feeling that if we'll do it on every [x]DATA state performance will degrade due to string operations

**Comment by inikulin** [comment]
#52 as far as I remember is totally about startup performance

**Comment by RReverser** [comment]
Well it says "Excessive RAM usage" in the title, and this is also one of potential causes of excessive RAM usage :)

**Comment by inikulin** [comment]
I'll change the title then to avoid future confusion =)

**Comment by RReverser** [comment]
Maybe better to create a separate issue since the reporter meant exactly memory usage?

**Comment by RReverser** [comment]
Okay, that works.

**Comment by RReverser** [comment]
>  that if we'll do it on every [x]DATA state performance will degrade due to string operations

I suggest to just check the current state / token on hibernation.
