### ISSUE TITLE
Does parse5 automatically "correct" html?

### ISSUE THREAD

**Issue by pedro93** [inikulin/parse5#131]
Hi, i've been using this library to create an html diff tool however I found a curious case, given the following html:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
	<a href="http://www.w3schools.com">Visit W3Schools.com!</a>
</body>
</html>
```
The library shows the following elements in the dom:
```js
{ type: 'tag',
  name: 'html',
  attribs: { xmlns: 'http://www.w3.org/1999/xhtml' } }
{ type: 'tag', name: 'head', attribs: {} }
{ type: 'tag', name: 'body', attribs: {} }
{ type: 'tag',
  name: 'a',
  attribs: { href: 'http://www.w3schools.com' } }
{ type: 'text', content: 'Visit W3Schools.com!' }
{ type: 'text', content: '\n\n' }
```
This shows there is a **head** element which does not exist in the original file. Hence I can only conclude it was inserted by the lib, is this correct? If yes is there any documentation I can read to become aware of these side-effects?

Thanks for reading this :)

**Comment by inikulin** [comment]
[Yes, parse5 corrects HTML just like your browser do](https://github.com/inikulin/parse5/wiki/Documentation#q-i-have-some-weird-output-from-the-parser-seems-like-a-bug)

> If yes is there any documentation I can read to become aware of these side-effects?

Nothing comes to my mind except the [HTML specification](https://html.spec.whatwg.org/multipage/) itself.

**Comment by pedro93** [comment]
Just as an afterthought, are you aware of any html parsing lib which does not operate in this way, that does not attempt to fix the html?

**Comment by RReverser** [comment]
>  that does not attempt to fix the html

This is not a "fix", this is the only way to parse it correctly. Otherwise you end up with useless results.

**Comment by UltraCakeBakery** [comment]
> [Yes, parse5 corrects HTML just like your browser do](https://github.com/inikulin/parse5/wiki/Documentation#q-i-have-some-weird-output-from-the-parser-seems-like-a-bug)
> 
> > If yes is there any documentation I can read to become aware of these side-effects?
> 
> Nothing comes to my mind except the [HTML specification](https://html.spec.whatwg.org/multipage/) itself.

@inikulin is there any way to disable this behavior? This is not something I expect from a parser...

**Comment by wooorm** [comment]
@UltraCakeBakery No, there is no option to diverge from the HTML spec
