### ISSUE TITLE
TypeError: str.replace is not a function

### ISSUE THREAD

**Issue by MarkPieszak** [inikulin/parse5#134]
Happening somewhere in the [escapeString function](https://github.com/inikulin/parse5/blob/600449c7404408e0539fc0fd7a81050ae548a658/lib/serializer/index.js#L39)

I'm trying to dissect exactly what is being serialized incorrectly, but I'm thinking it just needs some sort of either `.toString()` before attempting any `.replace()` or `("" + str).replace()`

I'm parsing with htmlparser2 before serializing, if that makes any difference.

**Comment by inikulin** [comment]
Can you provide minimal reproduction example, please?

**Comment by MarkPieszak** [comment]
Trying to get something together right now, sure!

**Comment by MarkPieszak** [comment]
Taking forever, but so far it looks like it's a checkbox that blew up when it was trying to serialize the attributes on it. Still looking to get more info. (Taking eternity to debug this one)

**Comment by MarkPieszak** [comment]
It seems it has to do with a checkbox that angular2 isn't rendering properly as `<input type="checkbox" checked="checked" />`.
Removing those html lines actually fixed the issue. Very strange I'll have to let them know about that...

At the moment I have a component passing `[checked]="item.completed"` which is either a true or false, this causes parse5 to error out here.

When I changed the template logic to `[checked]="item.completed === true ? 'checked' : '' "` this actually working.

**Comment by inikulin** [comment]
> It was working before (but that may of been due to encodeHtmlEntities: false we used to have.

Can't tell for sure. Can you set breakpoint in `escapeString` function and add watch to `str` value when it fails?

**Comment by inikulin** [comment]
Because if it's an object, it worked but worked wrong: attribute value (which seems like an object) implictily converted to the string on `html` concatenation.
