### ISSUE TITLE
Support an entry point for parsing text files

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#135]
https://html.spec.whatwg.org/#read-text

>  create an HTML parser, associate it with the Document, act as if the tokenizer had emitted a start tag token with the tag name "pre" followed by a single U+000A LINE FEED (LF) character, and switch the HTML parser's tokenizer to the PLAINTEXT state. Each task that the networking task source places on the task queue while fetching runs must then fill the parser's input byte stream with the fetched bytes and cause the HTML parser to perform the appropriate processing of the input stream.

It would be cool to have something where we could feed parse5 plaintext and it would do this for us, so jsdom could implement handling of plaintext mime types

**Comment by inikulin** [comment]
OK, I guess it unlikely will be used by anyone except jsdom, so I think we don't need shorthand for it. `Parser.parsePlainText` sounds good to everyone?

**Comment by RReverser** [comment]
What are the differences in result with feeding a parser with '&lt;plaintext>' + ...actual content...?

**Comment by inikulin** [comment]
@RReverser You can't emulate `plain-text` parsing by wrapping text with some markup: we need to wrap text with `<pre>` and parse it's content in `plaintext` tokenizer mode (`<pre>`'s are parsed in `data` mode in regular parsing algorithm).

**Comment by RReverser** [comment]
> You can't emulate plain-text parsing by wrapping text with some markup

This feels controversial to

> we need to wrap text with <pre>

**Comment by inikulin** [comment]
I mean we should emit `pre` and insert text, parsed in 'plaintext' mode as it's content.

**Comment by inikulin** [comment]
By `plain-text` parsing I mean parsing of text files

**Comment by RReverser** [comment]
Yeah, I'm asking (rather educationally) what's the difference with emitting `<plaintext>` (which already switches to PLAINTEXT on its own without special handling).

**Comment by inikulin** [comment]
Spec requires to emit `<pre>` instead of `<plaintext>`:

> act as if the tokenizer had emitted a start tag token with the tag name "pre" followed by a single U+000A LINE FEED (LF) character

**Comment by inikulin** [comment]
This is how it should look like:
```html
<html>
<head></head>
<body>
<pre>
[[Parser with PLAINTEXT tokenizer mode]]
</pre>
</body>
</html>
```

**Comment by domenic** [comment]
Woohoo, should be fun!!

**Comment by inikulin** [comment]
@domenic Now you guys have yet another reason to switch from parse5@1.x =)
