### ISSUE TITLE
Question: Walk the parsed dom + serialize each node

### ISSUE THREAD

**Issue by vigneshshanmugam** [inikulin/parse5#141]
I want to walk through the parsed DOM and serialize only that particular node. 

Example
```js
const parse5 = require('parse5');
const htmlparser2 = parse5.treeAdapters.htmlparser2;
const html = `
 <!doctype html>
<html>
   <head>
         ...
        <script type="placeholder"></script>
   </head>
</html>
const parsedNodes = parse5.parse(html, { treeAdapter: htmlparser2 })
const result = parse5.serialize(parsedNodes, { treeAdapter: htmlparser2 });
`;
```
Right now, the `result` contains the complete serialized DOM, But Instead I want to walk through each node and serialize only the ones in which I am interested in. 

```js
  function walkTheDOM(node, func) {
        if (node.name) {
            func.call(this, node);
        }
        node = node.firstChild;
        while (node) {
            this.walkTheDOM(node, func);
            node = node.next;
        }
    }
  const temp = [ ];
  function serialize() {
     const tagName = htmlparser2.getTagName(node);
     const attribs = htmlparser2.getAttrList(node);
    
     if (tagName === 'script' && attribs.type === 'placeholder') {
           // store in some temp array
          temp.push({ placeholder : 'dummy'});
     } else {
          const data = parse5.serialize(node, { treeAdapter: htmlparser2 });
          temp.push(data);
     }
  } 
  walkTheDOM(parsedNode, serialize);
```

But parse5 serializes all the way down to childNodes. Is there any way to serialize only the current node?

**Comment by inikulin** [comment]
If I get it right you want to serialize node without it's child nodes. If so, you can create document fragment using [treeAdapter.createDocumentFragment](https://github.com/inikulin/parse5/wiki/Documentation#TreeAdapter.createDocumentFragment) method. Add node to fragment's `childNodes` and temporally assign `[]` to node's child nodes. Serialize fragment, then restore node's `childNodes`.

**Comment by vigneshshanmugam** [comment]
just checked the code, will subclass it and provide hooks in my code. Thanks @inikulin
