### ISSUE TITLE
How can I prevent escaping html entities?

### ISSUE THREAD

**Issue by differui** [inikulin/parse5#143]
Here is my html:

```html
<span>></span>
```

After parse and serialize by parse5:

```html
<span>&gt;</span>
```

Here is `escapeString` method:

```js
Serializer.escapeString = function (str, attrMode) {
    str = str
        .replace(AMP_REGEX, '&amp;')
        .replace(NBSP_REGEX, '&nbsp;');

    if (attrMode)
        str = str.replace(DOUBLE_QUOTE_REGEX, '&quot;');

    else {
        str = str
            .replace(LT_REGEX, '&lt;')
            .replace(GT_REGEX, '&gt;');
    }

    return str;
};
```

How can I disable this function?

**Comment by inikulin** [comment]
> How can I disable this function?

Why would you like to disable it? What's your scenario?

**Comment by differui** [comment]
I am using parse5 works for `.cshtml` aka **Razor** which is template language of .NET MVC framework.

In Razor  `=>` is something else meaning.After process of parse5 the `=>` will be replaced into `=&gt;` which lead to syntax error.

So I am asking for preventing from parse5 replacing html entities.

@inikulin Thanks for you time.

**Comment by inikulin** [comment]
If razor is not a subset of HTML syntax, you shouldn't use HTML parser for it. Use razor parser instead
