### ISSUE TITLE
Clarify SAXParser documentation (Attributes)

### ISSUE THREAD

**Issue by MeirionHughes** [inikulin/parse5#147]
in the documentation: https://github.com/inikulin/parse5/wiki/Documentation#starttag-name-attrs-selfclosing-location

the SAXParser is listed as returning attributes with key/value. 

**attrs:**
>List of attributes in the { key: String, value: String } form.

but in reality the runtime is returning `{name, value}`. 
Also, since 2.2, attributes of the form `foo:bar="choochoo"` are seperated into `{name:"bar", value:"choochoo", prefix:"foo"}`

Could someone clarify that SAXParser is supposed to return Attributes of the form: 
```js
{
  name:string
  value:string
  prefix:string
}
```
if so can the docs be updated (and I will update typings on dt)

**Comment by inikulin** [comment]
Hi,

> Could someone clarify that SAXParser is supposed to return Attributes of the form

You are totally right.With exception that `prefix` present only for attributes that actually have prefix. Thank you for the find!

Can you issue a PR, please? Tip: you need to modify JSDOC comment: https://github.com/inikulin/parse5/blob/master/lib/sax/index.js#L166

**Comment by MeirionHughes** [comment]
Yup can do.

**Comment by MeirionHughes** [comment]
I've PRed that jsdoc change anyhow. https://github.com/inikulin/parse5/pull/148

**Comment by inikulin** [comment]
Closed via #148
