### ISSUE TITLE
White space between nodes in `#document`, `html`

### ISSUE THREAD

**Issue by wooorm** [inikulin/parse5#150]
Hi! Thanks for the awesome work on parse5. It’s really cool! 👍 

Currently, there isn’t any white-space in the AST directly inside `#document`, or at the start and end of `html`.

Example:

```html

<!doctype html>
<html lang="en-GB">
  <head>
    <meta charset="utf8">
    <title>Hello</title>
  </head>
  <body>
    <h1>World</h1>
    
  </body>
</html>
```

Yields (when passed through `parse5.serialize(parse5.parse(doc))`):

```html
<!DOCTYPE html><html lang="en-GB"><head>
    <meta charset="utf8">
    <title>Hello</title>
  </head>
  <body>
    <h1>World</h1>
    
  

</body></html>
```

Here’s an excerpt of the AST, and some of the points I expected `#text`s to be:

```js
{ nodeName: '#document',
  quirksMode: false,
  childNodes: 
   // expected `#text` here as first child
   [ { nodeName: '#documentType',
       name: 'html',
       publicId: null,
       systemId: null,
       parentNode: [Circular] },
     // expected `#text` here
     { nodeName: 'html',
       tagName: 'html',
       attrs: [ { name: 'lang', value: 'en-GB' } ],
       namespaceURI: 'http://www.w3.org/1999/xhtml',
       childNodes: 
        [ { nodeName: 'head',
            tagName: 'head',
            attrs: [],
            namespaceURI: 'http://www.w3.org/1999/xhtml',
            childNodes: [ [Object], [Object], [Object], [Object], [Object] ],
            parentNode: [Circular] },
          { nodeName: '#text', value: '\n  ', parentNode: [Circular] },
          { nodeName: 'body',
            tagName: 'body',
            attrs: [],
            namespaceURI: 'http://www.w3.org/1999/xhtml',
            childNodes: [ [Object], [Object], [Object] ],
            parentNode: [Circular] } ],
       parentNode: [Circular] } ] }
     // maybe even a `#text` with the final newline `\n` here?
```

The current behaviour makes it hard to keep the users style intact: I don’t care about the precise style, and know that that’s not possible/needed, but this seems like something “bug”-like?

**Comment by inikulin** [comment]
Hi!

Thank you for the kind words, really appreciate it. 

Spec requires to drop spaces before `<html>` and `<head>` elements (see: https://html.spec.whatwg.org/multipage/syntax.html#writing:the-html-element-2). So this is a by design behavior..

**Comment by domenic** [comment]
Here is an example showing how this works in browsers: http://jsbin.com/weseduhewo/edit?html,console

**Comment by wooorm** [comment]
Thanks for clarifying, @domenic, @inikulin, that makes sense!

Before I start writing code to re-insert them, would it be possible that behaviour to keep whitespace in there be added under a flag, similar to positional information? I know it’s an edge case but I can see others using it as well.

**Comment by inikulin** [comment]
@wooorm  We trying to not violate spec, even optionally. However, can you clarify your scenario, please? I guess it's some kind of html reprocessing, if so we have a related discussion going in #132. Maybe you would like to put your five cents there. Also, you may be interested in #144, @jescalan  already [implemented](https://github.com/inikulin/parse5/issues/144#issuecomment-243571393) `LexicalTreeParser` on top of parse5, maybe it will serve your needs.

**Comment by wooorm** [comment]
Yes, HTML reprocessing, similar to what reshape is doing.
I’ll add a comment over there, thanks for listening :)
