### ISSUE TITLE
Passing both AST nodes and raw HTML

### ISSUE THREAD

**Issue by wooorm** [inikulin/parse5#152]
One of the things I’m working on is a [Markdown AST](https://github.com/wooorm/mdast) -> [HTML AST](https://github.com/wooorm/hast).  While keeping correct HTML nesting and positional information (an example use cases is: https://github.com/wooorm/remark-lint/issues/77).

For example, this markdown:

```markdown
<blockquote>

* one;
* two;
* three.

</blockquote>
```

Yields something like the following in the markdown tree:

```js
{ type: 'root',
  children: 
   [ { type: 'html',
       value: '<blockquote>',
       position: { start: [Object], end: [Object], indent: [] } },
     { type: 'list',
       ordered: false,
       start: null,
       loose: false,
       children: [ [Object], [Object], [Object] ],
       position: { start: [Object], end: [Object], indent: [Object] } },
     { type: 'html',
       value: '</blockquote>',
       position: { start: [Object], end: [Object], indent: [] } } ],
  position: { start: { line: 1, column: 1 }, end: { line: 8, column: 1 } } }
```

Now, I can transform the markdown to parse5’s AST fine, but I’m of course running into problems with the raw HTML...and it’s rather hard to deal with this in the current parse5 set-up (to my knowledge). I’m able to simulate this sort-of by creating a parser and sometimes feeding it HTML (`<blockquote>`), and sometimes emitting stuff on `parser.tokenizer` (`tok._createStartTagToken` modifying `tok.currentToken.location` and so on), but it’s rather dirty.

This is related to passing a context node when parsing a fragment, but to my knowledge that wouldn’t work in the example above as the blockquote would be closed and the list added next to it instead of inside it.

What I’m looking for are a) pointers on how to do it (cleanly), or b) if there are changes in the API that could make this possible, whether it would if of interest to incorporate those in parse5.

It’s rather an edge case, I have to admit, but it would be quite awesome if it’s possible to keep the source locations intact through the transform 😬🎉

**Comment by inikulin** [comment]
If I get it right, you need some custom nesting logic, so you'll be able to incorporate markdown and parse5 ASTs. I believe [SAXParser](https://github.com/inikulin/parse5/wiki/Documentation#parse5+SAXParser) may do a trick for you. It will give you HTML tokens which you can incorporate in your AST then. You can use [treeAdapter methods](https://github.com/inikulin/parse5/wiki/Documentation#TreeAdapter) as an utility library to deal with the tree. Regarding position information - I think we can't do much here, except manually adjusting position information, produced by parse5. 

BTW, I'm not sure how markdown grammar works exactly. But wouldn't it be simpler to parse document as HTML first and then walk through text nodes and convert them to markdown?
