### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by sir-valentin** [inikulin/parse5#156]
Clearify please, it is possible use this parse for non node.js app?

**Comment by inikulin** [comment]
Hi, yes it's possible by using [browserify](http://browserify.org/), [webpack](https://webpack.github.io/) or any other bundler of your choice.

**Comment by sir-valentin** [comment]
Спасибо

Отправлено с помощью BlueMail<http://www.bluemail.me/r>


На 1 окт. 2016 г., в 18:01, Ivan Nikulin <notifications@github.com<mailto:notifications@github.com>> написал:п

Hi, yes it's possible by using browserify<http://browserify.org/>, webpack<https://webpack.github.io/> or any other bundler of your choice.
