### ISSUE TITLE
Attribute values without quotations

### ISSUE THREAD

**Issue by MeirionHughes** [inikulin/parse5#157]
when parsing 

`<element foo=value>`

the SAXParser will raise "startTag" event with attrs including "foo", where, the attr value equals the string `"value"`

However in firefox and chrome `foo=value` results in the attribute being ignored and not added to the element due to missing quotation marks. 

Unfortunately, there is no way to detect this via the SAXParser give its current behaviour. Is this a bug or by design?

**Comment by inikulin** [comment]
> However in firefox and chrome foo=value results in the attribute being ignored and not added to the element due to missing quotation marks.

It can't be true. Are you sure you parsing HTML document and not XML?

**Comment by MeirionHughes** [comment]
ahh; well, technically Aurelia (templating frontend) is using the browser to parse a template html segment, and then reporting that the attribute is missing.
