### ISSUE TITLE
No nested tags in a <title>

### ISSUE THREAD

**Issue by jescalan** [inikulin/parse5#158]
Hi there! Back again with another questionable issue.

In the process of working on [reshape](), I have run into a strange edge case bug while using our layouts plugin. Let me try to explain how it happens. Essentially, with this plugin you can use `block` and `extend` tags to be able to use layout files in your html. So for example, you could create a layout file as such:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Testing</title>
</head>
<body>
  <h1>Welcome to my site!</h1>
  <block name='content'></block>
</body>
</html>
```

And a page like this:

```html
<extends src='layout.html'>
  <block name='content'>
    <p>hello world!</p>
  </block>
</extends>
```

Then have each page rendered into this template using the reshape-layouts plugin, so it would produce something like this:

```html
<!DOCTYPE html>
<html>
<head>
  <title>Testing</title>
</head>
<body>
  <h1>Welcome to my site!</h1>
  <p>hello world!</p>
</body>
</html>
```

Now, I have a user who is trying to use a layout block to be able to customize the page's title on each page, something like this:

```html
<!DOCTYPE html>
<html>
<head>
  <title><block name='title'>Default title</block></title>
</head>
</html>
```

However, this block is actually parsed out as plaintext, which I assume is because parse5 parses tags nested inside the title tag (and maybe some others) as plaintext to ensure valid HTML. In this case, however, it's an issue because there will be no nested tags inside the title on the output, it's just an intermediate stage to ensure that layouts can work correctly.

I really was just posting this here because I am stumped as to how to move forward. It makes perfect sense to me why the contents of the title tag are parsed as plaintext and that clearly is the correct decision. But at the same time, the block functionality to change the title isn't really too uncommon among many layout systems, and I'm afraid it will be something that continues to come up down the line.

Any suggestions on what might be a good way to handle this issue?

**Comment by inikulin** [comment]
You are right, `<title>` content is always parsed as plain text. I believe the best way will be to raise an error or warning that tag accepts only text content. Here is the list of such elements: `title`, `noscript`, `noframes`, `style`, `script`, `xmp`, `iframe`, `noembed`.

**Comment by jescalan** [comment]
Yeah I think you may be right there. What I'm trying to figure out, I guess, is how a user might be able to customize the page title from the page rather than the layout. It seems like perhaps wrapping the entire title tag in a block might be the best way?

```html
<block name='title'>
  <title>custom title</title>
</block>
```

**Comment by wooorm** [comment]
@jescalan How about an attribute on elements which loads its content?

```xml
  <title block-name="title"></title>
```

**Comment by jescalan** [comment]
@wooorm This is an interesting idea, thanks for the suggestion! This would be a nice additional feature I think. Either way, will take the discussion back to  https://github.com/static-dev/spike/issues/31 since I think @inikulin has given his thoughts, and we're now after workarounds.
