### ISSUE TITLE
Option to preserve whitespace during parsing

### ISSUE THREAD

**Issue by thomas-darling** [inikulin/parse5#160]
Let's assume I have this HTML:
```html
<div foo="  attribute  with  important whitespace  ">
    element  with  important  whitespace
</div>
```

When using `parseFragment` to parse this, all whitespace is collapsed to single spaces.
Is there any way to parse this, _without_ collapsing the whitespace?

We need this for extracting content for translation from our templates, and it's currently blocking us from using this parser. The reasoning is, that any element may be styled to preserve whitespace using CSS, so for _some_ elements and attributes, we need to get the content with the whitespace preserved - and of course, then there's also elements that preserve whitespace by default, such as `<pre>`.

Maybe the content should _internally_ be parsed and stored without collapsing, and then each `ASTNode` and `ASTAttribute` should have a `collapse` property which determines how the content of the element and its children is exposed/serialized.
This should default to `null`, corresponding to the default collapse behavior, but may be set explicitly to `true` or `false` where needed. When set to `true`, the value of the attribute or node, and any child nodes not explicitly set to `false`, should then return the content with whitespace preserved - and when serializing, whitespace should be preserved the same way.

Thoughts?

**Comment by inikulin** [comment]
Hi Thomas.

parse5 doesn't collapse any whitespaces (and shouldn't in this particular case). Here is the live demo with markup you've provided: https://runkit.com/580f9ad527cf550013c20537/580f9ad527cf550013c20538

**Comment by thomas-darling** [comment]
# D'oh!
You're absolutely right - thanks, and awesome work on parse5, by the way!

The reason for my confusion was, that the **debugger** in Visual Studio Code, of all things, is apparently collapsing whitespace when presenting the value of a variable - including in watches, mouse-over previews, and when just executing the variable name in the console. I'll go create a bug for them instead!
