### ISSUE TITLE
More examples and comment on the docs

### ISSUE THREAD

**Issue by albertbuchard** [inikulin/parse5#165]
The docs are very difficult to understand for a newbie, there is no comment, no use case...

Thank you for your consideration !

Albert

**Comment by inikulin** [comment]
@albertbuchard Hi. Can you elaborate what kind of comments and use cases will be helpful for you, please.

**Comment by inikulin** [comment]
Ironically this issue doesn't contain any comments or use cases for documentation problem. However, I have some ideas on how documentation can improved.
