### ISSUE TITLE
Self-closing svg elements

### ISSUE THREAD

**Issue by jescalan** [inikulin/parse5#168]
Hi there! I had an issue opened by a user recently in reshape-parser saying that parse5 doesn't allow a self-closing `<path>` tag, which is how it is [specified by standards](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path):

https://github.com/reshape/parser/issues/13

Any thoughts on this?

**Comment by wooorm** [comment]
I think `<path/>` is just an unknown HTML element for parse5 (as it expects HTML), or browsers for that matter. Unless it’s wrapped in an `<svg>` tag?

**Comment by inikulin** [comment]
Self-closing tags are XML thing, so they are only allowed in foreign content (`<svg>` or `<math>` content), see: https://runkit.com/582b0e9ebe07a80014bf1e82/58400d2db3ef0f0013bae090

**Comment by jescalan** [comment]
Makes sense -- thanks for the clarification!
