### ISSUE TITLE
Question: which is correct?

### ISSUE THREAD

**Issue by mysticatea** [inikulin/parse5#170]
- [lib/index.d.ts#L16](https://github.com/inikulin/parse5/blob/ca29cffdea0f81436e9b901c0d3f31be3b924b66/lib/index.d.ts#L16) says `LocationInfo#col` is zero-based index.  
  (note: this comment is popped up in [Visual Studio Code](http://code.visualstudio.com/) when I put the mouse cursor on the property. Also, it's shown in auto-completions.)
- [Wiki](https://github.com/inikulin/parse5/wiki/Documentation#LocationInfo) says `LocationInfo#col` is one-based index.

Which is correct?

**Comment by inikulin** [comment]
It's one-based. Thank you for pointing it out!
