### ISSUE TITLE
Keep origin document tree

### ISSUE THREAD

**Issue by thanhtrixx** [inikulin/parse5#171]
I want to parse html. But:
+ if use parse() when parse ```<div></div>``` then parser5 auto add html + body nodes to document tree
+ if use parsefragment() when parse ```<html><body><div></div></body></html>``` then parser5 auto delete html + body nodes from document tree

Have any option to parse html keep origin document free info?
Ex:
+ ```<div></div>``` -> ```div {}```
+ 
```
<html>
  <body>
    <div></div>
  </body>
</html>
```
->
```
html {
  body {
    div {}
  }
}
```
Tks!!

**Comment by RReverser** [comment]
I don't get what you're asking for to be honest. Just custom serializer? Yes, you can implement it.

**Comment by thanhtrixx** [comment]
@RReverser Sorry for my bad question. My English skill is not good. I've updated my question. Tks.

**Comment by michael-ciniawsky** [comment]
@thanhtrixx Just use `parse5.parseFragment('<div></div>')` from the beginning ? 😛 `parse5.parse` expects a valid HTML Document and adds the nessecary tags if not present (spec compliant parser, like in browsers). In case I miss something maybe take a look at the [SAX Parser](http://inikulin.github.io/parse5/classes/saxparser.html) aswell

**Comment by thanhtrixx** [comment]
@michael-ciniawsky use can input full HTML or 1 fragment of HTML. I'll implement 1 method to indicate input HTML are full or not
