### ISSUE TITLE
Parsing a HTML fragment and keeping the case

### ISSUE THREAD

**Issue by thenoseman** [inikulin/parse5#172]
Hi,

thanks for creating this awesome parser!

I'm trying to parse some HTML coming from an angular template
```
...
<a routerLink="/somepath">somepath</a>
...
```

After parsing this fragment the attrs show that `routerLink` has been downcase to `routerlink`.

This of cause poses some problems with angulars runtime parser since it expects camelcased attributes.

Is it possible to pass an option to keep the case of the attributes?

Thanks!
Frank

ps. Playground demonstration what I mean: http://astexplorer.net/#/1CHlCXc4n4/73

Edit:
Reference: https://www.w3.org/TR/html52/syntax.html#elements-attributes

**Comment by RReverser** [comment]
This has been answered in at least #133 and #116.
