### ISSUE TITLE
Unclosed tags are discarded

### ISSUE THREAD

**Issue by TimvdLippe** [inikulin/parse5#173]
The editor plugins of the Polymer team contain an autocompleter for several types: elements, attributes, attribute values, etc... In case of the element autocompletion, given the following document invoking the autocompleter at `|` should autocomplete to for example `<paper-button>`.
```html
<paper-|
```
The editor plugin makes use of `parse5` to analyze the document tree of the file to determine what to serve as autocompletion. However, unclosed tags such as the one above are discarded in the document tree nor are they available as text node (with value `<paper-`). See the corresponding issue at https://github.com/Polymer/polymer-editor-service/issues/37

This is probably more of a question, but is it possible to supply these unclosed tags such that `parse5`-users can use them to implement features like autocompletion? Probably the cleanest solution is putting it in a textnode, but I am not sure if that is HTML-spec-compliant.

CC @rictic

**Comment by webdesus** [comment]
@inikulin its problem is observed only when <paper-| last tag in the document. If the document include after not finished tag another tags, problem not appears. I can try decide if you not against.

**Comment by TimvdLippe** [comment]
In my testing the problem appears regardless if tags are after the unclosed tag.

**Comment by RReverser** [comment]
@TimvdLippe HTML spec is very explicit about each edge case, including how to restore errors, and having custom way to do so would be a violation from the spec. But if you want to autocomplete, can't you manually insert `>` in the cursor position before passing to the parser?

**Comment by TimvdLippe** [comment]
@RReverser That would solve this edgecase, but that would then also break the case when we autocomplete for example `<paper-></paper->`?

**Comment by webdesus** [comment]
@TimvdLippe oh yes, i am not correct looked result my test. First element after not finished tag go to attribute, another tags work fine, like i said above

my test:

```
var parse5 = require('parse5');
var document1 = parse5.parse('<paper- <p><div>');
console.log(document1.childNodes[0].childNodes[1].childNodes)

```
i see next result:

```
{
   tagName: 'paper-'
   attrs: <p
   childNodes:[
      {tagName: 'div'}
   ]
}
```

**Comment by TimvdLippe** [comment]
@webdesus Hm yes I can confirm the above output. It is weird the node was not showing up in the editor-service, I will need to reinvestigate.

So current issue is that nodes after an unclosed tag are swallowed and reported as attributes of the unclosed tag.

**Comment by inikulin** [comment]
Hi guys,

> I think it's bug, but maybe owener have own look

> So current issue is that nodes after an unclosed tag are swallowed and reported as attributes of the unclosed tag.

It's perfectly legit. The issue with HTML autocompletion is that HTML is designed to swallow **any** input. So if you feed parser malformed HTML it will not bailout with syntax error, but will try to re-interpret it instead, like we have in this case. As a solution you can try to implement some simple HTML parser with relaxed grammar but you will run into edge-cases anyway. The conclusion is that you can't avoid edge cases like this with HTML while working with partial input. So just

![stickerline-elsa-let-it-go](https://cloud.githubusercontent.com/assets/453071/21545304/b8ddc2ae-cde7-11e6-9275-2e1ac0b718fe.png)

**Comment by TimvdLippe** [comment]
@inikulin Okay thanks for the explanation, it does make sense. We will have to figure out a solution for our usecase.
