### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by felixsanz** [inikulin/parse5#174]
Is this normal?

```javascript
const p = require('parse5')
const t = '<code>const foo = (i) => {\r\n  console.log(i)\r\n}\r\n\r\nfoo(3)</code>'
const d = p.parseFragment(t)
console.log(d.childNodes[0].childNodes[0].value)
// const foo = (i) => {\n  console.log(i)\n}\n\nfoo(3)
```

Why this happens even in a windows box? Is common that libraries strips off the \r character?

Probably not a bug, but I'm trying to understand whats going on.

**Comment by RReverser** [comment]
As [documentation suggests](https://inikulin.github.io/parse5/#q-i-have-some-weird-output-from-the-parser-seems-like-a-bug-):

> Just try it in the latest version of your browser before submitting an issue.

If you try this in your browser, you will see that `\r` is stripped in just the same way. This is part of HTML tokenization algorithm which normalizes any newlines to `\n`.

**Comment by felixsanz** [comment]
@RReverser You closed the issue so fast, hah

The `\r` is inside a <pre> tag and also inside a <code> one, so why is not respected? HTML tokenizer shouldn't touch this tags? Or it is impossible to represent that character in HTML?

**Comment by RReverser** [comment]
@felixsanz I closed the issue just because it's not really an issue, but I'm happy to answer your questions. As I said, it's part of tokenization algorithm, not tree construction - that is, newlines are normalized way before you know within which tag you're.

You might want to check HTML spec for explanations: [Preprocessing the input stream](https://html.spec.whatwg.org/multipage/syntax.html#preprocessing-the-input-stream)

> U+000D CARRIAGE RETURN (CR) characters and U+000A LINE FEED (LF) characters are treated specially. Any LF character that immediately follows a CR character must be ignored, and all CR characters must then be converted to LF characters. Thus, newlines in HTML DOMs are represented by LF characters, and there are never any CR characters in the input to the tokenization stage.

**Comment by RReverser** [comment]
As for your second question, check out this tweet from #HTMLQuiz series we did with Simon: https://twitter.com/zcorpan/status/788712392075186176 (and following answer)

**Comment by felixsanz** [comment]
@RReverser Thanks!
