### ISSUE TITLE
Question: escape mechanism

### ISSUE THREAD

**Issue by songsiqi** [inikulin/parse5#175]
I use a directive of `Vue` and there exists `&&` in the directive.

```
<div :src="case1 && case2 ? val1 : val2"></div>
```

After invoking `serialize`, `&&` will be escaped to `&amp;&amp;`. How to avoid this?

Thanks.

**Comment by inikulin** [comment]
There is no canonical way to avoid it, since such serialization will not be per spec. However, you can monkey patch [SerializerStream](http://inikulin.github.io/parse5/classes/serializerstream.html) to achieve desired functionality:
```js
const SerializerStream = require('parse5');

var s = new SerializerStream(document);

s.serializer.constructor.escapeString = str => str;

var result = '';

s.on('data', chunk => result += chunk);
...
```
