### ISSUE TITLE
parse5.parse return parse5.AST.Document instead of parse5.AST.Default.Document

### ISSUE THREAD

**Issue by GrandSchtroumpf** [inikulin/parse5#176]
Hello,
I don't know if it's meant to, but parse5 returns a parse5.AST.Document when I do : 
```
parse5.parse("<div></div>", {
      treeAdapter: parse5.treeAdapters.default
 });
```
By doing so I can't access the childNodes property of the document ...
Is there any workaround to access this property with TypeScript ? 
Thanks !

**Comment by RReverser** [comment]
Documentation addresses this very problem: http://inikulin.github.io/parse5/#typescript-definitions
