### ISSUE TITLE
Question: boolean attribute value

### ISSUE THREAD

**Issue by songsiqi** [inikulin/parse5#177]
I use `parse5` to transform some `Vue` code. To some directives such as `v-else` and `scoped`

After parsing and serializing, `<style scoped></style>` becomes to `<style scoped=""></style>`. Is there any way to avoid the appearance of `=""`?

Thanks.

**Comment by tw93** [comment]
+1

**Comment by inikulin** [comment]
Hi there is no canonical way to avoid it: attributes without value semantically is just a shorthand for the attributes with empty value. So, once `<style scoped></style>` gets parsed there is no way to distinguish it from `<style scoped=""></style>` in AST. HTML spec requires attributes with empty values to be serialized in explicit form. However, you can workaround it by overriding [serializeAttribute method](https://github.com/inikulin/parse5/blob/master/lib/serializer/index.js#L105) the same way as I suggested in #175. To conclude, judging from your previously open issues I guess it makes sense to implement custom Vue-specific serializer.

**Comment by RReverser** [comment]
One more suggestion: if you want to transform some HTML nodes but preserve formatting for others, you can also use `startOffest` / `endOffset` from node's location to `.slice(...)` pieces from original string whenever node is unchanged. This way, you will preserve formatting on any untouched pieces, and also will likely get better performance than with serializing entire AST from scratch.
