### ISSUE TITLE
Example returns: Uncaught TypeError. Example update needed.

### ISSUE THREAD

**Issue by dimwell-git** [inikulin/parse5#178]
const parse5 = require('parse5');
const http = require('http');

// Fetch the google.com content and obtain it's <body> node
http.get('http://google.com', res => {
   const parser = new parse5.ParserStream();

   parser.once('finish', () => {
       console.log(parser.document.childNodes[1].childNodes[1].tagName); //> 'body'
   });

   res.pipe(parser);
});

**Returns Error:** Uncaught TypeError: Cannot read property 'childNodes' of undefined

Please update example, so there is not confusion.
This example returns "body"

parser.once('finish', () => {
       console.log(parser.document.childNodes[0].childNodes[1].tagName); //> 'body'
   });

**Comment by RReverser** [comment]
Please send a pull request, this is a simple change and PR is a much better medium for changes :)
