### ISSUE TITLE
Advice needed.

### ISSUE THREAD

**Issue by dimwell-git** [inikulin/parse5#179]
I used example from documentation:  parse5.ParserStream().
Once the document tree received is there direct way to query required element ?

**Comment by RReverser** [comment]
Sorry, but question is unclear.

**Comment by madbence** [comment]
@dimwell-git if you need something like `document.querySelector`, use [`jsdom`](https://github.com/tmpvar/jsdom) or [`cheerio`](https://github.com/cheeriojs/cheerio), they both provide a way to query&manipulate the parsed DOM tree.

**Comment by inikulin** [comment]
[jsdom](https://github.com/tmpvar/jsdom) is greate and it uses parse5 as a parser under the hood. However, since jsdom tries to implement full featured DOM it may be too heavy weight for some scenarios. For basic parse5 AST traversing you can take a look at [dom5](https://github.com/Polymer/dom5).
