### ISSUE TITLE
location.startTag not available if end tag is missing in html

### ISSUE THREAD

**Issue by palamccc** [inikulin/parse5#181]
In following code, it works as expected.

```js
const parse5 = require('parse5');
const tree1 = parse5.parseFragment('<p>hello</p>', { locationInfo: true });
console.log(tree1.childNodes[0].__location);
```

```
{ line: 1,
  col: 1,
  startOffset: 0,
  endOffset: 12,
  startTag: { line: 1, col: 1, startOffset: 0, endOffset: 3 },
  endTag: { line: 1, col: 9, startOffset: 8, endOffset: 12 } }
```

In following code, while parsing malformed html '&lt;p&gt;hello', __location object is not complete.
can you add startTag also in __location ? I understand its malformed html, i want to print warning to user, whenever there is startTag without endTag. so this will be usefull if anyone builds linting tool on top of parse5.

```js
const tree2 = parse5.parseFragment('<p>hello', { locationInfo: true });
console.log(tree2.childNodes[0].__location);
```
```
{ line: 1, col: 1, startOffset: 0, endOffset: 3 }
```

**Comment by inikulin** [comment]
Published as `v3.0.2`
