### ISSUE TITLE
Html character entities parsing error

### ISSUE THREAD

**Issue by songsiqi** [inikulin/parse5#182]
Using `parse5.parseFragment` method, the html code below

```
<text>&#xe606;&#xe605;&#xe604;&#xe603;&#xe602;&#xe601;&#xe600;</text>
```

is parsed to

```
text value { nodeName: '#text',
  value: '',
  parentNode: ...
```

**Comment by inikulin** [comment]
Hi,

I can't see any bugs here:
https://runkit.com/58bdb485d0de8a0014aa1f3d/58c0331fb316500013011735

**Comment by songsiqi** [comment]
But I have to use `ch.charCodeAt(0).toString(16)`. 

If the html code is

```
<text>&#xe606;&#xe605;&#xe604;&#xe603;&#xe602;&#xe601;&#xe600;content内容</text>
```

How to parse the value?

**Comment by inikulin** [comment]
I'm not sure I understand what you're asking. Can you provide comprehensive example of what you're expecting and your usage scenario?

**Comment by songsiqi** [comment]
I want common ways to get text node values, which contain common characters, icon font, html entities, and so on.

```
<text>&#xe606;&#xe605;&#xe604;&#xe603;&#xe602;&#xe601;&#xe600;content内容</text>
```

```
text value { nodeName: '#text',
  value: '&#xe606;&#xe605;&#xe604;&#xe603;&#xe602;&#xe601;&#xe600;content内容',
  parentNode: ...
```

Or some other ways to get the text value `&#xe606;&#xe605;&#xe604;&#xe603;&#xe602;&#xe601;&#xe600;content内容`, not only using particular method to parse icon font.

**Comment by inikulin** [comment]
The thing is that html entities is **not** text content. HTML parser transforms them to text content as you see in your example. If you need source code that represents text content then consider using [locationInfo](http://inikulin.github.io/parse5/interfaces/options.parseroptions.html#locationinfo).
