### ISSUE TITLE
Can I use the SAX parser to parse html as a big string as opposed to streaming from a url?

### ISSUE THREAD

**Issue by elgs** [inikulin/parse5#183]
The example code from this url: http://inikulin.github.io/parse5/classes/saxparser.html shows how to use the parser5 SAX api to parse html as a stream from a url. Now if I have some html as a string, how can I parse it with parse5 SAX api? It seems the documentation just gives an advanced usage example and forgets to give the basic one.

Also in the `parser.on('text', text => {})` callback, is there any way to tell which tag the text is currently in? For example, if I'm only interested in the text between the `<title />` tag. How can I know from the `on('text', text=>{})` callback that it is currently within the `<title />` tag or another tag that I'm not interested in? Thanks.

**Comment by inikulin** [comment]
As stated in documentation `SAXParser` is a regular node.js writable stream. This repository doesn't intended to provide documentation for standard node.js API. Use [node documentation instead](https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_writable_streams).

> Also in the parser.on('text', text => {}) callback, is there any way to tell which tag the text is currently in? For example, if I'm only interested in the text between the <title /> tag. How can I know from the on('text', text=>{}) callback that it is currently within the <title /> tag or another tag that I'm not interested in?

Why you try to use `SAXParser` if you need information about nesting? This completely opposite of what SAX parsers are usually used for. Use `ParserStream` instead.

**Comment by elgs** [comment]
So I have to wrap a string into a stream in order to use the SAXParser, is it correct?

**Comment by inikulin** [comment]
[No](https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_writable_streams)

**Comment by elgs** [comment]
So is there a way for your API to wotk with strings, as opposed to streams. I already have the HTML as a string, and I want to output parsed result to string, as opposed to a file stream? If the answer happened to be yes, can you show me some example code? My assumption is based on your answer saying warping strings into streams is not an option, which heavily confused me.

**Comment by inikulin** [comment]
@elgs Did you manage to navigate to link I gave you already two times? Because there is answer to your question and examples there.

**Comment by inikulin** [comment]
> I want to output parsed result to string, as opposed to a file stream

`SAXParser` doesn't produce any compound results, it just raises a number of events with chunks of information about markup.

**Comment by elgs** [comment]
> @elgs Did you manage to navigate to link I gave you already two times? Because there is answer to your question and examples there.

@inikulin Yes, but I didn't find anything talking about how to work string.

> `SAXParser` doesn't produce any compound results, it just raises a number of events with chunks of information about markup.

I understand that. My question is about your example code. The example code read data from a url, and write results into a file. What I'm after is reading data from a string, and output as another string. I understand it might be off topic to `SAXParser`, but my question is regarding your example code.

> Why you try to use SAXParser if you need information about nesting? This is completely opposite to what SAX parsers are usually used for. Use ParserStream instead.

That's not true. I am only interested in certain part of the html, once I got them, I will completely ignore the rest of the html. For this question, I can use a stack/array to store such information, by pushing in the tag name on tag open and popping the same out on tag close. I don't think it is completely opposite to what SAX parsers are usually used for.

**Comment by elgs** [comment]
Essentially, your example code showed how the `SAXParser` piped an http response and a file output stream, and I'm wondering how the `SAXParser` will pipe two strings. You showed me Nodejs stream APIs, and at the same time, you gave me 'No' to possibility to wrap strings into streams in order to use your API.

As I last resort, in order to use the API, I probably have to save my html string as a file, and upload it to a web server.

**Comment by inikulin** [comment]
@elgs 
1. `SAXParser` is a Node.js `TransformStream` which means it's both `WritableStream` and `ReadableStream`. The very first example in [Node.js documentation](https://nodejs.org/api/stream.html#stream_writable_streams) for `WritableStream` shows how to feed it with strings:
> While specific instances of Writable streams may differ in various ways, all Writable streams follow the same fundamental usage pattern as illustrated in the example below:
```js
const myStream = getWritableStreamSomehow();
myStream.write('some data');
myStream.write('some more data');
myStream.end('done writing data');
```

Considering example above, here is how you can pass string to `SAXParser`:
```js
const parser = new SAXParser();

parser.on('text', text => { /* ... */ });

parser.end('<div>Hi there!<div>');
```
2. `SAXParser` **doesn't** return anything. You can use it as a proxy between feeder and consumer streams (e.q. response and request) to analyze content while it's gets transferred between mediums. It doesn't modify content that piped into it and passes it to consumer stream as is. Therefore, since you already have whole string in memory in your case there is no reason to pipe it anywhere: you can just simply write it to output stream (if you have one).

3.  The thing with SAX parsers is that they are memory and computationally efficient because they don't need to track nesting information. Otherwise, you need to consider using full-featured parsing. Nesting in HTML is extremely tricky. Thus, solution from https://github.com/inikulin/parse5/issues/183#issuecomment-285699547 will give incorrect results in lots of cases. Nevertheless, if accuracy is not a big concern for you then you can try this approach on your own risk.

**Comment by elgs** [comment]
That is exactly my question. How to turn my string into a stream. I got this error:

```
const myStream = getWritableStreamSomehow();
ReferenceError: getWritableStreamSomehow is not defined
    at repl:1:18
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:336:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:533:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
    at REPLServer.Interface._onLine (readline.js:238:10)
    at REPLServer.Interface._line (readline.js:582:8)
```
