### ISSUE TITLE
Support boolean attributes (`defer` vs. `defer=""`)

### ISSUE THREAD

**Issue by FredKSchott** [inikulin/parse5#184]
Follow up to discussion in https://github.com/inikulin/parse5/issues/177

parse5 will parse boolean attributes (without a value) as having a value of `""`.  See the `async` attribute in the example below: 

```
// html fragment
<script type="text/javascript" src="javascript.js" async></script>

// parse5.parse()
attrs: [
  {"name":"type", "value":"text/javascript"},
  {"name":"src", "value":"javascript.js"},
  {"name":"async", "value":""}
]
```

As @inikulin mentioned in #175, this is an accurate representation of the value, since the spec says some value is needed even when shorthand is used: 
> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

However, boolean attributes are still a real type of attribute that the current parse5 AST cannot represent correctly. the parse5 AST loses information about whether an attribute was a boolean or just a string with a value of "". This is type information that is properly represented in the [HTML spec for element attributes](https://html.spec.whatwg.org/multipage/dom.html#htmlelement):

```
interface HTMLElement : Element {
  [CEReactions] attribute DOMString title;
  // ...
  [CEReactions] attribute boolean hidden;
  // ...
```

The lossy AST parsing makes it impossible to accurately recreate the source if we re-serialize.

Would the team consider adding a bit of information to the `Attribute` type to represent the data type of the scanned attribute? This could be a flag for boolean/string, or a string to represent the several different possible data types that are possible [in the spec](https://html.spec.whatwg.org/multipage/dom.html#htmlelement).

**Comment by RReverser** [comment]
> However, boolean attributes are still a real type of attribute that the current parse5 AST cannot represent correctly.

It's not. parse5 represents values correctly - any attribute can have only a string value. What you're providing below is a DOM representation which converts strings to numbers (e.g. `tabindex`), space-separated token lists (e.g. `class`), booleans (e.g. `hidden`) and so on, but that's a completely different workflow and has nothing to do with HTML parsing itself (and your spec link points to DOM section too).

As far as HTML parser (whether parse5 or in-browser) is concerned, `attr` and `attr=""` are exactly same, and further DOM conversions don't 
![capture](https://cloud.githubusercontent.com/assets/557590/23929388/b06b50d4-091d-11e7-8883-864c2a8db650.PNG)
distinguish between them either:

**Comment by FredKSchott** [comment]
@RReverser that's fair enough, I played around with `DOMParser()` a bit myself and couldn't find any meaningful information for shorthand vs. longhand boolean attribute notation either. 

I still believe that this is a useful feature for parsing & re-serializing an HTML document truthfully. Re-serializing isn't a goal of a browser's DOM parser so I can understand why this isn't something they've added support for.

**Comment by inikulin** [comment]
@FredKSchott The thing with HTML is that it's not parse-serialize round trip-proof anyway (at least unless you don't have fully conforming markup). Even adding ad hoc solution for this particular case we will not get any closer to 100% identical/correct re-serialization. The root cause of this lies in the design of HTML and it's error recovery mechanisms.

**Comment by imingyu** [comment]
```javascript
var p5 = require('parse5');

var result = p5.parse('<div id="d1" show>D1</div><div id="d2" show="off">D2</div>', {
    locationInfo: true
});

var body = result.childNodes[0].childNodes[1];


var transformResult = [];
body.childNodes.forEach(item => {
    var element = {
        tagName: item.tagName,
        attrs: []
    };
    var onlyNameAttrs = [];
    Object.keys(item.__location.attrs).forEach(name => {
        var attr = item.__location.attrs[name];
        if (name.length === attr.endOffset - attr.startOffset) {
            onlyNameAttrs.push(name);
        }
    });
    item.attrs.forEach(attr => {
        if (onlyNameAttrs.indexOf(attr.name) === -1) {
            element.attrs.push({
                name: attr.name,
                value: attr.value
            })
        } else {
            element.attrs.push({
                name: attr.name,
                onlyName: true
            })
        }
    });

    transformResult.push(element);
});

console.log(JSON.stringify(transformResult));
//[{ "tagName": "div", "attrs": [{ "name": "id", "value": "d1" }, { "name": "show", "onlyName": true }] }, { "tagName": "div", "attrs": [{ "name": "id", "value": "d2" }, { "name": "show", "value": "off" }] }]
```
