### ISSUE TITLE
Parse html fragments inside markdown document

### ISSUE THREAD

**Issue by klaszlo** [inikulin/parse5#185]
My usecase would be to recognize html fragment inside markdown document, change some attributes, then serialize back to the original markdown document. 
In the meantime do not really modify the non-html strings (markdown) around valid html fragments.

Example:

    [back][0]
    
    ## 20161220, tuesday
    
    <div>
      <label for="20161220-harbor-freight.jpg-09gpx">
      <img src="/money/rsc/20161220-harbor-freight.jpg" title="20161220-harbor-freight.jpg" height="auto" width="160">
      <span style="display:inline-block;vertical-align:top;background:lightgreen;">
        <strong>20161220</strong><br/>
        Harbor Freight<br/>
        9.99 USD<br/>
        <em>description</em><br/>
        tags: harbor tools<br>
      </span>
      </label>
    
      <input type="checkbox" id="20161220-harbor-freight.jpg-09gpx" class="toggle">
      <div>
        <img src="/money/rsc/20161220-harbor-freight.jpg" style="max-width:100%;height:auto">
      </div>
    </div>
    
    There may be (and there is) many more pics like the above, see more [here][1]
    
    [0]: /money
    [1]: /money/more

So in the above example, I would like to change `background:lightgreen` and the `tags: harbor tools` text reliably. 
It is part of a homebrew angular app, which is basically a markdown editor with "html snippet wizard", 
so many predefined html strings can be inserted, which is otherwise impossible 
to do with plain markdown.

I would like to change the html snippets programmatically, so buttons on a page, to highlight all image
which fullfills a given condition (say time is less then 20161220), and highlight is basically the `background:lightgreen` in the above example.

What would be the best way to use parse5 in the above usage scenario?
(I tried parse the markdown text, but it is impossible to transform back to the original markdown source.
Maybe I should implement my own parsers?)

Any idea is much appreciated, maybe it is completely offtopic, so feel free to close it, if it is unappropriate here.

**Comment by inikulin** [comment]
Hi,

I guess you need markdown parser which provides source location information, such that you'll be able to get source location information for HTML-code markdown AST node, then get substring that contains HTML, parse it with parse5, modify it the way you like, serialize it back and then insert back into original string instead of parsed fragment. Overall, this is how I see it. However, we don't provide and don't have any plans to provide facilities to deal with markdown.

**Comment by wooorm** [comment]
This could help: https://github.com/wooorm/rehype-remark
