### ISSUE TITLE
Aren't I supposed to be able to import interfaces from the AST namespace?

### ISSUE THREAD

**Issue by mightyiam** [inikulin/parse5#187]
For example, `DocumentFragment`?

```ts
import { DocumentFragment } from 'parse5'
```

Now, I realize that `DocumentFragment` is an existing DOM type, from TypeScript...

So, what am I missing? I have a function that accepts an `AST.DocumentFragment`. How do I get that type do be able to go `(frag: DocumentFragment) => null` or so?

**Comment by inikulin** [comment]
You can import interface but just like you mentioned they're namespaced:
```ts
import {  AST  } from 'parse5';

function myFunc(doc: AST.Document) {
  
}
```
