### ISSUE TITLE
Use treeAdapter to attach location information

### ISSUE THREAD

**Issue by inikulin** [inikulin/parse5#189]
Currently location always implicitly stored as `__location` property. It breaks paradigm of not enforcing tree format in parse5. It makes sense to introduce `treeAdapter.setNodeLocationInfo` method that will give implementers opportunity to decide how to store it. 
Another thing that bothered for a long time is the name of the `__location` property. Since where will be a major version bump due to the changes in the location info layout required for error reporting feature I guess it's a good chance to rename it to `location`.

**Comment by diervo** [comment]
@inikulin Are you planning to use the same paradigm to inject the error types?

I like an imperative API much better than the simple AOP hooks that exists today for location, which would be very hard to reason once you have more than one injection.

**Comment by inikulin** [comment]
Location will still be implemented via hooks. For errors there will be combination of imperative and AOP. I don't like it either, but we can't use imperative approach for this feature since it will harm performance in basic case. Maybe, maybe I'll revisit this topic one day being fed up with current approach, but meanwhile it doesn't bother me that much.

**Comment by inikulin** [comment]
Tree adapter will need to implement two methods:
- `setNodeSourceCodeLocation`
- `getNodeSourceCodeLocation`

`__location` property will be renamed to `sourceCodeLocation`.

Both changes are breaking.
