### ISSUE TITLE
complain/throw on invalid html

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#193]
Instead of automatically correcting invalid structures/etc, perhaps it could optionally complain. This would help prohibit invalid HTML in source code.

**Comment by inikulin** [comment]
There is no such thing as an "invalid HTML". There is non-conforming HTML. What's use case for that?

**Comment by stevenvachon** [comment]
> This would help prohibit [non-conforming] HTML in source code.

Any such HTML pushed by designers would rejected in the build step.

**Comment by inikulin** [comment]
It can be covered by #180 then. There will be `validate` method which could be used for such checks.
