### ISSUE TITLE
implements default values

### ISSUE THREAD

**Issue by adrienboulle** [inikulin/parse5#194]
Hello!
I'm wondering if it would be possible to add default property values per element.
For instance: 
`hidden: false` for any element (not the attribut but the element node property)

My use case is with angular platform-browser (Universal), the element object we have access to during the server side rendering is an object provided by parse5 and the object do not behave exactly like an `HTMLElement` regarding the properties.

for instance `document.createElement('div').hidden === false` in the browser

Is there a reason why it is not implemented?
Would you like it to be?

**Comment by inikulin** [comment]
@adrienboulle Element IDL definitions are handled in the DOM and the goal of this project is just to provide HTML AST. For a full featured DOM please refer to the [jsdom](https://github.com/tmpvar/jsdom) project.
