### ISSUE TITLE
Empty document

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#195]
What are the situations in which parse5 would produce this with the streaming API?:
```js
{ nodeName: '#document', mode: 'no-quirks', childNodes: [] }
```

Even an empty document at least produces html/head/body elements in my test suite. I'm getting the above with manual testing with a remote server.

**Comment by inikulin** [comment]
parse5 produces such AST if  `write` or `end` was never called on stream. Basically, if stream is in initial state and haven't received any data yet.

**Comment by stevenvachon** [comment]
Hmm, "never called"? Am I supposed to wait for an event before sending the stream to parse5?

**Comment by inikulin** [comment]
Interesting, seems like node stream doesn't call `_write` on `end` without content. Well, that's a bug, as a fix we can write empty string to stream on construction. Care to issue a PR?

**Comment by stevenvachon** [comment]
It might not be a bug. But you still may want to take some sort of action on this. I was accidentally using [bhttp](https://npmjs.com/bhttp)'s `discardResponse` option for non-HEAD requests; which [pipes to `/dev/null`](https://github.com/joepie91/node-bhttp/blob/master/lib/bhttp.js#L496-L498). Do you still want to handle this with an empty string for consistent output, or is this a situation where the developer fucked up and deserves their fate?

**Comment by inikulin** [comment]
It's a bug. We give erroneous AST on empty string input (which is still a valid input)

**Comment by stevenvachon** [comment]
I have tests with empty string input that produce ASTs with html/head/body elements.

**Comment by inikulin** [comment]
Try
```js
const parser = new parse5.ParserStream(options)
  .once("finish", () => resolve(parser.document));

parser.end();
```

**Comment by stevenvachon** [comment]
That's different than empty string input, though.

**Comment by inikulin** [comment]
@stevenvachon That's pretty much the same.

**Comment by stevenvachon** [comment]
Which file do you want the test in?

**Comment by stevenvachon** [comment]
I just noticed that my empty string tests were using `parse5.parse()` and not `ParserStream`.
