### ISSUE TITLE
Remove menuitem special-casing

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#204]
We ended up removing it from the spec a while back: https://github.com/whatwg/html/pull/2319

But it looks like there is still code here for it, based on a brief skim.

**Comment by inikulin** [comment]
Yeah, it was already removed in the Parse Error WG fork. It will be merged once we accomplish tree construction errors. Is it hits you in jsdom at the moment somehow and you need a quick fix? Or you can wait till Parse Error WG fork will be merged into upstream?

**Comment by domenic** [comment]
No, no rush, I was just reminded in https://github.com/whatwg/html/issues/2730#issuecomment-311779740 that we never filed a parse5 bug when removing it, and doing so is a good idea.

**Comment by inikulin** [comment]
Great then. Thanks for the report!

**Comment by inikulin** [comment]
I'm actually going to use upstream html5lib tests for daily CI builds in the future, so once something will change in the spec and, thus, hopefully, in tests we will get notifications about it automatically.

**Comment by inikulin** [comment]
Changes from parse error working group's fork has been recently merged, so closing this one.
