### ISSUE TITLE
this.html.charCodeAt is not a function at Preprocessor.advance 

### ISSUE THREAD

**Issue by mohitkadelongraph** [inikulin/parse5#208]
My project is built in Angular 4 with Universal(Server Side Rendering). When I load website on browser I am getting below error in server terminal/console.

> ERROR TypeError: this.html.charCodeAt is not a function at Preprocessor.advance (/home/user/node/project/dist/server.js:152260:24) at Tokenizer._consume (/home/user/node/project/dist/server.js:45694:30) at Tokenizer.getNextToken (/home/user/node/project/dist/server.js:45652:23) at Parser._runParsingLoop (/home/user/node/project/dist/server.js:102429:36) at Parser.parseFragment (/home/user/node/project/dist/server.js:102384:10) at Object.parseFragment (/home/user/node/project/dist/server.js:55136:19) at Parse5DomAdapter.setInnerHTML (/home/user/node/project/dist/server.js:53609:49) at Parse5DomAdapter.setProperty (/home/user/node/project/dist/server.js:53250:18) at EmulatedEncapsulationServerRenderer2.DefaultServerRenderer2.setProperty (/home/user/node/project/dist/server.js:54766:94) at setElementProperty (/home/user/node/project/dist/server.js:9982:19)

I have also posted this issue on [stackoverflow](https://stackoverflow.com/questions/45459624/angular-4-universal-this-html-charcodeat-is-not-a-function)

OS: Ubuntu 16.04
NodeJS: v6.9.2
npm: 3.10.9

**Comment by inikulin** [comment]
This issue can occurs only if you feed non-string to parse5 to parse. I believe this should be issued to Angular repo.
