### ISSUE TITLE
Q: What is the adoptAttributes method from the TreeAdapter interface used for.

### ISSUE THREAD

**Issue by jannesiera** [inikulin/parse5#209]
Hello,

I am modifying the standard TreeAdapter to provide a slightly customized output format as an intermediary step to compile a templating language mixed with html.

Since I would like to change the attribute values from strings to an array with custom nodes, I'm making some changes in the createElement method. However, there is also the adoptAttributes method which doesn't seem to get called.

I was wondering if someone could tell me in which cases the adoptAttributes method gets called so I can be aware of what kind of bugs I might be introducing.

Greetings

**Comment by inikulin** [comment]
Hi,

It's used to copy attributes from duplicate `<html>` and `<body>` tags to already existing elements. E.g.: https://github.com/inikulin/parse5/blob/fee401878d866ab87fbc79a4dc5f4f58e4b699c5/lib/parser/index.js#L1232
