### ISSUE TITLE
Browser build without stream interface

### ISSUE THREAD

**Issue by dantman** [inikulin/parse5#213]
According to #156, using parse5 in the browser with browserify/webpack is fine. However `parse_stream.js` causes problems bundling in some environments because `stream` is a node.js package. And hacks like installing [stream](https://www.npmjs.com/package/stream) don't work because that ancient hack doesn't export `Writable`.

Non-node environments don't have a use for streams anyways, so it would probably be best if `parse5` used the `"browser"` field in `package.json` to exclude stream related parts of parse5 from the browser bundled version.

**Comment by inikulin** [comment]
Hmm, creating dedicated builds for browser means that we need to setup dedicated testing browser environment and updating docs about API available in browsers. Unfortunately, I don't have time to invest into these changes. And can't it be fixed on bundler's side with some basic mocking?

**Comment by dantman** [comment]
Mocking the modern streams used by parse5 is non-trivial, the code involved has ballooned since that `stream` package hack was created. You'd end up adding [258kb](https://github.com/juliangruber/stream/issues/2#issuecomment-27626072) of code to mock something that is not used or in any way useful in the browser solely to stop `parse5` from generating an error in a module that isn't used.

Packgers (webpack and browserify) just expect packages supporting node and browser to use the "browser" field to replace any modules that don't work in the browser with something else.

The change I'm describing is a relatively small change to work like how [knex](https://github.com/tgriesser/knex) does it.

A `"browser"` field in `package.json` pointing the modules for the stream interface to a `noop.js` module instead and a conditionals elsewhere to make sure the other code is ok with those modules' classes not being available.

**Comment by inikulin** [comment]
We still need tests for that and documentation update.

**Comment by inikulin** [comment]
BTW, PRs with tests and updated docs are welcome.

**Comment by RReverser** [comment]
> or in any way useful in the browser

I wouldn't say it's useless - `fetch` allows you to get a streaming response, which, in turn, can be used with parse5. Especially useful if you want to parse HTML on the fly in Service Worker or something.

**Comment by dantman** [comment]
@RReverser Ok, I suppose a small subset of users might have a use for it. I suppose it might be possible to get streams working in browser if `parse5` switched to [`readable-stream`](https://www.npmjs.com/package/readable-stream).

I still don't think bundling the huge pile of code you need for a streams implementation and all the unused polyfills it depends on for the browser when it's not used (which will be most cases) is a good idea.

Perhaps that could be solved simply by adding a sub module like `lite.js` which you can require by `require('parse5/lite')` (give it a better name if you want) that just doesn't include the streaming interfaces (then those who don't want the streaming code can just require that instead).

Then again, my real-world problem is that the next version of `cheerio` is starting to use `parse5`, and I can't control how `cheerio` imports `parse5` so having a `parse5/lite` module without the streams may not actually work.

**Comment by RReverser** [comment]
@dantman Agree it might make sense, but then any bundler allows you to configure blacklists of modules - does adding "stream" to ignored list not cover your usecase?

**Comment by dantman** [comment]
@RReverser `parse5` actually uses the modules, so blacklisting things will just result in runtime errors instead. Also, sadly I'm in the one environment where you have very little control over the bundler (React Native).

**Comment by RReverser** [comment]
@dantman 

I see... Regarding 

> which you can require by require('parse5/lite')

suggestion - would using `require('parse5/lib/parser')` work for your use case? That's what we did in ASTExplorer and it worked just fine. Although if React Native's bundler doesn't let you override modules, that probably won't help as you said.

**Comment by dantman** [comment]
@RReverser I'm using `cheerio`. Even if I could rewrite modules easily, rewriting `parse5` to `parse5/lib/parser` wouldn't work since the two modules do not output the same structure (a single class vs a module of classes/functions). And I can't reasonably suggest cheerio should require `parse5/lib/parser` since then a publicly released package would be depending on the `/lib/` structure of another package. But I could conceivably convince `cheerio` to import a `parse5/lite` version that leaves out the stream interface, since from what I can tell `cheerio` does not use the streaming interfaces.

**Comment by RReverser** [comment]
> since the two modules do not output the same structure (a single class vs a module of classes/functions)

In webpack etc. you can override to anything including local module, in which case you can reflect original structure with no issues without changes upstream. Although if you could do that, you could as well replace `stream` with almost empty shim and it would work in just the same way.

**Comment by inikulin** [comment]
@dantman please take a look at #235
