### ISSUE TITLE
Missing attributes in head when not firstChild

### ISSUE THREAD

**Issue by afiestas** [inikulin/parse5#215]
```
const parse5 = require('parse5');

var html = `<!DOCTYPE html>
    <html>
        <script><script>
        <head foo="bar">
        </head>
        <body>Hi there!</body>
    </html>`;
const document = parse5.parse(html);

console.log(document.childNodes[1].childNodes[0].attrs);
```

The output should be an array with foo=bar, it is empty though.

If the script element is removed from the html, everything works as expected.

**Comment by inikulin** [comment]
@afiestas If you insert `<script>` element in `<html>` tag before `<head>` element the parser will implicitly create `<head>` element and insert `<script>` element into it. Therefore, `<head>` in your markup is parsed within already existing `<head>` and, thus, completely ignored.

**Comment by afiestas** [comment]
Then, would it make sense to merge the first head tag that is parsed?  Otherwise Information will be missed.

**Comment by RReverser** [comment]
@afiestas It wouldn't be per spec. I'd suggest checking how your HTML is handled in a browser.

**Comment by inikulin** [comment]
@afiestas 
> Then, would it make sense to merge the first head tag that is parsed

No, this is a per-specification.

> Otherwise Information will be missed.

Well, you'll always have some trade-offs if you have non-conforming markup.
