### ISSUE TITLE
While serializing the processing instructions also gets output as comment nodes

### ISSUE THREAD

**Issue by riteshksriv** [inikulin/parse5#217]
Shouldn't we check if the comment node is actually a processing instruction or comment before appending !-- in the output stream ? For that we will need to check if the node is comment or processing instruction.

https://github.com/inikulin/parse5/blob/8d38fda7e45a28684980ba5b67ca3fa3fbf976da/lib/serializer/index.js#L155

**Comment by inikulin** [comment]
Hi, there is no such thing as a processing instruction in HTML syntax.

**Comment by riteshksriv** [comment]
While serializing the xml declaration in xhtml documents also gets converted as comments. Including the xml declaration may not be the best practice but it is allowed in HTML5 and extensively used in legacy documents.

**Comment by inikulin** [comment]
> Including the xml declaration may not be the best practice but it is allowed in HTML5

It is not.
