### ISSUE TITLE
Should @types/node be a devDependency instead of dependency?

### ISSUE THREAD

**Issue by shepmaster** [inikulin/parse5#220]
It seems strange that I need to include this, even when I'm not using TypeScript. I don't really understand all the parts in motion here, so feel free to close with prejudice 😈 .

**Comment by domenic** [comment]
+1, it would be nice to omit this in jsdom.

**Comment by inikulin** [comment]
It's may be debatable, but TS folks recommend to include type definitions as production dependencies for libraries: https://github.com/Microsoft/types-publisher/issues/81 Considering that `@type/node` doesn't have any dependencies itself and it's just a few hundred lines of code I myself struggle to understand how it can be a problem as well.

**Comment by RReverser** [comment]
As far as I remember, devDependencies are not installed together with package unless you pass some special flag, as they are intended to be used only by maintainers. That way, required types would be inccessible to end users, effectively rendering them useless.

**Comment by inikulin** [comment]
@RReverser I was thinking about peer dependency, but it feels like it will introduce a lot of unnecessary hustle for users.

**Comment by inikulin** [comment]
OK, at this point I'm totally convinced that we should keep it as a dependency, so closing.

**Comment by huntharo** [comment]
So what do we have here?

Another open source developer who picks a technology they don't like (TypeScript in this case) and trying to read thin documentation as "proof" that they should actively do something useless to them that actively harms users of that technology.

Thanks @inikulin 

This project is worthless and should be forked.

**Comment by inikulin** [comment]
@shepmaster @domenic Please, take a look at #235
