### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by hansl** [inikulin/parse5#223]
Disclaimer: I read #116 and #133.

Hello `parse5`,

I'm building a multi-language refactoring library and one of my goal was to support Angular2 templates. Those templates follow the HTML spec, except for one exception (and we can debate separately whether the spec allows for it or not); tags and attributes names are case sensitive and preserving. I wanted to use `parse5` because it's a great library with proper testing and a complete AST with location info. The only problem is that it doesn't preserve case.

After diving in, I noticed that it would be relatively simple to add case preservation to the parse5 tokenizer. Tests showed that it would be sufficient for my use-case. Such a change should be gated behind an option, which defaults to the current behaviour (e.g. `options.preserveCase`).

**I'm offering to do all the work for this feature, including test coverage.** I just want to make sure you are open to a PR before starting work. I also want to have a general discussion here, under this context.

I understand that this would mean that parse5 becomes more than a strict HTML parsing library. I personally think this is a plus, but that is definitely up to discussion.

Cheers, Hans

**Comment by inikulin** [comment]
Hi, thank you for the proposal, but we won't implement or accept PRs for any features that violate the spec or provide various "relaxed" parsing modes. However, feel free to fork parse5 to implement functionality required for you project.
