### ISSUE TITLE
Setting `endTag` location info with `Object.create` hides it from inspecting

### ISSUE THREAD

**Issue by wooorm** [inikulin/parse5#224]
I propose `endTag` to be set as a normal, enumerable object, so it’s visible for people trying to inspect nodes. But maybe there’s some smart reasoning behind this that I haven’t thought about.

#### Breakdown

Break down of how the props are set:

1. `__location` is [set](https://github.com/inikulin/parse5/blob/d9c08818bfad8ff1c9714e00f37cbef44e5226a2/lib/extensions/location_info/parser_mixin.js#L30) with `Object.create()` from the `startTag` as “prototypal defaults”.
2. `__location.startTag` is [set](https://github.com/inikulin/parse5/blob/d9c08818bfad8ff1c9714e00f37cbef44e5226a2/lib/extensions/location_info/parser_mixin.js#L31) as a normal object, thus making the object visible while inspecting
3. `__location.endTag` is [set](https://github.com/inikulin/parse5/blob/d9c08818bfad8ff1c9714e00f37cbef44e5226a2/lib/extensions/location_info/parser_mixin.js#L50) with `Object.create()` from the closing tag’s location, as “prototypal defaults”, making them invisible while inspecting.

#### Example

For example, say we have this `example.js`

```js
var inspect = require('util').inspect;
var parse5 = require('parse5');

var x = parse5.parseFragment('<h1>My First Heading</h1>', {locationInfo: true});

console.log(inspect(x.childNodes[0], {depth: null, showHidden: true}));

console.log(x.childNodes[0].__location.endTag.__proto__);
```

Now, running `node example` (with parse5 installed), this yields:

```js
{ nodeName: 'h1',
  tagName: 'h1',
  attrs: [ [length]: 0 ],
  namespaceURI: 'http://www.w3.org/1999/xhtml',
  childNodes: 
   [ { nodeName: '#text',
       value: 'My First Heading',
       parentNode: [Circular],
       __location: { line: 1, col: 5, startOffset: 4, endOffset: 20 } },
     [length]: 1 ],
  parentNode: 
   { nodeName: '#document-fragment',
     childNodes: [ [Circular], [length]: 1 ] },
  __location: 
   { startTag: { line: 1, col: 1, startOffset: 0, endOffset: 4 },
     endTag: {},
     endOffset: 25 } }
{ line: 1, col: 21, startOffset: 20, endOffset: 25 }
```

Note that the headings `endTag` is invisible in the first `console.log`, because it’s set as a prototype, which is illustrated by the second `console.log`.

**Comment by inikulin** [comment]
Hi @wooorm, thank you for the report. It was introduced (seems like inconsistently) due to https://github.com/inikulin/parse5/issues/119. Maybe it shouldn't be a problem to use regular objects for location, idk. PRs and ideas are welcome.

**Comment by wooorm** [comment]
Hi! 👋

I dunno, I personally prefer plain JSON objects (we’ve been using those for decades), but those with `null` as a prototype (`Object.create(null)`) are fine as well.

Is there a reason to have `startTag` as the prototype of a `__location`? One effect is that you can do `node.__location.line` instead of `node.__location.startTag.line`, but is that intentional?
