### ISSUE TITLE
Is "@types/node" really a dependency?

### ISSUE THREAD

**Issue by alexandrudima** [inikulin/parse5#225]
I've been looking at the shipped version of `parse5` and I cannot find any usage of `@types/node` at runtime. 

It is not required in any way. 

I therefore believe `@types/node` should not be a dependency in `package.json`.

**Comment by inikulin** [comment]
Hi, yes: https://github.com/inikulin/parse5/issues/220

**Comment by inikulin** [comment]
@alexandrudima Please, take a look at #235
