### ISSUE TITLE
Location Information not available

### ISSUE THREAD

**Issue by amcdnl** [inikulin/parse5#229]
I've got the following code that should find the head tag and return me the location.

```
export function getHeadTag(src) {
  const document = parse5.parse(src) as parse5.AST.Default.Document;
  let head;
  const visit = (nodes: parse5.AST.Default.Node[]) => {
    nodes.forEach(node => {
    console.log('!!!!!', (<any>node).__location)
    const element = <parse5.AST.Default.Element>node;
      if (element.tagName === 'head') {
        head = element;
      }

      if (element.childNodes) {
        visit(element.childNodes);
      }
    })
  };

  visit(document.childNodes);

  return {
    position: head.__location.endOffset
  };
}
```

The `__location` is not showing up for ANY tags. If I look in the AST Explorer, I see them being shown correctly - http://astexplorer.net/#/gist/11184b3a5c2cac8026f93a37d5a06cf0/9f9be4820b89ec8f7a526dccb6503aa764ddeb7a ... ( This is the file I'm trying to parse too. ).

Any ideas what could be wrong here? Looks like it should be working.

**Comment by fictitious** [comment]
Location information is not available by default, you have to set [locationInfo in ParseOptions](http://inikulin.github.io/parse5/#-i-need-a-source-file-location-information-for-the-parsed-document-):

    parse5.parse(src, {locationInfo: true});

**Comment by amcdnl** [comment]
Thanks so much!
