### ISSUE TITLE
Add a serialization mode that mimics outerHTML

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#230]
That is, it should include the node itself.

Currently in jsdom we have to create a fake parent node with only one child node, the node we want to serialize, and then ask parse5 to serialize that.

**Comment by joeldenning** [comment]
I've implemented this in #347. For anyone looking for a workaround, here's how you can serialize outerHTML without my new code:

```js
import Serializer from 'parse5/lib/serializer/index.js'

function serializeOuterHTML() {
  const serializer = new Serializer()
  serializer._serializeElement(node)
  return serializer.html
}
```

**Comment by joeldenning** [comment]
@fb55 following up from https://github.com/inikulin/parse5/pull/347#issuecomment-1006932005, what would you prefer the name of the new method be? Maybe `serializeOuter`?

**Comment by fb55** [comment]
`serializeOuter` works! We are about to land a major refactor (#362). Once that is done, I look forward to addressing this issue.
