### ISSUE TITLE
No end tag returned when fragment contains self-closing iframe

### ISSUE THREAD

**Issue by rbrtmrtn** [inikulin/parse5#233]
Hello! I'm trying to use `parseFragment` to parse some HTML-ish code that looks like this:

```
<template>
  <div>
    <iframe />
  </div>
</template>
```

(This is a [Vue.js single-file component](https://vuejs.org/v2/guide/single-file-components.html), not straight-up HTML, hence the self-closing node syntax.)

This is the call I make to `parse5`:

    const fragment = parse5.parseFragment(code, { locationInfo: true });

When I inspect the result and try to get the `endTag` for the `<template>` node, it's missing from the `__location` object. This is what `__location` looks like:

```
{ startTag: { line: 1, col: 1, startOffset: 0, endOffset: 10 },
     endOffset: 55 } }
```

Interestingly, if I change the `<iframe />` to a `<button />` (or any other more common HTML element), the `endTag` reappears. Also, if I give the `<iframe>` a closing `</iframe>` tag, it works as well. I have a Runkit comparing all three cases here:

https://runkit.com/rbrtmrtn/5a506a54ba85940012089faa

Does anyone know why a self-closing `<iframe />` would cause this sort of behavior in `parseFragment`? Any insights would be much appreciated.

**Comment by fictitious** [comment]
It's explained here https://stackoverflow.com/questions/27545757/why-is-a-self-closing-iframe-tag-preventing-further-dom-elements-to-be-displayed , see also https://www.linkedin.com/pulse/self-closing-void-elements-vs-iframe-john-correll on why iframe is not a void tag. 

The end result is that spec-compliant HTML parser must ignore the slash in `<iframe />` , so closing tags for `<div>` and `<template>` are still inside the `<iframe>` and don't really close anything.

**Comment by inikulin** [comment]
@fictitious Thank you for handling this one! Closing since comprehensive answer was given above.
