### ISSUE TITLE
Using parse5 in react native app

### ISSUE THREAD

**Issue by makma** [inikulin/parse5#234]
I've tried to use parse5 in react native app and I've failed in building JS bundle because `parser/parser_stream.js `  attempted to import the Node standard library module "stream". More info about why it is not possible [here](https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo).

Whole error:

> The package at ".c:\\Users\\martinm\\Documents\\React Native\\RealEsta
te\\node_modules\\parse5\\lib\\parser\\parser_stream.js" attempted to import the
 Node standard library module "stream". It failed because React Native does not
include the Node standard library. Read more at https://docs.expo.io/versions/la
test/introduction/faq.html#can-i-use-nodejs-packages-with-expo

My question: Is there any workaround for parse5 + react native app?  
Thanks

**Comment by fictitious** [comment]
The workaround is to leave out parse5 parts that use streams when bundling.

How exactly to do that depends on which bundler are you using, and which parts of parse5 API you want to use.

For webpack, I think it's possible to create parse5 bundle by creating customized entry point file which is identical to https://github.com/inikulin/parse5/blob/master/lib/index.js , except with last 4 lines removed (the lines that  import stream-depending parts).

**Comment by makma** [comment]
Thanks for your response and suggestions but I'm not sure this works for me - my original question is little misleading - I'm trying to use package which depends on parse5.

**Comment by fictitious** [comment]
That error message at the top seems to be produced by some kind of a tool. Is that tool configurable, and does it allow for substitution of dependencies, that is, does it allow to use your own, local version of parse5 instead of the one published on npm?

**Comment by inikulin** [comment]
@makma Closing this in favour of #235

**Comment by makma** [comment]
Thank you!
