### ISSUE TITLE
Need more insight into the stack of open elements

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#237]
I've tried to come up with some alternative but it seems that to implement the [style element](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element) properly, we need some notification: it requires action when

> - The element is popped off the stack of open elements of an HTML parser or XML parser.
>
> - The element is not on the stack of open elements of an HTML parser or XML parser, and it becomes connected or disconnected.

Do you have any ideas on how we could implement this in a parse5 adapter? It's currently causing a pretty bad regression in jsdom ever since we switched from the htmlparser2 adapter, with bad consequences for our consumers.

**Comment by inikulin** [comment]
Hi @domenic, 

> we need some notification: it requires action when

Can you point me to the parts of the spec that describe these notifications? It will help me to come up with proper API for that.

**Comment by domenic** [comment]
See the link for "the style element" in the OP, where the bullet points I quoted are found.

Based on https://github.com/jsdom/jsdom/pull/2132, an API that would work for our purposes would be two adapter functions, each taking an element, which are called when the element is pushed and when it is popped, respectively.
