### ISSUE TITLE
Getting 'Critical dependency' warning in Angular project

### ISSUE THREAD

**Issue by Enngage** [inikulin/parse5#240]
Hi there,

Importing your library using `import * as parse5 from 'parse5';` will cause following warning when used in default Angular CLI project:

```
WARNING in ./node_modules/parse5/lib/index.js
55:23-49 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (c:\dev\Parse5DependencyExpr
essionAngular\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (c:\dev\Parse5DependencyExp
ressionAngular\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (c:\dev\Parse5DependencyExpressionAngular\node_modules
\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (c:\dev\Parse5DependencyExpressionAngular\node_m
odules\webpack\lib\Compiler.js:502:17)
    at c:\dev\Parse5DependencyExpressionAngular\node_modules\tapable\lib\Tapable
.js:289:11
    at _addModuleChain (c:\dev\Parse5DependencyExpressionAngular\node_modules\we
bpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (c:\dev\Parse5DependencyExpressionAngular\n
ode_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./node_modules/parse5/lib/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Compiled with warnings.
```

I've reproduced this on the most basic Angular project in [this repo.](https://github.com/Enngage/Parse5DependencyExpressionAngular)

As you can see in my [app.component,](https://github.com/Enngage/Parse5DependencyExpressionAngular/blob/master/src/app/app.component.ts) all I'm doing is just importing the library.

Thanks for your support!

**Comment by fictitious** [comment]
Yes this library has switched to [dynamic require ](https://github.com/inikulin/parse5/blob/master/lib/index.js#L55) for loading node-dependent parts [on demand](http://inikulin.github.io/parse5/#4-0-0), instead of unconditionally loading modules that require streams API.

Yes this causes webpack warnings. Previously (before 4.0) it caused webpack to bundle shim code for node streams which was often unused and unnecessary. If these warnings are critical for you, you can use previous release until this is sorted out. (There are no functional changes in 4.0 as yet compared to 3.0, apart from that dynamic loading).

Yes there is a way to tell webpack about this lazy loading and stop issuing warnings, but looks like it's webpack-specific and will break bundling for other platforms like React Native.

Any ideas?

**Comment by Enngage** [comment]
I'm not sure what would be the best course of actions for me though... I have a client library that needs to be run in both in and outside node.js environment (so I believe I need to keep using 4.0 for that), but I'm a bit worried of possible side effects of the dynamic include warning. Currently our clients also see the warning and it seems unprofessional and just hiding it seems 'wrong'.

**Comment by inikulin** [comment]
Unfortunately I can't come up with better workaround for this kind of issues at the moment. Splitting into separate packages should is the only solution we've came up with so far. Tracking ticket for this work is https://github.com/inikulin/parse5/issues/235, so if you wouldn't mind I'll close this one as duplicate.

**Comment by Enngage** [comment]
Thank you for the response! Sure, I understand. I do have a small question if I may since you way more familiar on the topic then I am. I've managed to fix (or hide?) the warning by using following webpack plugin:

```
new webpack.ContextReplacementPlugin(
/(.+)?parse5(\\|\/)lib(\\|\/)(.+)?/,
path.join(__dirname, 'src'), 
{} 
)
```

Do you think this will have any side effects in node.js / browser environments or certain builds (AOT..)? From what I've seen so far this seems to work ok, but one never knows.

**Comment by inikulin** [comment]
@Enngage This should be fine, unless you use start using streaming APIs.

**Comment by Enngage** [comment]
Okey, thanks a lot!
