### ISSUE TITLE
SAXParser resolves html entities in attributes

### ISSUE THREAD

**Issue by jescalan** [inikulin/parse5#241]
Hi there!

A reshape user [opened an issue](https://github.com/reshape/reshape/issues/61) reporting this one, and I was able to trace the root of it back to parse5's SAXParser, which we are using in the project. Basically, if you have an html element with an entity in the attributes, as such:

```
<div foo="&quot;test&quot;"></div>
```

... the parser resolves the entities when parsing the attribute automatically, so it turns out like this:

```
<div foo=""test""></div>
```

This specific example makes it fairly clear why this is not always desirable.

I did a bit of extra hunting to see if I could get closer to the source of the issue, but I didn't manage to get there - the codebase is quite difficult to navigate. The furthest I got was [here](https://github.com/inikulin/parse5/blob/master/lib/tokenizer/preprocessor.js#L136), where I found the original source, including the html entity, being fully represented in the resulting code points. [Shortly after this](https://github.com/inikulin/parse5/blob/master/lib/tokenizer/index.js#L232), logging out the code points showed them as being reduced to `&q`, and several other characters being garbled. At this point, I lost track of how data flows through, as it seemed like all the tokens had been fully formed at this point despite just getting to the point where we had a series of code points. Any push in the right direction surely would be helpful!

**Comment by fictitious** [comment]
The source seems to be in the [CHARACTER_REFERENCE_IN_ATTRIBUTE_VALUE_STATE](https://github.com/inikulin/parse5/blob/master/lib/tokenizer/index.js#L1540) handler function. The switch to this state happens upon seeing `&` in the attribute value [here](https://github.com/inikulin/parse5/blob/master/lib/tokenizer/index.js#L1469), [here](https://github.com/inikulin/parse5/blob/master/lib/tokenizer/index.js#L1492) and [here](https://github.com/inikulin/parse5/blob/master/lib/tokenizer/index.js#L1515).

I think you could try to override handlers for all three attribute value states - `ATTRIBUTE_VALUE_DOUBLE_QUOTED_STATE`, `ATTRIBUTE_VALUE_SINGLE_QUOTED_STATE` and `ATTRIBUTE_VALUE_UNQUOTED_STATE` and remove the special handling for ampersand.

**Comment by RReverser** [comment]
> This specific example makes it fairly clear why this is not always desirable.

It looks like the problem here is serialized representation. Parser itself does what it's supposed to do as per spec.

**Comment by domenic** [comment]
FWIW the serialization algorithm that should be followed is https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments . Are you using parse5 to produce the bad serialization seen in the OP, or some other tool?

**Comment by inikulin** [comment]
Closing for now, as issue seems like to be unrelated to parse5 itself. Will be happy to reopen when more info emerge.

**Comment by jescalan** [comment]
Oh sorry for the late update, but yes this is being reproduced purely with parse5, and without other tools.

**Comment by inikulin** [comment]
@jescalan But as far as I understand you have custom serialiser, right? As mentioned above, parser doing the correct thing resolving entities in attributes as a part of parsing process. It's a burden of serialiser to take care of correct escaping of quotes in attributes. Links provided in https://github.com/inikulin/parse5/issues/241#issuecomment-364929967 is a good starting point.

**Comment by jescalan** [comment]
Ok sorry, perhaps I didn't fully understand before. To be clear, you're saying that it is the intended behavior that the parser resolves html entities within attributes, and it's the serializer's job to re-encode them?

**Comment by inikulin** [comment]
Correct

**Comment by jescalan** [comment]
Got it. I mean, to be honest this doesn't seems like a reasonable behavior to me, but I assume those who wrote the spec are infinitely more knowledgable and had a good reason for it.
