### ISSUE TITLE
about "input" label, the parse result is not include end tag? how to solve it 

### ISSUE THREAD

**Issue by suuuuuuuuperman** [inikulin/parse5#244]

**Comment by inikulin** [comment]
Hi, unfortunately it's unclear from the issue what the problem is. Will be happy to reopen once you provide more information.

**Comment by suuuuuuuuperman** [comment]
I mean when i use parse5 to parse "input tag" like "<input class='inputtag' />", it will lose it end tag "/>" and just become "input tag" like "<input class='inputtag' >".  Is there some good way to help me to solve it?

**Comment by inikulin** [comment]
@suuuuuuuuperman There is no such thing as a self-closing tag in HTML (though they exist in SVG). Therefore, parser just ignores `/` in the end of the tag. `input` is a void element in HTML which means that it doesn't require end tag, so semantically markup is equivalent in both cases.
