### ISSUE TITLE
IE11 does not support destructuring assignment

### ISSUE THREAD

**Issue by kurtinatlanta** [inikulin/parse5#252]
lib/tree-adapters/default.js line 3:
```
const { DOCUMENT_MODE } = require('../common/html');
```

This line breaks `parse5` when used in the browser with IE11 as that browser does not support destructuring assignment.

I don't know if it's used elsewhere or if you support running in the client side on IE11.

**Comment by RReverser** [comment]
How are you currently using it? You should transpile parse5 with Babel or some other transpiler if targetting IE11. Assuming you're bundling it with Webpack or similar and already use a transpiler, it should be a small change to the config.

**Comment by kurtinatlanta** [comment]
We do npm install, then, since we're using TypeScript, we import what we need and go.

We are using Webpack.

But we don't expect to have to transpile libraries in node_modules that we get via npm install. We expect they have already been transpiled and are ready for use directly. If that's not the case here, then we'll either have to stick with 4.0.0 or fork and build this code on our own.

**Comment by kurtinatlanta** [comment]
Unfortunately, we can't dump IE11 (which will never be fully ES6) yet. If that's not something you care about, that's fine. I missed that 'limitation' when we upgraded to 5.0.0.
