### ISSUE TITLE
serialize function remove carriage returns after certain tags

### ISSUE THREAD

**Issue by ericmorand** [inikulin/parse5#253]
Consider the following code:

```js
const parse5 = require('parse5');
const fs = require('fs');

let data = fs.readFileSync('parse5.html');

const document = parse5.parse(data.toString(), {
  locationInfo: true
});

let serialized = parse5.serialize(document);

console.warn(serialized);
```

* parse5.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
```

The result of `parse5.serialize(document)` is:

```html
<!DOCTYPE html><html lang="en"><head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


</body></html>
```

Carriage returns after the DOCTYPE, html and /body tags are lost.

Tested with parse5@3.0.3

**Comment by inikulin** [comment]
Text nodes between these nodes are ignored as per specification. You can observe the same behaviour in browsers: https://jsbin.com/yakuxehebi/edit?html,js,console. If you need to modify HTML with less modifications to the original formatting, then take a look at [parse5-html-rewriting-stream](https://github.com/inikulin/parse5/tree/master/packages/parse5-html-rewriting-stream).

**Comment by ericmorand** [comment]
Aweome! Thank you.
