### ISSUE TITLE
Mismatch between camel-cased and kebab-cased error name

### ISSUE THREAD

**Issue by wooorm** [inikulin/parse5#255]
From what I gather `common/error-codes.js` is a mapping between camelcased properties and dash-cased error codes. However, there’s a mismatch (I think the only one) on [L26-27](https://github.com/inikulin/parse5/blob/4350f6a03dcd57dd9b3d8ba3c962ebf31a5f7f54/packages/parse5/lib/common/error-codes.js#L26) (without and with `s`): 

```js
    missingWhitespaceBetweenDoctypePublicAndSytemIdentifier:
        'missing-whitespace-between-doctype-public-and-system-identifiers',
```

Is this a bug, or a feature? 😉

**Comment by wooorm** [comment]
Oh, also `Sytem` vs `-system-`!

**Comment by inikulin** [comment]
Yeah, it's a typo in the variable name. PR with a fix is welcome?

**Comment by wooorm** [comment]
Sure thing! Would you prefer with S (as in the [html spec](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-missing-whitespace-between-doctype-public-and-system-identifiers))
