### ISSUE TITLE
tree-construction data missing in tests

### ISSUE THREAD

**Issue by mlynch** [inikulin/parse5#259]
Hello, I'm trying to run the tests locally from the repo and it seems the `tree-construction` fixtures aren't in the repo. I tried some of the other scripts in `package.json` but couldn't seem to generate it. Is there a way I'm missing?

<img width="837" alt="screenshot 2018-06-11 11 45 58" src="https://user-images.githubusercontent.com/11214/41245218-0da119dc-6d6d-11e8-9dd8-41e36423e1e5.png">

**Comment by inikulin** [comment]
Test data is in Git submodule. Just run:
```sh
git submodule update --init --recursive
```

**Comment by mlynch** [comment]
Thanks! Doing some tweaking of the parser for Angular templates and figured this was just not documented. 🍻
