### ISSUE TITLE
Serialization is changing a lot of things

### ISSUE THREAD

**Issue by antoineVgs** [inikulin/parse5#260]
Hi,

I'm parsing  an html angular file in order to apply modifications : renamings, parameters changes, etc.

It works, but when re-serializing to save the modifcations, a lot of other unexpected changes are applied.
Maj are disappearing in directive, = "" are added, html and body tag are added.
e.g.

    <a myDirective href="url">

is becomming 

    <a mydirective="" href="url>

Is it possible to prevent from modifying anything ?

**Comment by RReverser** [comment]
This is working as intended (per spec). Please check previously closed issues about serialisation, questions like this have been answered many times.
