### ISSUE TITLE
Can't detect original text

### ISSUE THREAD

**Issue by evilebottnawi** [inikulin/parse5#261]
Input:
```html
<p>I will display &euro;</p>
<p>I will display &#8364;</p>
<p>I will display &#x20AC;</p>
```

Output: `<p>I will display €</p>`

Based on https://github.com/prettier/prettier/pull/4753

**Comment by RReverser** [comment]
The issue description doesn't contain any specific question, but this is working as per HTML spec. It's also worth taking a look at some of the previous discussions. https://github.com/inikulin/parse5/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+entities

**Comment by evilebottnawi** [comment]
@RReverser And? What is workaround? How i can solve this?

**Comment by RReverser** [comment]
@evilebottnawi Solve what? As I said, this is working as per HTML spec, which parser strictly follows to have exactly same behaviour as browsers.

**Comment by evilebottnawi** [comment]
@RReverser I'm not suggesting changing parser. Why not provide `rawData` property for text node?

**Comment by domenic** [comment]
Sometimes it seems like people don't really understand what a parser is.

A parser converts raw text into a structured, canonical representation. This is inherently a lossy transformation, by nature of what canonicalization means. There are multiple inputs that all map to the same parsed representation.

For a JavaScript example, `function(a){}` parses the same as `function    ( a) { }` which parses the same as `function (\u{000061}) {    }`. All produce a function expression with a parameter named "a" and an empty body. This is usually represented in a data structure known as an AST.

For a HTML example, `<p>I will display &euro;` parses the same as `<p>I will display &#8364;</p>` which parses the same as `<p    >I will display &#x20AC;</    p>`. All produce a paragraph with the contents "I will display €". This is usually represented in a data structure known as a DOM.

_The whole point_ of a parser is to get rid of these differences in input string format, and produce a single canonical representation of the actual structure that you'll operate on.

If you're interested in the original raw string, you should not be parsing it in the first place. You should be operating on the string.

**Comment by evilebottnawi** [comment]
@domenic 
> Sometimes it seems like people don't really understand what a parser is.
Who?

> This is inherently a lossy transformation, by nature of what canonicalization means.
Disagree. You can parse and lose information and you can parse and don't lose information, it is your choice. First of all, the parser is written for other developers and help them, not create additional barriers.

> The whole point of a parser is to get rid of these differences in input string format, and produce a single canonical representation of the actual structure that you'll operate on.
I do not propose to change anything, just allow people get raw text without manipulation with original source code.

Ideal program often differs from the program from real world. In real world you have difference technologies/libraries/tools/etc stuff and spend most of your time working on that they work well together. And this often requires additional lines of code and I've never seen a problem with it, we're all trying to create something good and help each other.

**Comment by gabrielmaldi** [comment]
I understand Domenic's rationale.

Let me just add what the intended use case for this would be: using the parser in order to format source code; in this scenario, you don't want to modify what the developer wrote.

I get that it may be out of scope, but for example [Roslyn](https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis#user-content-understanding-syntax-trees) provides source code location for each node. This would provide a workaround: read the file again at the given position and retrieve the original text.

**Comment by RReverser** [comment]
> using the parser in order to format source code; in this scenario, you don't want to modify what the developer wrote

Isn't the whole point of autoformatting the code to... well, modify, what developer wrote into a same canonical format?

**Comment by evilebottnawi** [comment]
@RReverser yep, but we don't have no `&euro;`, `&#8364;` or `&#x20AC;` :disappointed: Only euro symbol, we can use same canonical format if we have original source text.

@gabrielmaldi we have original code and location and we can get original text in text node, but I would not like to do such hacks :disappointed:

**Comment by RReverser** [comment]
> Only euro symbol, we can use same canonical format if we have original source text.

I don't understand. If you agree that you want to have a single canonical format as output, why do you still want the original raw text with different entity representation and not the parsed value? Arguably it would be more readable to have euro sign as-is (luckily, UTF-8 is supported everywhere nowadays), but even if not and for whatever reason you want to encode some symbols back to entities, you could do that as well from the parsed text without needing the original raw representation.

**Comment by inikulin** [comment]
@gabrielmaldi parse5 can provide source code location for each node (if it's present in the original markup, there are cases when parser generates nodes implicitly): https://github.com/inikulin/parse5/blob/master/packages/parse5/docs/options/parser-options.md#optional-sourcecodelocationinfo

**Comment by inikulin** [comment]
@evilebottnawi 

> we have original code and location and we can get original text in text node, but I would not like to do such hacks 

I fail to see how's that's a hack, considering that having a node location and a source html you are one step away from having raw representation that you demand:
```js
const raw = html.substring(node.sourceCodeLocation.startOffset, node.sourceCodeLocation.endOffset);
```

**Comment by karlhorky** [comment]
> for whatever reason you want to encode some symbols back to entities, you could do that as well from the parsed text without needing the original raw representation

I think what @evilebottnawi means is that this is not possible with the parsed text, because, for example, for the parsed text of €, the original representation may be either `&euro;`, `&#8364;` or `&#x20AC;`.

This is understandable from the perspective of a code formatter such as Prettier, which does not want to change the non-formatting related code that the user has written.

Not sure if it fits the goals of the `parse5` project though.
