### ISSUE TITLE
v5.0.0, webpack can't minify the library

### ISSUE THREAD

**Issue by kanweiwei** [inikulin/parse5#263]
Because the bundled library use many es6 syntax like `asnyc` `const` `class` , etc,  **webpack** can't minify them. Can you translate them into **es5** syntax by babel ? The best translate them into **es5** syntax with the **es6** `import export` feature by babel and packaged in the  **es** directory, so that i can try the **tree-shaking** of  **webpack**.

**Comment by inikulin** [comment]
This library targets modern node.js versions and browsers. We encourage users to perform transpilation in their setup if they target ancient platforms that don't support ES6 syntax.
