### ISSUE TITLE
Published packages are missing LICENSE text

### ISSUE THREAD

**Issue by kuba-kubula** [inikulin/parse5#275]
Hi @inikulin,

Since `parse5` is a great library and I really enjoy using it for personal projects, it'd be awesome to be able to use also for my company employer projects. But due to LICENSE text being missing in the published package(s) tarballs, it's not possible due to (possible) legal (I know, damn legal!) issues.

MIT basically states that the full text of the License has to be distributed with all the code pieces. Just having `MIT` in `package.json` file is not enough unfortunately :-( 

Never version of `lerna` manages a fix for that issue with missing license-text, issue was https://github.com/lerna/lerna/issues/1213 and fixed was in https://github.com/lerna/lerna/pull/1465 then promoted to lerna's `3.0` release.

Could upgrade of Lerna and republishing all packages be possible, so `legal` can 😴 then?

Thanks a lot for your great work and looking forward for bright future of OSS. 👍

**Comment by tomas-mechura** [comment]
+1

**Comment by johnjbarton** [comment]
Also a problem for us.
