### ISSUE TITLE
Node OOM crash

### ISSUE THREAD

**Issue by gugu** [inikulin/parse5#276]
Today I got this kind of error on parsing of my project.

Unfortunately I don't have HTML available, which caused this error, but usually it happens if there is a long loop without gc() called periodically or `process.nextTick()` called, but second one will require API change as well

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
<--- Last few GCs --->
io[1:0x557682a3f660] 491846829 ms: Mark-sweep 501.2 (525.1) -> 498.9 (529.1) MB, 841.8 / 0.0 ms (+ 0.5 ms in 95 steps since start of marking, biggest step 0.0 ms, w
alltime since start of marking 897 ms) (average mu = 0.132, current mu = 0.061) allocation f[1:0x557682a3f660] 491847590 ms: Mark-sweep 498.9 (529.1) -> 498.9 (529.1) MB, 758.9 / 0.0 ms (+ 0.0 ms in 0 steps since start of marking, big
<--- JS stacktrace --->
==== JS stack trace =========================================
0: ExitFrame [pc: 0x14de9ea041bd]
Security context: 0x11835331e6c9 <JSObject>
1: _runParsingLoop [0x158bac5df269] [/srv/shorturl_api/node_modules/parse5/lib/parser/index.js:~418] [pc=0x14debd185429](this=0x192ba827cbe1 <Parser map = 0x3bfaef786199>,scriptHandler=0x7c1ef402201 <null>)
2: parse [0x158bac5df189] [/srv/shorturl_api/node_modules/parse5/lib/parser/index.js:344] [bytecode=0x32f42d954b11 offset=64](this=0x192ba827cbe1...
```

I'll try to get HTML if it will happen again

**Comment by inikulin** [comment]
You can easily reproduce with any HTML that have extremely long tag name, attribute name or value. We don't have any other choice except for buffering these values even in streaming parser. Although, we can abort parsing and raise error event in such a case, but it's not implemented at the moment. 

The other cause could be a huge HTML file that expands into AST that doesn't fit in the memory (Node.js has quite small heap size by default).
