### ISSUE TITLE
Switch to the latest version of the html5lib test suite

### ISSUE THREAD

**Issue by inikulin** [inikulin/parse5#28]
Apply latest spec changes by the way.

**Comment by inikulin** [comment]
Sources: https://chromium.googlesource.com/chromium/blink/+/master/LayoutTests/html5lib/resources/

**Comment by domenic** [comment]
It would be better to sync with the official html5lib repo, as in some cases Blink might not be fully compliant. @gsnedders is currently looking in to Blink divergences.

**Comment by inikulin** [comment]
Yep, I'm already doing it.

**Comment by inikulin** [comment]
Note: sync Blink changes as well-https://github.com/html5lib/html5lib-tests/pull/67

**Comment by gsnedders** [comment]
Note some of the Blink changes are wrong per spec, and aren't gonna get merged. I'd stick with what's on master.

**Comment by inikulin** [comment]
@gsnedders Thank you for the clarification.
