### ISSUE TITLE
Rewriter API: emitXyz confusing + how to add flexibility

### ISSUE THREAD

**Issue by meisl** [inikulin/parse5#280]
First off, parse5 is great work - big Thank You!

This issue is more of **a request-for-comments** than anything else: I am actually not really asking to *change* the API, but would rather like to hear your thoughts on possible alternatives (which I might then implement myself, be it as a subclass or in a fork).

Please bear with me, as I have to strike out a bit; guess that's inevitable when it comes to API design. The aim is of course to have it small, intuitive, extensible, and finally rather hard to (inadvertently) abuse - **for both, user and implementors** (implementors = those who want to extend it).

---
#### Executive summary ####
*Public methods `emitXYZ` (called from listeners) are misnamed, too numerous and not flexible enough -> alternative paradigm?*

---
#### Status quo ####
While experimenting with subclassing/adapting parse5-html-rewriting-stream to my needs,
I got (and still get) **quite confused by the use of the verb "emit" in method names** for both,
1. EventEmitter-related (implementors' view):
  - `emit(eventName, ...args)` from EventEmitter, to actually call the listeners
  - `_emitToken(eventName, token)` to process token and then call `emit(eventName, ...args)`
2. ReadStream-related (users,' view i.e. called from listeners):
  - `emitRaw(htmlString)`
  - `emitStartTag(startTagToken)`
  - `emitEndTag(endTagToken)`
  - `emitComment(commentToken)`
  - `emitText(textToken)`
  - `emitDoctype(doctypeToken)`

So, 1. is obviously internal while 2. is the public API, which is kind of OK as long as you're *only using* the Rewriter as is. That's because from a listener's point of view, what you do is *output* something to consumers of the stream (if any), and the verb "emit" has indeed this notion. The question is, however: *what* is being put out to the outside world? Here it's tokens, or ultimately strings - NOT events.

I can discern two purposes of those `emitXyz` methods from 2.:
* serialize the argument to a string (trivial case: `emitRaw`)
* *push* (!) the resulting string through to consumers of the ReadStream part of the Rewriter
Note that it's `push` from ReadStream that you have to call in order to make your results available to consumers.

---
#### Problems ####

Generally, all this Stream stuff is already hard enough to wrap your head around, particularly when dealing with Transform streams (* see footnote for a nice illustration of this). Basically, there's two orthogonal aspects:
* ReadStream vs. WriteStream
* implementor vs. user

...which can *both* - unfortunately - be viewed as a producer/consumer question. But they are in fact *independent* (orthogonal), yielding four points of view to choose from. Now, even though here we're really mainly concerned with the ReadStream part:

**Using the verb "emit" for methods to be called from listeners unnecessarily adds to this confusion, namely by not clearly keeping apart events vs. (serialized) tokens "coming out" of the Rewriter**.
Alternative would be something with an "output" notion, like "issue", "push", or even "write". Which exactly needs further discussion. E.g. a *listener* might very well view the Rewriter as a *WritableStream*...

**Having a separate *public* method for each token type is error-prone**. For example:
```javascript
   rewriter.on('startTag', token => rewriter.emitEndTag(token))
```
This minimal example might look stupid, but you know, in practice... Why not just differentiate between raw html vs a token, the latter having been either modified or created completely new within the listener? Dispatch on the token type could as well be done internally.

**As an implementor, I'd like an easy way to - possibly selectively - preprocess tokens before they're emitted to listeners**.
There is indeed `_handleToken` (already in SAXParser, overridden in RewritingStream), but it seems to serve a whole other purpose already (?).
As an example for a use case: reconstruct original attribute names from source, so they're output as is - with or without a listener.
Here, i.e. on the implementor's side, a differentiation by token type might actually be useful: one could *selectively* overrride methods `_handleStartTag`, `_handleText`, etc.
Note: `_handleToken` in SAXParser uses a const `TOKEN_EMISSION_HELPERS`, making it essentially non-extensible (only way out: re-implement _handleToken altogether).

**From both, a user's and an implementor's point of view: there should be more fine-grained control over serialization. Somehow "pluggable".**
For this I don't really have an idea.
Maybe in the *public* API an additional `options` parameter for the "output-that-token"-function(s)?
Or even completely separate token manipulation on the one hand from serialization on the other, by having *two* Transforms streams: the first turning text (html) into tokens, i.e. in objectMode on the Readable side, and the second solely for serialization, i.e. transforming objects into text...?

---
:+1: for having read up to here! Looking forward to your thoughts :)

---
#### Footnote ####
(*) In fact, [in the source](https://github.com/inikulin/parse5/blob/06ff839a325bcc4b63e97d51e38d2f73c706eb05/packages/parse5-html-rewriting-stream/lib/index.js#L13) it says:
```javascript
    _transformChunk(chunk) {
        // NOTE: ignore upstream return value as we want to push to
        // the Writable part of Transform stream ourselves.
        super._transformChunk(chunk);
    }
```
This comment there, as such, cannot be right. Simply because there is no `push` in WritableStream. The important part is "ourselves", of course. But: should it be "Readable" instead of "Writable" or rather "write" instead of "push"...?! ;)

**Comment by meisl** [comment]
Maybe one way to approach this is to look at possible use-cases. From my side, and for now, there'd be
* have attribute names serialized with original case by default - with or without listeners to `startTag`. That's a workaround, and might better be solved in the tokenizer [TODO: there's an issue re this - ref it].
* normalize whitespace/indentation under `<head>`, but only there.
* normalize order of attributes for certain tags
* rewrite/remove certain attributes from certain tags (e.g. make URLs relative). Ideally this would be done rather concisely in the listener function; something like "poor-man's-jquery".
* generally, the default should always be to keep the original, except when I say otherwise. Particularly:
  - self-closing tags like `<meta ... />` - which are allowed (but not required) for "html void tags"
  - entities in both, attribute values and text nodes (encoded or not)
  - tag "properties" as in `<input type="checkbox" checked>`

---
p.s.: for the discussion at hand, what's important is the "how" - NOT the "why". But I'll try to explain, should you really want to know.

**Comment by inikulin** [comment]
Hi,

I appreciate your efforts writing down all your thoughts regarding serialization API. However, unfortunately, I'm quite limited in time to go through such a long reads during my open source work. 

Can you, please, explain in 3 bullet points (one sentence per each):
1. What's wrong with current API in your opinion
2. Why it's wrong 
3. What you propose instead

In the meantime, I'm closing this issue. Will be happy to reopen once there will be a clear explanation of the problem.

**Comment by meisl** [comment]
Ok, I'll try to compress my points as you suggested. Not sure though, if I manage to get along with only one sentence each...
