### ISSUE TITLE
SAXParser tests are overly lax

### ISSUE THREAD

**Issue by meisl** [inikulin/parse5#281]
Looking at the diff of `source.html` vs `expected.html` in `test/data/sax/lhc/` I stumbled upon some things I **couldn't believe SAXParser is supposed to do** (see examples below).

So how could the tests still pass?
In `packages/parse5-sax-parser/test/sax-parser-test.js` I found this:
```js
function sanitizeForComparison(str) {
    return removeNewLines(str)
        .replace(/\s/g, '')
        .replace(/'/g, '"')
        .toLowerCase();
}
```
* What about `<pre>`? `<script>`?
* Whitespace normalization might be OK within tags (whitespace between attributes) - but NOT for attribute values.
* In conjunction with automatic decoding of named entities (which I'd like to have optional), this also has the effect that e.g. a source text `How low&nbsp;is the pressure` could be turned into something like `h Owlowi SThEpr     eSsuRe` - and the *test would still pass!?*

I understand that some form of "sanitation" might be needed, but this is going to far.
Not only is this kind of test very misleading (to me, tests are a form of documentation, too), but also allowing for a seriously broken SAXParser going through without notice.

---
### Examples ###

* line 96
  - src: `<li class="menu-675"><a href="/students-educators">Students &amp; Educators</a></li>`
  - exp: `<li class="menu-675"><a href="/students-educators">Students & Educators</a></li>`
* line 154
  - src: `<p>&nbsp;</p>`
  - exp: `<p></p>`
* line 163
  - src: `<p>How many kilometres of cables are there on the LHC? How low&nbsp;is the pressure in the beam pipe? Discover facts and figures about the in the handy LHC guide</p>`
  - exp: `<p>How many kilometres of cables are there on the LHC? How lowis the pressure in the beam pipe? Discover facts and figures about the in the handy LHC guide</p>`
  ("lowis" in "How lowis the pressure...")

**Comment by inikulin** [comment]
It's not quite clear if this a suggestion, question or a bug report. 

- If it's a **suggestion** then I'll be happy to accept any PRs that improve testing of the SAX parser.

- If it's a **question** about state of things with SAX parser testing then here is the explanation: SAXParser is actually a very thin layer of API on top of `Tokenizer` (which extensively tested with dozen of thousands html5lib tests) and `ParserFeedbackSimulator` (which is, thanks to @RReverser's efforts, tested by even bigger number of tests that are generated from html5lib tree construction tests). So, the only purpose of SAXParser tests is just to check that these things are glued up together nicely, it doesn't make much sense to test parsing precisely as it's covered by unit testing of its component.

- If it's a **bug** report then, please, explain in details which issue in SAXParser you've found that were shadowed by the current tests.

In the meantime, if you wouldn't mind, I'll close this issue. Will be happy to reopen once there will be any information from the bullet points above.

**Comment by meisl** [comment]
It's been quite a while, so I'll have to get into this again myself.

Anyhow, to answer your main question: it's first and foremost a **question**, neither a bug report, nor a suggestion (yet). I was asking about the rationale behind mentioned tests.
For this you gave an answer / a few hints which sound quite reasonable to me, particularly: "only purpose ... is to check things are glued together nicely", precise parsing tests elsewhere).
My point is that I have the impression, that this very reasonable goal isn't actually quite achieved.

But again, right now I cannot reply with anymore details.
So, for the time being, I'm fine with this being closed until I can come up with more concrete questions, or maybe even suggestions (I'll dig into #284 first, though).
