### ISSUE TITLE
Fix location info in tokens from tokenizer - attrs/char-refs

### ISSUE THREAD

**Issue by meisl** [inikulin/parse5#284]
### Summary ###
Location info in tokens from tokenizer is wrong...
a) ...when there is no whitespace between an attribute value and the following attribute name (the token's `location.attrs['xyz']` is faulty)
b) ...when a character reference follows a character *of different type* (`CHARACTER_TOKEN` vs `WHITESPACE_CHARACTER_TOKEN` vs `NULL_CHARACTER_TOKEN`)
c) ...quite likely under other - yet unknown - circumstances. To back this very claim, I'd have to dig into details - which I will. Just not here and now.

I have reworked [`packages/parse5/test/location-info-tokenizer.test` in my fork](
https://github.com/meisl/parse5/blob/fix-location-at-char-ref-and-attrs/packages/parse5/test/location-info-tokenizer.test.js) s.t. it covers cases a), b) and more.
Note: originally, attribute locations were ignored altogether. So: case a) couldn't be detected, not even with an appropriate test case.

### Why didn't I make this a PR? ###
* As of now it's just the extended tests; no fix yet. I think I'd need someone knowledgeable for discussion and/or review. It's about `packages/parse5/lib/extensions/location-info`, which is comprised of several mixins, but from what I can see, the fix would be in `tokenizer-mixin.js` only. Maybe some changes in `packages/parse5/lib/tokenizer/index.js` as well.
* Combinations with the null-character `\u0000` and with null-character-references `&#0`, `&#x0` aren't covered completely.
* Character refs in attribute values aren't covered at all.
* The test code got pretty complicated. Particularly, I am now calculating a real location info object representing what's to be expected. This was necessary in order to understand what exactly is wrong, and moreover: *why*. However, this went so far that now really some stuff needs to be factored out, and be tested itself. I'd need advice where to put this, that is how to organize it s.t. it fits into the project.
* I don't completely understand the overall test organization. For example: when I do `npm run unit-tests` - mentioned test file gets executed *7 times over (!)*. How come?

Basically: I'm at a point where I need feedback.

### How to reproduce ###
* parse5 version: master at this point in time, i.e. v5.1.0 plus 3 commits; precisely: 06ff839a325bcc4b6
* Branch [`fix-location-at-char-ref-and-attrs` in my fork](https://github.com/meisl/parse5/tree/fix-location-at-char-ref-and-attrs)
* In root dir of said branch:
  - `node_modules/.bin/mocha --ui exports --color --reporter list packages/parse5/test/location-info-tokenizer.test.js`.
  - Or, if you've got time: `npm run unit-tests`
* See the test report below, it details (more) what's working and what is not
* Finally: two particular example fragments that yield tokens with incorrect location info. **I'll discuss each of them in detail**, by means of the corresponding (new) failure messages; **in follow-up comments**. This will be helpful for getting an idea where/what the actual problem with the location-info extension really is.
   a) `<div id ="foo"class="bar">` (note the *missing* space between `"foo"` and `class`; the space between `id` and `=` is deliberate!)
   b) `\t&lt;`

### The test report (so far) ###
Even though the original test file had several "test cases" in it, there was effectively only one large test. I made it one test per test case, added a description for each, and of course added quite a few new test cases.
Tests 0 through 4 are the original tests, the rest was added by me.
Failing test 10 covers a), failing tests 11 through 14, 18 and 19 cover b). 
```
  √ Location info (Tokenizer) 0 - [DATA_STATE/] complete document: 40ms
  √ Location info (Tokenizer) 1 - [RCDATA_STATE/title] from inside <title>: 4ms
  √ Location info (Tokenizer) 2 - [RAWTEXT_STATE/style] inside <style>: 4ms
  √ Location info (Tokenizer) 3 - [SCRIPT_DATA_STATE/script] inside <script>: 5ms
  √ Location info (Tokenizer) 4 - [PLAINTEXT_STATE/plaintext] after <plaintext>: 1ms
  √ Location info (Tokenizer) 5 - [DATA_STATE/body] one attribute: 4ms
  √ Location info (Tokenizer) 6 - [DATA_STATE/body] one attribute, unquoted: 12ms
  √ Location info (Tokenizer) 7 - [DATA_STATE/body] one attribute without value: 1ms
  √ Location info (Tokenizer) 8 - [DATA_STATE/body] two attributes with intermediate whitespace: 9ms
  √ Location info (Tokenizer) 9 - [DATA_STATE/body] two attributes with newlines in between: 7ms
  1) Location info (Tokenizer) 10 - [DATA_STATE/body] two attributes with no whitespace in between
  2) Location info (Tokenizer) 11 - [DATA_STATE/body] non-whitespace char-ref after plain whitespace
  3) Location info (Tokenizer) 12 - [DATA_STATE/body] non-whitespace char-ref after whitespace char-ref
  4) Location info (Tokenizer) 13 - [DATA_STATE/body] non-breaking-space after whitespace
  5) Location info (Tokenizer) 14 - [DATA_STATE/body] non-breaking-space char-ref after \u0000
  √ Location info (Tokenizer) 15 - [DATA_STATE/body] non-breaking-space character after \u0000: 2ms
  √ Location info (Tokenizer) 16 - [DATA_STATE/body] non-breaking-space after non-whitespace: 2ms
  √ Location info (Tokenizer) 17 - [DATA_STATE/body] whitespace char-ref after whitespace: 12ms
  6) Location info (Tokenizer) 18 - [DATA_STATE/body] whitespace char-ref after non-whitespace
  7) Location info (Tokenizer) 19 - [DATA_STATE/body] whitespace char-ref after non-whitespace char-ref
  √ Location info (Tokenizer) 20 - [DATA_STATE/body] non-whitespace char-ref after non-whitespace: 2ms

  14 passing (156ms)
  7 failing
```

**Comment by inikulin** [comment]
Hi, sorry for the delay in response. I'll be happy to help with the fix, however I'm a bit confused by the report. Is it possible to open separate tickets for each case where location info calculation fail with expected/actual results specified. After that we can work through each case.

**Comment by meisl** [comment]
Hello, thx for your feedback. Actually, I had given up hope. So, after over 2 months, I'll have to refresh my memory of this myself. For now I'll say this:

I understand your striving to break the problem up into smaller ones. However, as mentionend, I cannot really estimate the extent of the problem yet. That is, I am even unsure about *how* to separate (hence: whether splitting it up makes sense or not).

I guess the section "The test report" above isn't clear/accessible enough, right?
So maybe I should give a detailed example/walk-through of one of the failures here before I start opening several closely related new issues?
We could use this as a test as to how the particular problem should best be described, and only then decide whether separate issues make sense or not.

Then I need help w.r.t. how tests are supposed to be organized in parse5. I got the impression that there are several different strategies/ideas at work for this in parallel. I reckon that's just how it is / how it grew over time. That's ok with me, but I do need help as to how I should proceed with the tests for this issue (see last 2 bullet points of "Why didn't I make this a PR?").

I'll dig into this again, and make above things & questions more concrete. But I do need to know at least what you think about this proposal. I mean within a week, say, rather than months. No offence intended, it's just that I can't afford otherwise.

**Comment by meisl** [comment]
I'm sorry, but I do need at least a "make it so" or similar.
Given that I *will* put more effort into this, promised. But without anything - I won't. Sorry.
