### ISSUE TITLE
Error Not instaled 

### ISSUE THREAD

**Issue by CisSasGot** [inikulin/parse5#290]
PS G:\myProje\NOWE2019\GeneTeka> npm install --save parse5
npm WARN geneteka@1.0.0 No description
npm WARN geneteka@1.0.0 No repository field.

npm ERR! path G:\myProje\NOWE2019\GeneTeka\node_modules\parse5
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'G:\myProje\NOWE2019\GeneTeka\node_modules\parse5' -> 'G:\myProje\NOWE2019\GeneTeka\node_modules\.parse5.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\X\AppData\Roaming\npm-cache\_logs\2019-03-14T19_36_38_248Z-debug.log

## THIS LOG
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'parse5' ]
2 info using npm@6.7.0
3 info using node@v11.10.1
4 verbose npm-session cbfe40e96be97340
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/parse5 328ms (from cache)
8 silly pacote tag manifest for parse5@latest fetched in 365ms
9 timing stage:loadCurrentTree Completed in 668ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 101ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule parse5@5.1.0 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 113ms
18 timing stage:loadIdealTree Completed in 250ms
19 silly currentTree geneteka@1.0.0
19 silly currentTree +-- agent-base@4.2.1
19 silly currentTree +-- async-limiter@1.0.0
19 silly currentTree +-- balanced-match@1.0.0
19 silly currentTree +-- brace-expansion@1.1.11
19 silly currentTree +-- buffer-from@1.1.1
19 silly currentTree +-- concat-map@0.0.1
19 silly currentTree +-- concat-stream@1.6.2
19 silly currentTree +-- core-js@3.0.0-beta.18
19 silly currentTree +-- core-util-is@1.0.2
19 silly currentTree +-- debug@4.1.1
19 silly currentTree +-- es6-promise@4.2.6
19 silly currentTree +-- es6-promisify@5.0.0
19 silly currentTree +-- extract-zip@1.6.7
19 silly currentTree | +-- debug@2.6.9
19 silly currentTree | `-- ms@2.0.0
19 silly currentTree +-- fd-slicer@1.0.1
19 silly currentTree +-- fs-extra@7.0.1
19 silly currentTree +-- fs.realpath@1.0.0
19 silly currentTree +-- glob@7.1.3
19 silly currentTree +-- graceful-fs@4.1.15
19 silly currentTree +-- https-proxy-agent@2.2.1
19 silly currentTree | `-- debug@3.2.6
19 silly currentTree +-- inflight@1.0.6
19 silly currentTree +-- inherits@2.0.3
19 silly currentTree +-- isarray@1.0.0
19 silly currentTree +-- jsonfile@4.0.0
19 silly currentTree +-- mime@2.4.0
19 silly currentTree +-- minimatch@3.0.4
19 silly currentTree +-- minimist@0.0.8
19 silly currentTree +-- mkdirp@0.5.1
19 silly currentTree +-- ms@2.1.1
19 silly currentTree +-- once@1.4.0
19 silly currentTree +-- path-is-absolute@1.0.1
19 silly currentTree +-- pend@1.2.0
19 silly currentTree +-- process-nextick-args@2.0.0
19 silly currentTree +-- progress@2.0.3
19 silly currentTree +-- proxy-from-env@1.0.0
19 silly currentTree +-- puppeteer@1.13.0
19 silly currentTree +-- readable-stream@2.3.6
19 silly currentTree +-- rimraf@2.6.3
19 silly currentTree +-- safe-buffer@5.1.2
19 silly currentTree +-- string_decoder@1.1.1
19 silly currentTree +-- typedarray@0.0.6
19 silly currentTree +-- universalify@0.1.2
19 silly currentTree +-- util-deprecate@1.0.2
19 silly currentTree +-- wrappy@1.0.2
19 silly currentTree +-- ws@6.2.0
19 silly currentTree `-- yauzl@2.4.1
20 silly idealTree geneteka@1.0.0
20 silly idealTree +-- agent-base@4.2.1
20 silly idealTree +-- async-limiter@1.0.0
20 silly idealTree +-- balanced-match@1.0.0
20 silly idealTree +-- brace-expansion@1.1.11
20 silly idealTree +-- buffer-from@1.1.1
20 silly idealTree +-- concat-map@0.0.1
20 silly idealTree +-- concat-stream@1.6.2
20 silly idealTree +-- core-js@3.0.0-beta.18
20 silly idealTree +-- core-util-is@1.0.2
20 silly idealTree +-- debug@4.1.1
20 silly idealTree +-- es6-promise@4.2.6
20 silly idealTree +-- es6-promisify@5.0.0
20 silly idealTree +-- extract-zip@1.6.7
20 silly idealTree | +-- debug@2.6.9
20 silly idealTree | `-- ms@2.0.0
20 silly idealTree +-- fd-slicer@1.0.1
20 silly idealTree +-- fs-extra@7.0.1
20 silly idealTree +-- fs.realpath@1.0.0
20 silly idealTree +-- glob@7.1.3
20 silly idealTree +-- graceful-fs@4.1.15
20 silly idealTree +-- https-proxy-agent@2.2.1
20 silly idealTree | `-- debug@3.2.6
20 silly idealTree +-- inflight@1.0.6
20 silly idealTree +-- inherits@2.0.3
20 silly idealTree +-- isarray@1.0.0
20 silly idealTree +-- jsonfile@4.0.0
20 silly idealTree +-- mime@2.4.0
20 silly idealTree +-- minimatch@3.0.4
20 silly idealTree +-- minimist@0.0.8
20 silly idealTree +-- mkdirp@0.5.1
20 silly idealTree +-- ms@2.1.1
20 silly idealTree +-- once@1.4.0
20 silly idealTree +-- parse5@5.1.0
20 silly idealTree +-- path-is-absolute@1.0.1
20 silly idealTree +-- pend@1.2.0
20 silly idealTree +-- process-nextick-args@2.0.0
20 silly idealTree +-- progress@2.0.3
20 silly idealTree +-- proxy-from-env@1.0.0
20 silly idealTree +-- puppeteer@1.13.0
20 silly idealTree +-- readable-stream@2.3.6
20 silly idealTree +-- rimraf@2.6.3
20 silly idealTree +-- safe-buffer@5.1.2
20 silly idealTree +-- string_decoder@1.1.1
20 silly idealTree +-- typedarray@0.0.6
20 silly idealTree +-- universalify@0.1.2
20 silly idealTree +-- util-deprecate@1.0.2
20 silly idealTree +-- wrappy@1.0.2
20 silly idealTree +-- ws@6.2.0
20 silly idealTree `-- yauzl@2.4.1
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 19ms
23 silly diffTrees action count 1
24 silly diffTrees add parse5@5.1.0
25 silly decomposeActions action count 8
26 silly decomposeActions fetch parse5@5.1.0
27 silly decomposeActions extract parse5@5.1.0
28 silly decomposeActions preinstall parse5@5.1.0
29 silly decomposeActions build parse5@5.1.0
30 silly decomposeActions install parse5@5.1.0
31 silly decomposeActions postinstall parse5@5.1.0
32 silly decomposeActions finalize parse5@5.1.0
33 silly decomposeActions refresh-package-json parse5@5.1.0
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir C:\Users\X\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
37 verbose lock using C:\Users\X\AppData\Roaming\npm-cache\_locks\staging-ea906b4e7f888d79.lock for G:\myProje\NOWE2019\GeneTeka\node_modules\.staging
38 silly doParallel extract 1
39 silly extract parse5@5.1.0
40 silly tarball trying parse5@latest by hash: sha512-fxNG2sQjHvlVAYmzBZS9YlDp6PTSSDwa98vkD4QgVDDCAo84z5X1t5XyJQ62ImdLXx5NdIIfihey6xpum9/gRQ==
41 silly extract parse5@latest extracted to G:\myProje\NOWE2019\GeneTeka\node_modules\.staging\parse5-e6e8c5d0 (151ms)
42 timing action:extract Completed in 155ms
43 silly doReverseSerial unbuild 8
44 silly doSerial remove 8
45 silly doSerial move 8
46 silly doSerial finalize 8
47 silly finalize G:\myProje\NOWE2019\GeneTeka\node_modules\parse5
48 timing audit submit Completed in 351ms
49 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 352ms
50 timing audit body Completed in 0ms
51 timing action:finalize Completed in 60071ms
52 verbose unlock done using C:\Users\X\AppData\Roaming\npm-cache\_locks\staging-ea906b4e7f888d79.lock for G:\myProje\NOWE2019\GeneTeka\node_modules\.staging
53 timing stage:rollbackFailedOptional Completed in 5ms
54 timing stage:runTopLevelLifecycles Completed in 65945ms
55 silly saveTree geneteka@1.0.0
55 silly saveTree +-- core-js@3.0.0-beta.18
55 silly saveTree +-- fs-extra@7.0.1
55 silly saveTree | +-- graceful-fs@4.1.15
55 silly saveTree | +-- jsonfile@4.0.0
55 silly saveTree | `-- universalify@0.1.2
55 silly saveTree +-- parse5@5.1.0
55 silly saveTree `-- puppeteer@1.13.0
55 silly saveTree   +-- debug@4.1.1
55 silly saveTree   | `-- ms@2.1.1
55 silly saveTree   +-- extract-zip@1.6.7
55 silly saveTree   | +-- concat-stream@1.6.2
55 silly saveTree   | | +-- buffer-from@1.1.1
55 silly saveTree   | | +-- inherits@2.0.3
55 silly saveTree   | | +-- readable-stream@2.3.6
55 silly saveTree   | | | +-- core-util-is@1.0.2
55 silly saveTree   | | | +-- isarray@1.0.0
55 silly saveTree   | | | +-- process-nextick-args@2.0.0
55 silly saveTree   | | | +-- safe-buffer@5.1.2
55 silly saveTree   | | | +-- string_decoder@1.1.1
55 silly saveTree   | | | `-- util-deprecate@1.0.2
55 silly saveTree   | | `-- typedarray@0.0.6
55 silly saveTree   | +-- debug@2.6.9
55 silly saveTree   | | `-- ms@2.0.0
55 silly saveTree   | +-- mkdirp@0.5.1
55 silly saveTree   | | `-- minimist@0.0.8
55 silly saveTree   | `-- yauzl@2.4.1
55 silly saveTree   |   `-- fd-slicer@1.0.1
55 silly saveTree   |     `-- pend@1.2.0
55 silly saveTree   +-- https-proxy-agent@2.2.1
55 silly saveTree   | +-- agent-base@4.2.1
55 silly saveTree   | | `-- es6-promisify@5.0.0
55 silly saveTree   | |   `-- es6-promise@4.2.6
55 silly saveTree   | `-- debug@3.2.6
55 silly saveTree   +-- mime@2.4.0
55 silly saveTree   +-- progress@2.0.3
55 silly saveTree   +-- proxy-from-env@1.0.0
55 silly saveTree   +-- rimraf@2.6.3
55 silly saveTree   | `-- glob@7.1.3
55 silly saveTree   |   +-- fs.realpath@1.0.0
55 silly saveTree   |   +-- inflight@1.0.6
55 silly saveTree   |   | +-- once@1.4.0
55 silly saveTree   |   | | `-- wrappy@1.0.2
55 silly saveTree   |   | `-- wrappy@1.0.2
55 silly saveTree   |   +-- minimatch@3.0.4
55 silly saveTree   |   | `-- brace-expansion@1.1.11
55 silly saveTree   |   |   +-- balanced-match@1.0.0
55 silly saveTree   |   |   `-- concat-map@0.0.1
55 silly saveTree   |   +-- once@1.4.0
55 silly saveTree   |   `-- path-is-absolute@1.0.1
55 silly saveTree   `-- ws@6.2.0
55 silly saveTree     `-- async-limiter@1.0.0
56 warn geneteka@1.0.0 No description
57 warn geneteka@1.0.0 No repository field.
58 verbose stack Error: ENOENT: no such file or directory, rename 'G:\myProje\NOWE2019\GeneTeka\node_modules\parse5' -> 'G:\myProje\NOWE2019\GeneTeka\node_modules\.parse5.DELETE'
59 verbose cwd G:\myProje\NOWE2019\GeneTeka
60 verbose Windows_NT 10.0.18348
61 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "parse5"
62 verbose node v11.10.1
63 verbose npm  v6.7.0
64 error path G:\myProje\NOWE2019\GeneTeka\node_modules\parse5
65 error code ENOENT
66 error errno -4058
67 error syscall rename
68 error enoent ENOENT: no such file or directory, rename 'G:\myProje\NOWE2019\GeneTeka\node_modules\parse5' -> 'G:\myProje\NOWE2019\GeneTeka\node_modules\.parse5.DELETE'
69 error enoent This is related to npm not being able to find a file.
70 verbose exit [ -4058, true ]

**Comment by inikulin** [comment]
This is an npm issue and should be reported in their bug tracker: https://npm.community/c/bugs
