### ISSUE TITLE
how to resolve the problem when using serilize method to  auto closed tag fragment

### ISSUE THREAD

**Issue by duxianzhang** [inikulin/parse5#296]
```
const { parseFragment, serialize } = require('parse5')

const code1 = `<div><input></input></div>`
const code2 = `<div><input /></div>`

let t1 = parseFragment(code1)
t1 = serialize(t1)
console.log(t1)

let t2 = parseFragment(code2)
t2 = serialize(t2)
console.log(t2)

// log:
// <div><input></div>
// <div><input></div>
```

**Comment by inikulin** [comment]
All 3 cases (`<div><input></input></div>`,  `<div><input /></div>`, `<div><input></div>`) are syntactically identical and all resolve into the same DOM-tree.  The only distinction is that `<div><input></input></div>` also has a conformance error - `<input>` is a void element which means that it doesn't require an end tag. So, `</input>` is a dangling end tag. 

I don't believe there is any problem here, unless you wan't conformance error in the serialised markup.
