### ISSUE TITLE
Undesirable `srcset` attr parsing behavior

### ISSUE THREAD

**Issue by harrysolovay** [inikulin/parse5#297]
### Basic info:

- **Node.js version:** 11.12.0

I'm trying to use `parse5` to turn all relative paths of an HTML file into absolute paths. I need to interact with ASTs for the sake of preventing content from being transformed (I only want to transform linked resources, aka. attributes). The HTML I'd like to transform contains many `srcset`s... which seem to be turned into `src`s by the parser. Additionally, the parser encodes the associated values. Swapping the value within the base64-encode is tough... I suppose I could use another library to transform it back... but hopefully there's a better way. I don't understand why the parser is behaving this way (probably to match browser specs?).

Below is the reproduction... any advice would be greatly appreciated. Thank you!

### Minimal reproduction case

```js
const {parse} = require('parse5');
const {includes, replace, startsWith} = require('ramda');

const parsed = parse(theHTML);

const target = '/somepath';
const replacement = 'https://pathprefix.com/somepath';

(() => {
  const traverse = node => {
    const {attrs, childNodes} = node;

    if (attrs && attrs.length) {
      for (let attributeI in attrs) {
        const {name, value} = attrs[attributeI];

        if (
          typeof value === 'string' &&
          (name === 'srcset' || startsWith(target, value))
        ) {
          node.attrs[attributeI].value = replace(target, replacement, value);
        }
      }
    }

    if (childNodes)
      for (let childNode of childNodes) {
        traverse(childNode);
      }
  };

  traverse(parsed);
})();
```

**Comment by harrysolovay** [comment]
@inikulin –– sorry to ping you directly, but my use-case is time-sensitive. Any insight would mean a lot to me!

**Comment by wooorm** [comment]
@harrysolovay I doubt that parse5 is changing `srcset` to `src`. I’m also not sure what the base64 part you mention is all about. Anyway: the code you provided does not show these two problems, so it’s not possible to debug them. Could you expand on that?

[AST explorer link showing srcset working fine](https://astexplorer.net/#/gist/b5b45a26e89517e768e86cc4da79be69/ddd9722decf9dd9d1d9e8967aadb81710e542fa0)

**Comment by harrysolovay** [comment]
![Screen Shot 2019-06-14 at 3 17 03 PM](https://user-images.githubusercontent.com/4893548/59541743-931fb980-8eb7-11e9-97af-2f482018c818.png)

I'm not getting the right parse behavior for some reason. Any tips? The HTML I'm trying to parse is valid –– can be found at [this link](https://amplify.aws/community/newsletters/2019/22).

**Comment by wooorm** [comment]
The HTML you are parsing is indeed valid. The problem is that the picture element is in a `noscript` element. Parse5 parses as if scripting was enabled, which dictates that anything inside a `noscript` is seen as text instead of elements and the like. This is the same behaviour as browsers with scripting (JS) enabled.

If you’d remove the opening and closing tags of the `noscript` element, everything works as you’d expect.

Or, you can turn off scripting through Parse5s options: https://github.com/inikulin/parse5/blob/master/packages/parse5/docs/options/parser-options.md#optional-scriptingenabled.

**Comment by harrysolovay** [comment]
@wooorm gotcha. Is there a way to override this behavior? (also, thank you for the help!)

**Comment by wooorm** [comment]
See the last line:

> Or, you can turn off scripting through Parse5s options: https://github.com/inikulin/parse5/blob/master/packages/parse5/docs/options/parser-options.md#optional-scriptingenabled.

**Comment by harrysolovay** [comment]
@wooorm thank you so much for the help!
