### ISSUE TITLE
Whitespaces in <pre> tag

### ISSUE THREAD

**Issue by horosgrisa** [inikulin/parse5#306]
First:
See AST: https://astexplorer.net/#/gist/0f1617aea8940c23c242972a7bb4b182/ea9447e8f5a03642c5114bc734ffc8f928cdc1ba

And HTML: https://jsbin.com/hehiforito/edit?html,output

So, I have spaces before letter `a`, but in AST I have onliy single space.

**Comment by inikulin** [comment]
It is the same as https://github.com/inikulin/parse5/issues/160. If you check AST explorer markup with dev tools you will find all of them, they just not rendered properly by the AST explorer UI.
I suggest you to open a bug in https://github.com/fkling/astexplorer
