### ISSUE TITLE
Late TypeError

### ISSUE THREAD

**Issue by Marvin9** [inikulin/parse5#309]
If we pass a data type other than string we get **TypeError** in confusing manner which seems not good.

``` javascript
require('parse5').parse(1);
```
![Screenshot (111)](https://user-images.githubusercontent.com/17699717/72801813-5c412b80-3c70-11ea-93df-2e8a9083cd69.png)

Why don't we add validation in parse function itself. Make it accepts only strings.

**Comment by inikulin** [comment]
JavaScript is a dynamically type language and I don't see a point in adding argument type validation, especially if they are outlined in the [API documentation](https://github.com/inikulin/parse5/blob/master/packages/parse5/docs/index.md#parse). 

If you strive for the type safety you need something that can guarantee it, i.e. TypeScript. TS typings for parse5 can be found here: https://www.npmjs.com/package/@types/parse5
