### ISSUE TITLE
eslint fail on fresh clone

### ISSUE THREAD

**Issue by SheetJSDev** [inikulin/parse5#310]
Starting from a fresh clone, `npm run test` fails on the `eslint` step thanks to the `prettier/prettier` rule

```
/tmp/parse5/test/utils/generate-parsing-tests.js
  106:120  error  Replace `⏎····················test.lineNum⏎················` with `test.lineNum`  prettier/prettier
```

The offending part:

```js
                const testName = `${prefix}(${test.dirName}) - ${test.idx}.${test.setName} - \`${test.input}\` (line ${
                    test.lineNum
                })`;
```

A possible fix puts the whole thing in one line:

```js
                const testName = `${prefix}(${test.dirName}) - ${test.idx}.${test.setName} - \`${test.input}\` (line ${test.lineNum})`;
```

**Comment by inikulin** [comment]
@SheetJSDev Strange, I can't reproduce that. Is it possible that you have prettier configuration specified elsewhere that affects the checked out repo?

**Comment by SheetJSDev** [comment]
Hmm it's probably a local configuration issue -- the issue is reproducible on this computer, but cannot be reproduced in a ubuntu VM.
