### ISSUE TITLE
/node_modules/parse5/lib"' has no exported member 'ElementLocation'.causes program compilation to fila

### ISSUE THREAD

**Issue by laishiwen** [inikulin/parse5#313]
// fail info
![image](https://user-images.githubusercontent.com/17078631/77386282-693fdf80-6dc5-11ea-90e9-d026ee5bb74d.png)

// bad
![image](https://user-images.githubusercontent.com/17078631/77386351-92f90680-6dc5-11ea-9e97-87f0cae27ffb.png)

// great
step 1:
![image](https://user-images.githubusercontent.com/17078631/77386476-d9e6fc00-6dc5-11ea-834b-0b62a3b2f12a.png)

step 2:
![image](https://user-images.githubusercontent.com/17078631/77386637-3d712980-6dc6-11ea-9daf-50d09c645086.png)

step 3:
![image](https://user-images.githubusercontent.com/17078631/77386542-06027d00-6dc6-11ea-80c1-965256f5447a.png)

**Comment by laishiwen** [comment]
please，administrator repair it's in time

**Comment by chav-aniket** [comment]
Hey @laishiwen, I'm currently having this problem, could you please share how you solved this?

**Comment by chav-aniket** [comment]
Solved with a version bump of `jsdom` from 19 to 20
