### ISSUE TITLE
Proposal: Add option to allow all tags as self-closing

### ISSUE THREAD

**Issue by dummdidumm** [inikulin/parse5#322]
It would be great if `parse5` would have an option that would ignore the self-closing tag validation.

`parse('<div />', { allowSelfClosingForAllTags: true })` --> would output a parsed tree instead of failing due to the validation.

This would be `false` by default to not change existing behavior.

**Comment by ClassName** [comment]
+1

**Comment by qingchiapp** [comment]
+1

**Comment by ottworks** [comment]
+1

**Comment by RReverser** [comment]
It wouldn't be great because it's a complete violation of HTML spec, and the produced DOM would be incorrect. If you want to parse XML, it's best you use an XML parser.

**Comment by RReverser** [comment]
Plus, it already doesn't fail due to validation (there is no validation in parse5), it already produces an AST with valid structure as per spec: https://astexplorer.net/#/gist/c9b085d63f4b7ad624af488a0504875a/19c0dcf6dadd6c165e4e88f63d1301b870215639

**Comment by ottworks** [comment]
I've fixed my specific problem (non-standard self-closing elements eating the rest of the tree) with this patch:
```diff
diff --git a/node_modules/parse5/lib/parser/index.js b/node_modules/parse5/lib/parser/index.js
old mode 100644
new mode 100755
index 45d3e83..3859372
--- a/node_modules/parse5/lib/parser/index.js
+++ b/node_modules/parse5/lib/parser/index.js
@@ -1151,7 +1151,6 @@ function tokenBeforeHead(p, token) {
 //------------------------------------------------------------------
 function startTagInHead(p, token) {
     const tn = token.tagName;
-
     if (tn === $.HTML) {
         startTagInBody(p, token);
     } else if (tn === $.BASE || tn === $.BASEFONT || tn === $.BGSOUND || tn === $.LINK || tn === $.META) {
@@ -1668,8 +1667,12 @@ function svgStartTagInBody(p, token) {
 }
 
 function genericStartTagInBody(p, token) {
-    p._reconstructActiveFormattingElements();
-    p._insertElement(token, NS.HTML);
+    if (p.options.voidElements && p.options.voidElements.includes(token.tagName)) {
+        areaStartTagInBody(p, token)
+    } else {
+        p._reconstructActiveFormattingElements();
+        p._insertElement(token, NS.HTML);
+    }
 }
 
 //OPTIMIZATION: Integer comparisons are low-cost, so we can use very fast tag name length filters here.
```
I'm not familiar with the project so I don't know if this is a 'complete' solution, but support for custom tag behavior would be very welcome.
