### ISSUE TITLE
Update package-lock.json

### ISSUE THREAD

**Issue by frank-dspeed** [inikulin/parse5#331]
# npm audit report

acorn  5.5.0 - 5.7.3 || 6.0.0 - 6.4.0 || 7.0.0 - 7.1.0
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1488
fix available via `npm audit fix`
node_modules/acorn

dot-prop  <4.2.1 || >=5.0.0 <5.1.1
Severity: high
Prototype Pollution - https://npmjs.com/advisories/1213
fix available via `npm audit fix`
node_modules/compare-func/node_modules/dot-prop
node_modules/dot-prop
  compare-func  <=1.3.4
  Depends on vulnerable versions of dot-prop
  node_modules/compare-func
    conventional-changelog-angular  0.0.1 - 5.0.10
    Depends on vulnerable versions of compare-func
    node_modules/conventional-changelog-angular
    conventional-changelog-writer  <=4.0.16
    Depends on vulnerable versions of compare-func
    node_modules/conventional-changelog-writer

handlebars  <=4.7.3
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1316
Arbitrary Code Execution - https://npmjs.com/advisories/1324
Depends on vulnerable versions of optimist
fix available via `npm audit fix`
node_modules/conventional-changelog-writer/node_modules/handlebars

ini  <1.3.6
Prototype Pollution - https://npmjs.com/advisories/1589
fix available via `npm audit fix`
node_modules/ini

kind-of  6.0.0 - 6.0.2
Validation Bypass - https://npmjs.com/advisories/1490
fix available via `npm audit fix`
node_modules/kind-of

lodash  <4.17.19
Prototype Pollution - https://npmjs.com/advisories/1523
fix available via `npm audit fix`
node_modules/@lerna/command/node_modules/lodash
node_modules/@lerna/prompt/node_modules/lodash
node_modules/lodash

minimist  <0.2.1 || >=1.0.0 <1.2.3
Prototype Pollution - https://npmjs.com/advisories/1179
fix available via `npm audit fix --force`
Will install mocha@8.3.0, which is a breaking change
node_modules/get-pkg-repo/node_modules/minimist
node_modules/meow/node_modules/minimist
node_modules/minimist
node_modules/strong-log-transformer/node_modules/minimist
  mkdirp  0.4.1 - 0.5.1
  Depends on vulnerable versions of minimist
  node_modules/mkdirp
    mocha  1.21.5 - 6.2.2 || 7.0.0-esm1 - 7.1.0
    Depends on vulnerable versions of mkdirp
    node_modules/mocha
  optimist  >=0.6.0
  Depends on vulnerable versions of minimist
  node_modules/optimist
    handlebars  <=4.7.3
    Depends on vulnerable versions of optimist
    node_modules/conventional-changelog-writer/node_modules/handlebars

node-fetch  <=2.6.0 || 3.0.0-beta.1 - 3.0.0-beta.8
Denial of Service - https://npmjs.com/advisories/1556
fix available via `npm audit fix`
node_modules/@lerna/gitlab-client/node_modules/node-fetch
node_modules/node-fetch

yargs-parser  <=13.1.1 || 14.0.0 - 15.0.0 || 16.0.0 - 18.1.1
Prototype Pollution - https://npmjs.com/advisories/1500
fix available via `npm audit fix`
node_modules/yargs-parser

15 vulnerabilities (9 low, 1 moderate, 5 high)

**Comment by RReverser** [comment]
package-lock.json doesn't matter for libraries, it's only used for testing.

**Comment by frank-dspeed** [comment]
I know but i did a commit so i need to track that.

**Comment by fb55** [comment]
Done!
