### ISSUE TITLE
Usage in browser

### ISSUE THREAD

**Issue by eGavr** [inikulin/parse5#34]
Hi!
Really good parser!

Can I use it in browser?

**Comment by inikulin** [comment]
Hi, you can build client-side parse5 package using [browserify](https://github.com/substack/node-browserify). Or just use this snippet for the fragment parsing:
```js
var parseHTML = function(str) {
  var tmp = document.implementation.createHTMLDocument();
  tmp.body.innerHTML = str;
  return tmp.body.children;
};

parseHTML(htmlString);
```
