### ISSUE TITLE
`serialize` doesn't preserve doctype as it was in original html before parsing

### ISSUE THREAD

**Issue by kapooostin** [inikulin/parse5#343]
The following
```js
const str = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>`

parse.serialize(parse.parse(str))
```
results in
```js
'<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>'
```

The child nodes for `#documentType` are present after parsing but then being stripped during serializing. Is it an intended behaviour? Is there an option to pass to `serialize` for preventing it?

I could guess that such a doctype might be useless for a modern browser, but I need it later to be inserted into an email, so it'd better be left intact.

**Comment by kristoferjoseph** [comment]
*bump*

Is there a supported way to pass one's own `DOCTYPE`, `html`, `head`, `body` in a way that is not stripped out during serialize?

**Comment by wooorm** [comment]
Hey! This is behavior dictated by the HTML spec, which Parse5 follows:

See: <https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments>, case 4.2.5 “If current node is a DocumentType”, and note that `node.name` for that doctype is `'html'`.
