### ISSUE TITLE
Support for Web Browser?

### ISSUE THREAD

**Issue by angelozerr** [inikulin/parse5#35]
I tell me if parse5 could be executedd too inside web browser?

tern https://github.com/marijnh/tern provides this cool feature. You can execute the JS inference engine 

* inside node 
* or web browser.

To fix problem with require, it use this code :: 

```javascript
(function(root, mod) {
  if (typeof exports == "object" && typeof module == "object") // CommonJS
    return mod(exports, require("./infer"), require("./signal"),
               require("acorn/acorn"), require("acorn/util/walk"));
  if (typeof define == "function" && define.amd) // AMD
    return define(["exports", "./infer", "./signal", "acorn/acorn", "acorn/util/walk"], mod);
  mod(root.tern || (root.tern = {}), tern, tern.signal, acorn, acorn.walk); // Plain browser env
})(this, function(exports, infer, signal, acorn, walk) {
...
``` 

See https://github.com/marijnh/tern/blob/master/lib/tern.js

**Comment by inikulin** [comment]
Hi, I can't see any issue using it in the browser. However, you will need to [browserify](https://github.com/substack/node-browserify) it first. See also: #34

**Comment by angelozerr** [comment]
> Hi, I can't see any issue using it in the browser. 

In my case I would like to use to support completion for attributes id inside web browser editor with tern http://ternjs.net/doc/demo.html (and Sublime, Emacs, Vim, Eclipse which works with node) :  

```javascript
<html>
  <body>
    <div id="MyId" ></div> 
  </body>
  <script>
  document.getElementById(' // here Ctrl+Space shows MyId
  </script>
</html>
```

> However, you will need to browserify it first. See also: #34

Thank's for the info!
