### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by KennyGoi** [inikulin/parse5#361]
**Affected files**:
parse5/lib/tokenizer/index.js
`2023: [NAMED_CHARACTER_REFERENCE_STATE](cp) {`

parse5/lib/tokenizer/index.js
`2024: const matchResult = this._matchNamedCharacterReference(cp);`

parse5/lib/tokenizer/index.js
`509: _matchNamedCharacterReference(startCp) {`

parse5/lib/tokenizer/index.js
`514: this.tempBuff.push(startCp);`

parse5/lib/tokenizer/index.js
`527: const cp = this._consume();`

parse5/lib/tokenizer/index.js
`537: i = current & HAS_BRANCHES_FLAG ? findNamedEntityTreeBranch(i, cp) : -1;`

parse5/lib/tokenizer/index.js
`545: this._unconsume();`

parse5/lib/tokenizer/index.js
`2024: const matchResult = this._matchNamedCharacterReference(cp);`

parse5/lib/tokenizer/index.js
`2028: if (this._ensureHibernation()) {`

parse5/lib/tokenizer/index.js
`2044: this._flushCodePointsConsumedAsCharacterReference();`

parse5/lib/tokenizer/index.js
`572: if (this._isCharacterReferenceInAttribute()) {`

parse5/lib/tokenizer/index.js
`573: for (let i = 0; i < this.tempBuff.length; i++) {`

parse5/lib/tokenizer/index.js
`2023: [NAMED_CHARACTER_REFERENCE_STATE](cp) {`

parse5/lib/tokenizer/index.js
`2024: const matchResult = this._matchNamedCharacterReference(cp);`

parse5/lib/tokenizer/index.js
`509: _matchNamedCharacterReference(startCp) {`

parse5/lib/tokenizer/index.js
`514: this.tempBuff.push(startCp);`

parse5/lib/tokenizer/index.js
`527: const cp = this._consume();`

parse5/lib/tokenizer/index.js
`537: i = current & HAS_BRANCHES_FLAG ? findNamedEntityTreeBranch(i, cp) : -1;`

parse5/lib/tokenizer/index.js
`545: this._unconsume();`

parse5/lib/tokenizer/index.js
`2024: const matchResult = this._matchNamedCharacterReference(cp);`

parse5/lib/tokenizer/index.js
`2028: if (this._ensureHibernation()) {`

parse5/lib/tokenizer/index.js
`2044: this._flushCodePointsConsumedAsCharacterReference();`

parse5/lib/tokenizer/index.js
`572: if (this._isCharacterReferenceInAttribute()) {`

parse5/lib/tokenizer/index.js
`577: this._emitSeveralCodePoints(this.tempBuff);`

parse5/lib/tokenizer/index.js
`496: _emitSeveralCodePoints(codePoints) {`

parse5/lib/tokenizer/index.js
`497: for (let i = 0; i < codePoints.length; i++) {`

**Risks**:
An attacker could provide a very high loop iteration count, causing the loop to go on for prolonged periods of time, potentially causing the application to stop responding. Additionally, if the operation inside the loop is tied to some exhaustible functionality, it may cause bloat elsewhere; For example - if file writes occur inside the loop, then an attacker can cause that file to bloat by simply engaging this file writing capability a very high amount of times.

The application relied on a user-provided value to determine the number of iterations performed by a loop, without enforcing a limited range for this value.

**Comment by fb55** [comment]
Hi @KennyGoi, not sure I understand what issue you are reporting.

A parser is always going to be processing user input, and exhibit longer processing times with a longer input. For parse5, this should be roughly linear in the size of the input (with some exceptions); you would expect the same behavior from eg. `JSON.parse`.

**Comment by fb55** [comment]
Closing as I am not sure what the issue is here.
