### ISSUE TITLE
How do I know which version of chromium is used in the current version

### ISSUE THREAD

**Issue by 52jaden** [inikulin/parse5#363]
When scanning with blackduck, it is suggested that the version of chromium used is vulnerable

**Comment by fb55** [comment]
`parse5` doesn't use Chromium 🙂

**Comment by 52jaden** [comment]
Thank you very much for your reply.
When using blackduck scanning, the results show that parse5-htmlparser2-tree-adapter uses a risky version of chromium.
But I can't find chromium.
Does this mean that the blackduck scan is wrong?

> `parse5` doesn't use Chromium 🙂

**Comment by fb55** [comment]
> Does this mean that the blackduck scan is wrong?

That's what I would assume.
