### ISSUE TITLE
Add an option to disable auto-compensating for missing opening/closing tag

### ISSUE THREAD

**Issue by ShayRubach** [inikulin/parse5#364]
Hey all. I want to suggest an option to disable such 'optimization' (not really) as in #345 (i.e).
I do realize this is the default behavior of the browser (and every other parser, including native DOMParser), but I figured it can be toggled with an optional flag.

For example, let the input be:
`let html = "<p></tr>"`
a parsed version of the input (as a fragment) will be:
`<p></p>`

The parser added a closing tag to `<p>` and removed the `</tr>` tag entirely since it has no opener.
I wish to be able to work on such input, without any compensation whatsoever by the parser. 

If you could kindly suggest where is the code that is responsible for the above, I'm sure I can get a PR going for it.

Thanks!

**Comment by fb55** [comment]
An HTML parser is mostly interested in building a tree, which will never keep invalid closing tags. What you are looking for is a tokenizer, which will give you a stream of tokens without filtering out anything. `parse5` contains such a tokenizer. You can use it this way:

```js
const Tokenizer = require('parse5/lib/tokenizer');

// Write your
const tokenizer = new Tokenizer();
tokenizer.write('<p>', false)
// ...
tokenizer.write('</tr>', true) // `true` means this is the last chunk

// Read the tokens
let token;
do {
  token = tokenizer.getNextToken();
  // Do what you want with the token
} while (token.type !== Tokenizer.EOF_TOKEN);
```

Hope this helps!

**Comment by fb55** [comment]
You would have to hand-roll a serializer, which isn't actually that complicated. Have a look at the `Serializer` class for most of the necessary logic.

As for traversals: You would just iterate over the stream of tokens. There is no semantic relationship in-between them, as this is done in the parser, during tree construction.

**Comment by wooorm** [comment]
@ShayRubach https://github.com/rehypejs/rehype

**Comment by ShayRubach** [comment]
Thank you guys, I'll check all of the options out! 

P.S. you opened my eyes to the world of Tokenizers and it led me to find a backend implementation that might work as well (Golang), which is something I was hoping to find at some point anyway.
