### ISSUE TITLE
well-known self-closing tags not parsed as such

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#39]
```js
var parse5 = new (require("parse5")).SimpleApiParser({
	startTag: function(tagName,attrs,selfClosing){ console.log(tagName,selfClosing) },
	endTag: function(tagName){ console.log(tagName) }
});

parse5.parse('<img src="asdf"/>');	//-> img true
parse5.parse('<img src="asdf">');	//-> img false
```
`<img>` is self closing, with or without the XML closer.

**Comment by inikulin** [comment]
`Has no end tag` !== `Self-closing`

**Comment by domenic** [comment]
Just compare tagName to https://www.npmjs.com/package/void-elements

**Comment by stevenvachon** [comment]
Ok, thanks.

**Comment by stevenvachon** [comment]
Revisiting this. How will this library handle void elements when it supports streaming (#26)? I'd imagine that the events would be delayed until a parent element is closed. Anyhow, such a scenario could warrant a `voidElement` argument.
