### ISSUE TITLE
Conditional comments

### ISSUE THREAD

**Issue by eGavr** [inikulin/parse5#41]
It would be great if your SAX parser could give the information about the `conditional comments`.

**Comment by inikulin** [comment]
Conditional comments are not part of the HTML5 specification, so I don't think that this functionality should be implemented on the parse5 side. However, they have quite simple grammar and can be easily parsed from the comment text using regular expression ([example](https://github.com/inikulin/BootML/blob/master/lib/resource_shorthands.js#L19)).

**Comment by eGavr** [comment]
Thanks for the quick response!
