### ISSUE TITLE
Compatible query selector library

### ISSUE THREAD

**Issue by moll** [inikulin/parse5#42]
Hey,

Giving Parse5 a try. I haven't yet been able to find a compatible CSS/`querySelector`-style query library to actually find objects in the returned DOM tree. Which have you found?

Thanks!

**Comment by inikulin** [comment]
Hi,

Query selection requires some DOM-like layer, while parse5 returns just bare tree. I can suggest to take a look at [jsdom](https://github.com/tmpvar/jsdom) or [whacko](https://github.com/inikulin/whacko). They are both using parse5 as an underlying platform.

**Comment by moll** [comment]
I was under the impression Parse5's returned tree was DOM compatible at least property-wise (sans methods). Then a query lib that could traverse that tree would be sufficient. So far I found the [XMLDOM project](https://github.com/jindw/xmldom) which does the former. Still looking for that query lib. ;)

**Comment by inikulin** [comment]
parse5 is the HTML parser, not DOM implementation. Why suggested libraries doesn't meet your requirements? Any specific case?

**Comment by moll** [comment]
Thanks, though JSDOM's feels like overkill with its remote resource loading and trickery. All I'm after is a getting a basic DOM-like back (DOM-like merely to not waste time learning yet another tree structure or API) to assert on. That rules out Whacko and Parse5.

XMLDOM seems to return a basic DOM structure. I and everyone else already knows the DOM APIs like `el.getAttribute` and `el.tagName` by heart. Trying it out now with an Xpath library to simplify querying.

**Comment by inikulin** [comment]
Then take a look at [minidom](https://www.npmjs.com/package/minidom) lib.

**Comment by moll** [comment]
Thanks, that seems pretty useful! If only there were a `querySelector` implementation I could pass a DOM from Minidom to ease finding a particular element. All of the ones I've found expect there to be a global `window` or `document`...
You don't happen to know one?

**Comment by inikulin** [comment]
jsdom uses [nwmatcher](https://github.com/dperini/nwmatcher) lib for querying (see: https://github.com/tmpvar/jsdom/blob/2ff5747488ad4b518fcef97a026c82eab42a0a14/lib/jsdom/living/selectors.js). You can try to adopt it with minidom. But it's quick code investigation shows that it still requires quite complex DOM implementatuin to operate properly, so seems like you will still end up with your own partial implementation of JSDOM :wink:

**Comment by moll** [comment]
Thanks.

Jeesh. Things are so coupled in this traversing world. All you need in theory is a selector parser and traversing function capable of moving down a DOM1 tree and comparing a few `tagNames` values and `getAttribute` calls. But I guess some people like the job security they get from overcomplicating shit. ^_^

**Comment by inikulin** [comment]
The issue is that for full-fetured CSS3 level querying you need really consider a lot of edge-cases and this thing is not as simple as it seems. This is really quite complex stuff. You can't just compare attributes, DOM is live structure, you should also consider live properties. You can't also retraverse tree on each query, because it will be just performance overkill, so you need to introduce some kind of memoization. You need query string parser after all (~45 selectors + combinations.) And... :tired_face:   Just believe me things are enormously complex and fucked up. And it's not because of twisted fantasy of the guys who loves to overcomplicated, but because of complexity of things we have nowadays in our browsers.   But if you need just a slow implemetation of some queries, then you can basically implement them yourself, it's not a big deal: tree walker + filtering clause.

**Comment by moll** [comment]
Well, I don't doubt emulating a browser DOM isn't hard, but in our parsing contexts the DOM's static and as always, first make it work, then make it fast. I haven't even found anything besides JSDOM's `querySelectorAll` that works.

The Xpath libraries I mentioned above manages to do fairly well. It's not coupled to a parsing library, doesn't need a global `document` object and works according to a DOM spec. Perhaps a little too much to-spec as it annoys me a little with its namespaceURI pedantry, but at least it works. Not with Minidom, mind you, as its DOM 1 spec is missing a `localName` property and there's something with `attributes` that prevents Xpath from working. :P

When it comes to querySelector, I'd be happy with CSS2 level querying. Anything, frankly, that's better than typing out seventy four periods to get an `input[name=foo]` element in a form. ;-)

**Comment by fb55** [comment]
You can port `css-select` (which is used by cheerio & whacko) quite easily by swapping out just a few accessor functions. There is already a `browser_functions.js` file that can be used as a replacement of the `domutils`, which should do the trick, it isn't up to date, though. (At least `domutils.removeSubsets` is  used internally & not part of the file, which you would need to port – PRs are appreciated :) ).

**Comment by moll** [comment]
Thanks. I ended up going with **XMLDOM** and **XPath**.

Besides the slight annoyance of [too verbose tag names](https://github.com/goto100/xpath/issues/27) (which I worked around with a simple regexp) it's a fairly composable and decoupled solution that works _today_. I couldn't get **Minidom** to work like I described above.
