### ISSUE TITLE
Documentation Link goes 404 error

### ISSUE THREAD

**Issue by iamkumaran** [inikulin/parse5#422]
Hi,

I tried to access documentation from "https://github.com/inikulin/parse5/tree/master/packages/parse5" and the below link shows 404 error,
https://github.com/inikulin/parse5/tree/master/packages/parse5/docs/index.md

**Comment by avotoko** [comment]
The documentation is in the folder parse5-6.0.1/packages/parse5/docs/ in the package.
Package here: https://github.com/inikulin/parse5/releases
