### ISSUE TITLE
HTML5 Legacy Doctype Misparsed with htmlparser2 tree adapter

### ISSUE THREAD

**Issue by kkirsche** [inikulin/parse5#45]
Hey,

I wanted to report an issue with the HTML5 legacy doctype parser.
Specifically:
```html
<!DOCTYPE html SYSTEM "about:legacy-compat">
```

Responds with:
```shell
'Document declares a non-HTML5 DOCTYPE'
```

X-Ref twbs/bootlint#251

**Comment by cvrebert** [comment]
Technically Bootlint responds with that, not Parse5.
Here's a more detailed description of the Parse5/Whacko-level issue: https://github.com/inikulin/whacko/issues/13

**Comment by kkirsche** [comment]
I'll close the Parse5 issue on that. Sorry about that. Thanks for the clarification!

**Comment by inikulin** [comment]
The cause of this issue is that parse5 incorrectly renders `doctype.data` in htmlparser2 tree adapter.

**Comment by inikulin** [comment]
Updated version 1.4.2 was published to NPM. Whacko should update automtically via `npm update`
