### ISSUE TITLE
stop parse5.SimpleApiParser

### ISSUE THREAD

**Issue by thisconnect** [inikulin/parse5#47]
Is there a way to have a stopParse api_

In my usecase I am parsing ```<meta name="robots" content="noindex, nofollow">``` and would like to stop the SimpleApiParser from continuing.

**Comment by inikulin** [comment]
Unfortunately there is no way to do that at the moment. However, this functionality makes sense, so I keep this issue open. PRs are welcome, BTW.

**Comment by RReverser** [comment]
Looks like subset of #26 - if you get streaming-like SimpleAPIParser, you can stop parsing (and even reading original file) whenever you've found what you wanted.

**Comment by inikulin** [comment]
It's a little bit different, since streaming parser will auto-suspend when it meets end of chunk. But here we want to stop parser at any moment.

**Comment by RReverser** [comment]
Suspend and stop is not the same. With streaming parser, you can cancel streaming as soon as you find `<meta>` and thus avoid not just parsing, but even unnecessary further reading from filesystem/network/whatever.

**Comment by inikulin** [comment]
@RReverser correct, this is exactly what I mean.

**Comment by RReverser** [comment]
@inikulin Awesome, thanks!

**Comment by thisconnect** [comment]
thanks a lot for this
