### ISSUE TITLE
parse()/parseFragment() inconsistency

### ISSUE THREAD

**Issue by jails** [inikulin/parse5#48]
Hi, If I use the htmlparser2 tree adapter and try to parse the following string `"<head><title>The Title</title></head><body>Hello world</body>"` it automatically adds an `<html>` extra tags which gives the following  "`<html><head><title>The Title</title></head><body>Hello world</body></html>`".

And if use `parseFragment()` it strip out some tags to give `"<title>The Title</title>Hello world"`. 

Is there a way or an option to parse an "xml based" template without any auto adds or strips ?

**Comment by inikulin** [comment]
Hello!

parse5 `parse()` and `parseFragment()` functions behave like browser does in case of document and fragment parsing respectively. To do parsing in "forgiving" manner you can use the this gist: https://gist.github.com/inikulin/bffe6fffd6942d022e11

**Comment by jails** [comment]
Thank you !

**Comment by inikulin** [comment]
You are welcome.
