### ISSUE TITLE
Tree adapter for DOM

### ISSUE THREAD

**Issue by gagern** [inikulin/parse5#49]
It would be nice if we could have an implementation-agnostic tree adaptor for DOM.
That way, one could use `parse5` to load the document, then use all the DOM manipulating tools out there to tweak the data, and finally serialize things again using `parse5`. Or just do one of parsing and serialization using `parse5`, the other with something different.

**Comment by inikulin** [comment]
[jsdom](https://github.com/tmpvar/jsdom)?

**Comment by gagern** [comment]
Adaptor for jsdom, [xmldom](https://github.com/jindw/xmldom), [libxml-dom](https://github.com/skrat/libxml-dom), …

In case you wanted to suggest jsdom as an alternative: sure, it can provide similar functionality, but the fact that the latest version requires io.js makes me reluctant to use it. And parsing to jsdom just so you can import the node into some other DOM implementation you're working with doesn't look attractive either. On the other hand, another tree adaptor would be a fairly easy affair. Should I make this a pull request?

**Comment by inikulin** [comment]
Well, seems like I don't quite understand what you want. Can you illiustrate it via some code snippets, please?

**Comment by gagern** [comment]
What I had in mind was something like this:

```js
var parser = new Parser(new DomTreeAdapter(new xmldom.DOMImplementation()));
```

where `DomTreeAdapter` would be a new class shipped with parse5, and its constructor argument could be any object satisfying the [`DOMImplementation`](http://www.w3.org/TR/2000/REC-DOM-Level-2-Core-20001113/core.html#ID-102161490) specification. But I now had a closer look and realized that on the one hand, libxml-dom apparently doesn't offer such a DOM implementation class, so the number of users would be rather small.

On the other hand, parse5 does object creation significantly different from what the DOM specs envision, so the effort to make things work out would be considerable. In particular, one would have to know the name (and namespace) of the root element before creating the document, and one would have to pass the document as an adapter function argument whenever constructing new elements. Probably not worth the effort just now. I thought this would be simpler, thus my suggestion.

Feel free to close if you don't want to pursue this either.

**Comment by inikulin** [comment]
DOM has a much more complicated connection with the HTML parser than this. I suggest you to keep an eye on JSDOM project, which is the most complete and spec-compliant pure-js DOM implementation at the moment.

**Comment by nrkn** [comment]
I had need of something like this

https://github.com/nrkn/dom-treeadapter/

I'm not actually using it with parse5 though - I've adopted the parse5 TreeAdapter interface throughout another project and I'm using it to map between two different DOM structures
