### ISSUE TITLE
Using document.elementFromPoint()

### ISSUE THREAD

**Issue by Schnodderbalken** [inikulin/parse5#50]
I am trying to use the document.elementFromPoint() function which returns the top visible element by x and y coordinates - see http://dev.w3.org/csswg/cssom-view/#dom-document-elementfrompointx-y
However,

     var Parser = require('parse5').Parser;
     var parser = new Parser();
     var doc = parser.parse(ff_dom);
     doc.elementFromPoint(1,1);

gives me a "TypeError: undefined is not a function" so it seems that the document object that is returned after parsing does not support this function although (according to this https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) Chrome supports it since version 4.0 and Firefox since version 3.

Is it planned to extend the functionality of this library by elementFromPoint? Or am I even doing something wrong?

**Comment by inikulin** [comment]
Parse5 provides pure HTML AST. For full-featured DOM use [jsdom](https://github.com/tmpvar/jsdom).

**Comment by vjyanand** [comment]
It's not implemented in [jsdom](https://github.com/tmpvar/jsdom) either
