### ISSUE TITLE
Avoid adding empty elements

### ISSUE THREAD

**Issue by sakagg** [inikulin/parse5#51]
Hey I was wondering if there is a way to NOT add elements automatically to the AST which are not there in HTML. I'll explain using an example
HTML:
&lt;html>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;head>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/head>
&lt;/html>

Now the html doesn't have any body tag, so I don't want that in the parse tree, whereas right now html has 2 childNodes - head and body.

**Comment by inikulin** [comment]
Hi
You can use "forgiving" parsing gist, as described in #48.

**Comment by sakagg** [comment]
Thanks!
