### ISSUE TITLE
Webpack incompatibility 

### ISSUE THREAD

**Issue by bkniffler** [inikulin/parse5#532]
Trying to use with a nodeJS server that is bundled through webpack.

```
Error: Cannot find module '/node_modules/parse5/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

Wonder this has to do with:
https://github.com/inikulin/parse5/pull/496

**Comment by wooorm** [comment]
Can you please make this reproducible?

**Comment by bkniffler** [comment]
Tried to create a repro, noticed some web pack config edgecase, so nevermind!
