### ISSUE TITLE
Problem running in Nashorn (JVM)

### ISSUE THREAD

**Issue by philmander** [inikulin/parse5#54]
I'm trying to run Parse5 in the JVM using Nashorn and [AvatarJS](https://avatar-js.java.net/). Don't ask....

Due to a [bug in Nashorn](http://stackoverflow.com/questions/27542742/nashorn-bug-jdk8u40-method-code-too-large), Parse5 fails because there are too many objects in [named_entity_trie.js](https://github.com/inikulin/parse5/blob/master/lib/tokenization/named_entity_trie.js)

Is there a way I can customize this file, maybe reduce its size to support a limited set of characters?

**Comment by inikulin** [comment]
> I'm trying to run Parse5 in the JVM using Nashorn and AvatarJS.
OMG 

I'm going rollout trie generator in context of #52. So you will be able to create your own named entities list.

**Comment by inikulin** [comment]
Trie generators now available into the master branch: https://github.com/inikulin/parse5/tree/master/tools

**Comment by philmander** [comment]
Great, thanks for the quick response.
