### ISSUE TITLE
"moduleResolution": "node" should be nodenext or node16

### ISSUE THREAD

**Issue by philkunz** [inikulin/parse5#556]
Hi,

the module resolution should NOT BE `node` for TypeScript as this breaks compatibility with esm on the TypeScript side.

it should be `nodenext`

Please see the reasoning here:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/

**Comment by fb55** [comment]
Sure, we can update this — feel free to send a PR! Afaict this would very much be a lint-style change, as nothing would change now, but future mistakes would be caught.
