### ISSUE TITLE
Incorrect AST

### ISSUE THREAD

**Issue by sakagg** [inikulin/parse5#57]
Here is a piece of code whose AST is not correct
<pre>
&lt;b&gt;
  &lt;i&gt;
&lt;/b&gt;

</pre>
(there is a newline after the last tag)
The resultant AST is 
root -> 1 child (html) -> 2 children (head,body)
body -> 2 children (b, i)
b -> 1 child (#text, i)
i -> 1 child (#text)

The key problem is that `i` is included twice (inside `b` and after `b`)

**Comment by inikulin** [comment]
This is the [classical case](http://dev.w3.org/html5/spec-LC/the-end.html#misnested-tags:-b-i-b-i) of the [adoption agency algorithm](http://dev.w3.org/html5/spec-LC/tree-construction.html#adoptionAgency) invocation result. And it's correct.

E.g. Chrome output:
```js
> var div =document.createElement('div')
< undefined
> div.innerHTML = '<b><i></b>\n';
< "<b><i></b>
"
> div.innerHTML
< "<b><i></i></b><i>
</i>"
```
