### ISSUE TITLE
ES6?

### ISSUE THREAD

**Issue by inikulin** [inikulin/parse5#58]
Pros: 
  - beauty! :lipstick: 
  - clarity

Cons:
  - implementation time
  - introduction of the build process

**Comment by domenic** [comment]
Alternative: use the subset of ES6 supported by io.js (soon to be node.js v4). Then: no build!

**Comment by inikulin** [comment]
Huh, haven't checked ES6 features supported by the io.js for a while. Seems like it have everything I've had in mind. Thanks, @domenic!

**Comment by inikulin** [comment]
However, I'm afraid some adopters will be unhappy with this decision. As far I know currently parse5 is used in some envirionments which doesn't have this syntax support (e.g. Google Trace Viewer). BTW, how jsdom is shipped to the browsers (which are in general doesn't support new syntax) now?

**Comment by domenic** [comment]
It works only on modern browsers.

**Comment by inikulin** [comment]
It would be really nice to use classes, object literal extensions, etc. But as far I know this features are not shipped in browsers yet.  `imports/exports` is another feature, which I really love. But seems like it will make it somewhere between the Judgment Day and the moment when Edward Furlong somehow grown up in the Christian Bale :weary:

**Comment by khrome83** [comment]
You could use [Babel.js](https://babeljs.io/), but there is some issues with this, including compile step to transcompile to ES5. 

If you use direct ES6, I am concerned about performance. For example, a basic loop still outperforms other looping types. I doubt it is any different in ES6.

**Comment by inikulin** [comment]
> You could use Babel.js

This was the original intention. Babel is great and I use it in some of my projects. But for parse5 generated code may kill performance in some cases. So, after some experimentation I've abandoned this idea.

On the other hand, native ES6 support, as you noticed, is still in it's early ages. Moreover, olders browsers and node 10 are still target platforms for parse5. Therefore, it's also not an option.

So, I just keep it open till the better times...

**Comment by RReverser** [comment]
Try to use `jscodeshift` + `jscodemod` - it allows to quickly transform codebase with little efforts.

**Comment by inikulin** [comment]
Yet another option: TypeScript

Pros: same as ES6 + typing (less VM bailouts)
Cons: pretty much the same

**Comment by inikulin** [comment]
Thinking of it a little bit more I came to conclusion that it will never happen: no need to fix things that's not broken. While there are some benefits they are all have just a cosmetic nature. Current codebase in ES5 is just fine (at least for now). So, it's better to put efforts in something more end-user valuable like memory performance, bug fixing, etc.
