### ISSUE TITLE
Incorrect behaviour on html entities without ending semicolon

### ISSUE THREAD

**Issue by paramonov** [inikulin/parse5#581]
Parsing started behave incorrectly since v7, was working correctly on v6

how to reproduce:
```js
const cheerio = require("cheerio");

const html = `<div class="contacts">
    <h3>Contacts</h3>
        <p>Website:&nbsp<a href="http://some.link/here" target="_blank">some.link</a></p>
        <p>Address:&nbsp<span>some address</span></p>
    </div>`;
const $ = cheerio.load(html);

const contacts = $("div.contacts p")
  .map((i, p) => $(p).text())
  .get();

console.log(contacts);
```

expected output:
```js
[
  'Website: some.link',
  'Address: some address'
]
```

actual output:
```js
[
  'Website:Áa href="http://some.link/here" target="_blank">some.link',
  'Address:Áspan>some address'
]
```

**Comment by paramonov** [comment]
probably something goes wrong in [_matchNamedCharacterReference](https://github.com/inikulin/parse5/blob/master/packages/parse5/lib/tokenizer/index.ts#L602) method

**Comment by fb55** [comment]
Fixed in https://github.com/fb55/entities/pull/858

**Comment by wooorm** [comment]
Nice, @fb55! 👍

**Comment by wooorm** [comment]
It was a problem in a dependency. That dependency is released. To get fixes from your dependencies, run `npm update` or equivalent.
