### ISSUE TITLE
Invalid self-closing tags cause undesired behavior

### ISSUE THREAD

**Issue by gorango** [inikulin/parse5#597]
Consider the following (invalid) HTML:

```html
<h1>works</h1>
<iframe src="some-tracker.com" />
<h2>fails</h2>
```

<details>
<summary>Parsing the fragment:</summary>

```js
const result = parseFragment(html)
console.log(util.inspect(result, { depth: 4 }))
```
</details>

<details>
<summary>Yields the following output:</summary>
  
```js
<ref *2> {
  nodeName: '#document-fragment',
  childNodes: [
    <ref *1> {
      nodeName: 'h1',
      tagName: 'h1',
      attrs: [],
      namespaceURI: 'http://www.w3.org/1999/xhtml',
      childNodes: [
        {
          nodeName: '#text',
          value: 'works',
          parentNode: [Circular *1]
        }
      ],
      parentNode: [Circular *2]
    },
    { nodeName: '#text', value: '\n', parentNode: [Circular *2] },
    <ref *3> {
      nodeName: 'iframe',
      tagName: 'iframe',
      attrs: [ { name: 'src', value: 'some-tracker.com' } ],
      namespaceURI: 'http://www.w3.org/1999/xhtml',
      childNodes: [
        {
          nodeName: '#text',
          value: '\n<h2>fails</h2>',
          parentNode: [Circular *3]
        }
      ],
      parentNode: [Circular *2]
    }
  ]
}
```
</details>

In the output, the last child is the `iframe` and not the `h2`. The markup of the `h2` is contained in the `#text` value of the `iframe`.

Importantly here, the markup I provided is invalid since the `iframe` is a non-void HTML element and should not use the self-closing syntax. Replacing the `iframe` with any valid void HTML element (like `img` or `a`) will work. 

However, browsers will successfully parse the invalid markup in my example. So when parsing the internet, we can expect to find such examples of invalid markup being supplied as inputs to our parsing functions.

I understand that parse5 strictly adheres to the spec, so I'm not sure if this is something worth addressing in this codebase or on an individual level. In the case of the former, I'd be happy to contribute. In the case of the latter, I'd really appreciate some suggestions for resolving this issue when it arises.

**Comment by wooorm** [comment]
How that is parsed, is exactly how this project is supposed to parse it. To this project, there is no bug.

> “resolving this issue when it arises.”

Parsing according to spec is not an issue. Something else could be an issue for you: for example, your authors do not write valid HTML. In that case, they could use linters to solve it. Or, you’re dealing with XML instead of HTML, in which case you need an XML parser. I do not know enough about your question to answer it.
