### ISSUE TITLE
How to stop tbody from being forced in when a table tag is passed to parse

### ISSUE THREAD

**Issue by fushihara** [inikulin/parse5#607]
If you enter `<table><tr><td>aaa</td></tr></table>` in parseFragment and then serialize it as is, you will see an additional tag called tbody.

I understand that that is required for the html table tag, but now I want the html I entered to be a tree structure as is.
Please let me know how to disable this option.

```
var parse5 = require("parse5")
const documentFragment = parse5.parseFragment('<table><tr><td>aaa</td></tr></table>');
const html = parse5.serialize(documentFragment);
console.log(html); // output "<table><tbody><tr><td>aaa</td></tr></tbody></table>"
```

**Comment by wooorm** [comment]
That is not what this project is for. You could potentially look at positional info to figure out if something was in the original document or not. Or you can use an xml parser
