### ISSUE TITLE
Get rid of JsDom parser

### ISSUE THREAD

**Issue by inikulin** [inikulin/parse5#61]
Since v2.0 will have event-driven streaming API I think we should get rid of `JsDomParser` as a separate entity. `ParserStream` will have `script` event instead and a `documentWrite` method.

\cc @Sebmaster @domenic JFYI

**Comment by Sebmaster** [comment]
Sounds good. When you emit the script event, can we pause the stream then call documentWrite sometime later and then resume the stream again?

I'm not sure we can pause the input stream (since we don't know where the start-tag ends).

**Comment by inikulin** [comment]
@Sebmaster But should we? Where are two scenarios:

1. parser encounters `<script>` and `document.write` is called immediately from this script. We don't need to suspend parser since it's already suspended, because you are in it's 'script' event handler.

2. `document.write` is called asynchronously, then you'll be able to write only then your code which will `document.write` receives event loop tick. This will happen if: 
a. parser awaits next chunk and therefore it's already suspended 
b. parsing is accomplished, in this case you should switch to your `document.write` implementation which rewrites whole body.

**Comment by Sebmaster** [comment]
> parser encounters <script> and document.write is called immediately from this script. We don't need to suspend parser since it's already suspended, because you are in it's 'script' event handler.

Ahh, I wasn't aware it will be auto-paused. Do we resume manually then?

**Comment by inikulin** [comment]
It will resume once you `write()` or `end()` just like regular streams.

**Comment by inikulin** [comment]
Oh, I misunderstood your question. It will just `emit('script')` and obviously will not resume till handler will not finish working.

**Comment by Sebmaster** [comment]
Yeah but what if we have to do a fetch request if it's a `<script src="">`? We'll have to have some explicit method to resume since we'll have to wait until the fetching is done.

**Comment by inikulin** [comment]
Arghh, forgot about this use case. What if parse will auto-suspend if it has 'script' event handler?
And `resume` function will be passed to the handler:
```js
parser.on('script', function(scriptNode, resume) {
    ...
});
```

**Comment by Sebmaster** [comment]
Yep, fine for me, thanks for taking it into account.
