### ISSUE TITLE
What is the preferred way for accessing `Token.` types?

### ISSUE THREAD

**Issue by hasezoey** [inikulin/parse5#624]
Currently `Token` in `parse5` is marked as `@internal`, which should mean it should not be used:
https://github.com/inikulin/parse5/blob/bde5b5e7d71119f4ef9352595fd49463d79d95bb/packages/parse5/lib/index.ts#L16-L17

so a "proper workaround" would be to import from `parse5/dist/common/token` directly.

But i also have seen that some (collaborators) point out using `Token` directly, so i wanted to ask if this `@internal` is really internal and should not be used or if this is just "something else" (if "something else" please explain why internal).

**Comment by fb55** [comment]
IIRC `@internal` was added for the documentation generator. Feel free to disregard — we will have to conform to Semver for any updates, to not break our own modules.

As for deep imports: Paths in the package.json's export map are guaranteed to continue working, others are best effort. Most tooling already won't allow you to import anything not in the export map.
