### ISSUE TITLE
Types error

### ISSUE THREAD

**Issue by polRk** [inikulin/parse5#636]
Try to import 
```ts
import { Node } from 'parse5/dist/tree-adapters/default'
```

```ts
Error: Missing "./dist/tree-adapters/default" export in "parse5" package
```

**Comment by 43081j** [comment]
are you using typescript?

the default adapter is exported at top-level (and only really accessible there), but its types should be available from the path directly.

maybe try an explicit `import type { Node }` and see if it works then. `Node` is only a type so that should be fine

**Comment by fb55** [comment]
Assuming this is resolved.
