### ISSUE TITLE
RewritingStream is not a constructor 

### ISSUE THREAD

**Issue by musicologopr** [inikulin/parse5#639]
I'm running latest node in vsc, and just by running this i get this error:
RewritingStream is not a constructor 

```js
const RewritingStream = require('parse5-html-rewriting-stream');

const rewriter = new RewritingStream();
```

​

**Comment by fb55** [comment]
You will have to update your require:

```js
const { RewritingStream } = require('parse5-html-rewriting-stream');
```

The module exports an object, with one of the properties being the rewriting stream.

**Comment by musicologopr** [comment]
> You will have to update your require:
> 
> ```js
> const { RewritingStream } = require('parse5-html-rewriting-stream');
> ```
> 
> The module exports an object, with one of the properties being the rewriting stream.

indeed..
