### ISSUE TITLE
CommonJS output for toolset packages?

### ISSUE THREAD

**Issue by ryota-ka** [inikulin/parse5#649]
At this moment, only `parse5` and `parse5-htmlparser2-tree-adapter` seem to have CommonJS outputs.
Are there any plans to make other packages also *dual*?

Background:
We are using `parse5-html-rewriting-stream` in our Node.js (CommonJS) + TypeScript project, and we still cannot update the library to v7 as the migration to ESM is pretty hard.

**Comment by fb55** [comment]
No plans. The existing dual modules were created to allow adoption by jsdom and cheerio. Not adding this for now, happy to reconsider should there be more demand.
