### ISSUE TITLE
Replace node with other file cotent

### ISSUE THREAD

**Issue by shawnXiao** [inikulin/parse5#65]
I want to use parse5 to implement the [SSI](http://nginx.org/en/docs/http/ngx_http_ssi_module.html)  module. Is there any method I can replace comment node with included file content.

BTW: Is there any docs for using? or examples.

**Comment by inikulin** [comment]
You can parse HTML using Parser and get AST as a result. Then walk AST and replace appropriate node content. Then convert AST back to HTML using Serializer.

**Comment by inikulin** [comment]
P.S. Docs and examples are in README.md in the root of the repo.

**Comment by shawnXiao** [comment]
Thanks for your help. I have done as you said. 
```js
                            var fileContent = fs.readFileSync(includeFilePath, "utf8");
                            var parser = new Parser();
                            var fragment = parser.parseFragment(fileContent, entry.childNodes[0]);
                            entry.childNodes.push(fragment);
```
I found that fragment con't be serialized to html. I have another way is traverse the fragment and then push to entry,  I think it's a little bit complex.

**Comment by inikulin** [comment]
@shawnXiao 
```js
var fileContent = fs.readFileSync(includeFilePath, "utf8");
var parser = new Parser();
var fragment = parser.parseFragment(fileContent, entry.childNodes[0]);
entry.childNodes = entry.childNodes.concat(fragment.childNodes);
```
?
