### ISSUE TITLE
`entities` dependency seems to cause problems in ESM-only projects

### ISSUE THREAD

**Issue by 43081j** [inikulin/parse5#666]
If you have a pure-esm project (i.e. one which doesn't support commonjs at all), it seems this line causes trouble:

https://github.com/inikulin/parse5/blob/8e6ef18b94753e880fbd6fe074a5d67c59bc4fe8/packages/parse5/lib/tokenizer/index.ts#L22

the error i get is:

> The requested module 'entities/lib/decode.js' does not provide an export named 'BinTrieFlags'

looking at the file, it seems to be commonjs.

if that's the case, esm-only builds/repos won't be able to import parse5 (unless the entire tree is ESM).

cc @fb55 as not sure what to do about this. maybe you could just publish an ESM version of the entities package? since it is already written as modules in typescript, seems it would be straight forward enough

**Comment by fb55** [comment]
entities is already a dual module. The error seems to stem from TypeScript, which consumes the CJS types. Your code will use MJS when run tho.

Curious where this error stems from.

**Comment by wooorm** [comment]
`node16`/`nodenext` maybe vs old resolution ways? https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/

**Comment by 43081j** [comment]
i see it in `lib/esm/decode.js`. but yes it seems the one being resolved in my case is the commonjs file... 🤔 

its also not a typescript error FYI @fb55, its an error thrown by node itself at runtime (the code actually builds fine).

it may be because lit is doing some custom module loading in that case...

**Comment by 43081j** [comment]
im gonna go with it being this:

https://github.com/lit/lit/blob/0275bd0bf1c96d1e27983cefd6c7c0e5ebe53d2e/packages/labs/ssr/src/lib/module-loader.ts#L285-L289

ill close this for now and open an issue in the lit repo, my bad. if it turns out there's still an issue on parse5/entities' end ill reopen.
