### ISSUE TITLE
attributes with value: undefined

### ISSUE THREAD

**Issue by allain** [inikulin/parse5#711]
It feels logical that an attribute can have a name but no value, or at least a value with undefined as its value.

In that case, it ought to render a boolean attribute: `attrs: [{name: 'x-test'}]` should yield an element without an explicitly ="" in it.

At the moment this causes the serialization to crash rather than emit he attribute.

**Comment by fb55** [comment]
Hi @allain, parse5 ships with types that specify the shape of what it expects.

> should yield an element without an explicitly ="" in it

parse5 follows HTML's spec for serialising HTML fragments: https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments

This spec has clear rules about what attributes should be rendered which way, and any divergence would violate the spec.

I understand that this is annoying. On a positive note, the [serializer code](https://github.com/inikulin/parse5/blob/1a505fa66e4158500610e1e39be795cdb95a390c/packages/parse5/lib/serializer/index.ts) isn't very long and it should be easy to maintain your own custom version of it. Hope that helps!
