### ISSUE TITLE
customizable forgiving options

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#72]
Like, the ability to define additional characters to be allowed in tag names and attribute names. If left blank/etc, it'd be spec compliant.

This way, you don't have to decide for anyone just how it would be forgiving. Instead, provide the tools for us to make those decisions.

**Comment by inikulin** [comment]
> Like, the ability to define additional characters to be allowed in tag names and attribute names. If left blank/etc, it'd be spec compliant.

I doubt it's possible without breaking grammar, too many edge cases, too many ways to shoot yourself in the head.

**Comment by stevenvachon** [comment]
Maybe a regex for such instead.

**Comment by domenic** [comment]
Basically, what you want is not a HTML Standard compliant parser, but instead for a different language. That kind of work is better off as a fork than baked into parse5.

**Comment by inikulin** [comment]
@stevenvachon 
[H͎̘̭͖̗̹TM̼L̘5̪̱͚͎ t͇͈o̲̯̹̭̗͉̤k̝̯̤ͅeṉ̠̳͎̯̥̲i̲z̬̪̭͚̙̮͓e̼͓̱ṛ ̻̪̺̤͔̠̭i̜̹̜̣̘ș ̙̝̮t͈̻͉̹͔̬ͅo͙o̜̼͔̪ ̺͈̱̲̩c̲̰͉͉͔o̼̞͙̗̟m̹͈͔̮̖p̺l̤̠̞̱e̪͍̪̠̬͍x̱͓͚͙ t͕ͅo̗̳͉̹͚̝͕ ̘̥̟̱b̤͓̬͓͎̯͎e̝ ̗͈̮̬̬͕r͕̯e͈̻̩̱̗̜ͅp̖̤̳l͔͉ͅa͖c̭͕͔̝e̺̣̭̹͕͈d͔͎̗̯̥ ̣̤̺ͅw̜̖͙̩i̻̩t͚̪ͅh̭̠͕͈̲ ̻̱̣̠͇͎̹th̺͈̼ͅe̗̼̠̻̮̻ ̠̲̹̠̜r̪̝͕͎egu̖͍̰̱͎̳l̝̙͚a̯̻r ̟̬e̞̟͖͍̳̹x̟̺͓͔̱̠͙p͔͕̯̘re͖͉s̰̩̝̩s͙͓͚̳̰i͕̥̩̳o̪n̯̫̩̠̬s](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags)

**Comment by stevenvachon** [comment]
@domenic a fork would quickly become outdated. I do not wish to maintain an HTML parser.

@inikulin I never said replace the tokenizer with a regexp, but simply add it as an optional step in the algorithm.

**Comment by domenic** [comment]
@stevenvachon right, and I'm guessing @inikulin doesn't want to maintain a not-HTML parser :P

**Comment by stevenvachon** [comment]
@domenic I know, but my thinking was that by making the non-standard tools optional, it wouldn't be a not-HTML parser.

**Comment by stevenvachon** [comment]
Actually, I came up with another solution which will allow me to use parse5.

**Comment by stevenvachon** [comment]
This becomes necessary again if we want to parse angular2 (or similar) templates:
```html
<button
  (event)="value"
  [property.property]="value"
  [(twoWayBinding)]="value"
>
```

**Comment by RReverser** [comment]
@stevenvachon You might want to see a thread at https://github.com/inikulin/parse5/issues/133#issuecomment-222713109.
