### ISSUE TITLE
Nuxt2 import error

### ISSUE THREAD

**Issue by otary** [inikulin/parse5#743]
![image](https://user-images.githubusercontent.com/3916327/204268160-e9bb03f7-518e-4d57-94e5-4fe0fa37bc97.png)

Why the error is introduced？

**Comment by 43081j** [comment]
im gonna guess this is because your webpack config is configured to look for `*.vue` but not `*.js`.

if you tell it to look for both, it'll probably work.

could be totally wrong but thats what i suspect it is

**Comment by otary** [comment]
> im gonna guess this is because your webpack config is configured to look for `*.vue` but not `*.js`.
> 
> if you tell it to look for both, it'll probably work.
> 
> could be totally wrong but thats what i suspect it is


I reduced the version from 7. x to 6. x, and the problem was solved。
