### ISSUE TITLE
Should parse5 account for cross site scripting escape sequences?

### ISSUE THREAD

**Issue by kristoferjoseph** [inikulin/parse5#763]
We use parse5 for server side rendering and have been thinking of ways to avoid cross site scripting attacks.
Normally I would use a library like [xss](https://www.npmjs.com/package/xss) to sanitize the input by escaping html tags.
The issue is that parse5 accepts escaped html and outputs unescaped tags.

Do you think parse5 should be cross site scripting aware and not convert escaped strings?

**Comment by wooorm** [comment]
How do you mean it accepts escaped html, and outputs it unescaped? I don’t think it does that. Perhaps you can share an MVP example

**Comment by kristoferjoseph** [comment]
Ah good to know. 
I will make a reduced case to be sure and share if this is indeed a parse5 issue.

Thanks for the speedy response🤗

**Comment by fb55** [comment]
Closing this for now. Happy to revisit with something we can reproduce!
