### ISSUE TITLE
XML mode!

### ISSUE THREAD

**Issue by domenic** [inikulin/parse5#77]
Sooooo, what about if parse5 also implemented XHTML parsing? It should be easier than HTML parsing, right?

The ideal situation would be where I can use basically the same API for HTML and XHTML, including my own tree adapter and the like, but just flip one switch and parse5 does all the work of changing how it parses (and hard-erroring on encountering an error).

Right now jsdom has to use htmlparser2 for the XML mode, and it doesn't work so great (https://github.com/tmpvar/jsdom/issues/1276#issuecomment-159792162).

What do you think? :)

**Comment by inikulin** [comment]
>  It should be easier than HTML parsing, right?

Well, looking at the [libxml2](https://github.com/ConradIrwin/libxml2) parser which is ~15k LOC I doubt it's easier :disappointed: . [XML spec](http://www.w3.org/TR/REC-xml/) is not as clear as the HTML spec: it just gives you some BNFs. Converting them to the neat hand-written parser may take a while. Parser generators may simplify things a bit, but I doubt about their performance. 

> The ideal situation would be where I can use basically the same API for HTML and XHTML, including my own tree adapter and the like, but just flip one switch and parse5 does all the work of changing how it parses (and hard-erroring on encountering an error).

Also, I'm not sure about incorporating it in the parse5. Package may grow enormously and will contain 2 quite different parsers (HTML and XML will not share much code). As an option, after all, we can combine both parse5 and XML parser under some umbrella package which will provide some generic interface for the consumers. 

Anyway, implementation of this may take a while. I'm also wonder if we need polished and fast parser for the XML. I mean, how often it's used in browser nowadays and does it cost the efforts? Maybe we should just compile some existing well-tested C/C++-parser used by the browsers with [emscripten](https://github.com/kripken/emscripten) and just provide nice JS fascade for it?

**Comment by domenic** [comment]
Haha yeah, fair enough. I agree with your concerns and think an umbrella package is indeed probably better.

I also agree that XML mode is not very important (although we do get a surprising number of issues on it). We should probably switch to sax-js as mentioned in tmpvar/jsdom#1276, and work on that kind of umbrella package.

I guess the thing to do here is wait for jsdom to upgrade to parse5 2.0. IIRC using parse5.SAXParser for better streaming and `<script>` support was the plan already. Once that's done, we can work on a parse5-lookalike wrapper on top of sax-js, and it'll take care of things hopefully.

Thanks!

**Comment by inikulin** [comment]
> IIRC using parse5.SAXParser for better streaming.

I'm afraid, it's not a good idea. SAXParser provides just basic lexical information that is alone is insufficient to build correct HTML5 AST (unlike XML whose element nesting rules are quite trivial). You will need to use `parse5.ParserStream` which is WritableStream and has a proper scripting support ([sneak peek](https://github.com/inikulin/parse5/wiki/Documentation#parse5+ParserStream)).
