### ISSUE TITLE
firstChild, nextSibling, previousSibling?

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#81]
Were these not added in order to maximize performance? If not, they would be useful.

**Comment by stevenvachon** [comment]
Oh yeah, stupid request; the values would need to be updated whenever the tree is mutated.

**Comment by stevenvachon** [comment]
Hmm, but then so would `parentNode`, which is provided.

**Comment by inikulin** [comment]
Tree adapters contain the minimal API required to build/serialize AST. Everything else is up to the tree format implementers. If you want these properties in default adapter, then you can create your own adapter that will extend default adapter (or just use jsdom).

**Comment by stevenvachon** [comment]
:+1:
