### ISSUE TITLE
Failed to parse source map ...

### ISSUE THREAD

**Issue by wisammechano** [inikulin/parse5#831]
I am using parse5 in a react app, and the modules are referring to a sourceMap file that is not being found, which is interrupting the build of the app.

I can confirm checking the dist/index.js in npm

Line 45
```js
//# sourceMappingURL=index.js.map
```

however, there isn't such file relative to path

**Comment by lunika** [comment]
I confirm we still have this issue with version 7.1.1 of `parse5`

**Comment by 43081j** [comment]
fyi @fb55 this is because the `files` array in the package JSON specifies `*.js` and not `*.js.map`

we could either stop generating sourcemaps in prod, or just ship them. what do you think?

**Comment by fb55** [comment]
Source maps reference the original TypeScript files. Most of my packages reference the source files on GitHub ([example](https://github.com/fb55/htmlparser2/blob/5eea942451c1b836999d4557ed98470678c789b9/package.json#L59)), which I couldn't figure out how to do with the monorepo setup of parse5.

I would prefer to ship useful source maps, but if that isn't possible, removing the reference seems logical.
