### ISSUE TITLE
Permissions for project's wiki?

### ISSUE THREAD

**Issue by RReverser** [inikulin/parse5#85]
I found a bunch of small mistakes in the wiki, but it looks like it's non-editable (for most projects it is, so I assume it's intentionally restricted?), and thus I'm not sure what is the best way to contribute to it.

**Comment by inikulin** [comment]
Docs in wiki are autogenerated from markdown in `docs` and jsdoc comments. You can modify it in repo and just issue the PR

**Comment by RReverser** [comment]
Ah thanks, that explains a lot :)
