### ISSUE TITLE
Incorrect handling of CDATA sections

### ISSUE THREAD

**Issue by alexdarc** [inikulin/parse5#873]
## Description:
The library is incorrectly handling CDATA sections in HTML documents. According to MDN documentation (https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName), the node name of a CDATA section should be "#cdata-section". However, parse5 is treating it as a comment tag (`#comment`).

## Steps to reproduce:

- Create an HTML document that contains a CDATA section
- Use the parse5 library to parse the HTML document
- Retrieve the node name of the CDATA section using the nodeName property

### Expected result:
The nodeName property should contains `"#cdata-section"`.

### Actual result:
The nodeName property contains `#comment`.

## Example code:

```js
const parse5 = require('parse5');

const htmlString = `
<!DOCTYPE html>
<html>
<head>
	<title>Test page</title>
</head>
<body>
	<![CDATA[This is some CDATA content]]>
</body>
</html>
`;

const document = parse5.parse(htmlString);
const cdataNode = document.childNodes[1].childNodes[2].childNodes[1];
console.log(cdataNode.nodeName);  // Output: #comment
```

**Comment by wooorm** [comment]
Have you tried saving that html as an html file, and opening it in your browser?
Then looking at the DOM tree in dev tools?

Both mdn and p5 are correct: you can theoretically have dom nodes for cdata, but you can't make them with HTML syntax.
