### ISSUE TITLE
node_modules/parse5/dist/index.d.ts:1:15 - error TS1005: ',' expected.

### ISSUE THREAD

**Issue by ilrein** [inikulin/parse5#878]
I'm currently using vite (which uses parse5 internally) and vercel. While building serverless functions in vercel, I notice I am always getting typescript errors from parse5. 

It doesn't actually impact the development and nothing fails, but it does fill my console with issues.

IE:

```
node_modules/parse5/dist/index.d.ts:1:15 - error TS1005: ',' expected.

1 import { type ParserOptions } from './parser/index.js';
                ~~~~~~~~~~~~~

node_modules/parse5/dist/index.d.ts:4:15 - error TS1005: ',' expected.

4 export { type DefaultTreeAdapterMap, defaultTreeAdapter } from './tree-adapters/default.js';
                ~~~~~~~~~~~~~~~~~~~~~

node_modules/parse5/dist/index.d.ts:6:15 - error TS1005: ',' expected.

6 export { type ParserOptions, /** @internal */ Parser } from './parser/index.js';
                ~~~~~~~~~~~~~
```

Currently finds 27 errors. I would love to find a way to silence or remove/fix these, but have no idea how to approach it 🤔

**Comment by 43081j** [comment]
it'll be a mismatch of typescript versions. importing individual type-only symbols is fairly new, so i suspect your project uses a slightly older typescript (or vite does?)

somewhere down the line there's definitely an older typescript, upgrading it would solve this

**Comment by ilrein** [comment]
I can see that vite uses typescript 5.0.2 while parse5 uses 5.0.3

Think that could the problem?

**Comment by 43081j** [comment]
apparently its a feature since 4.5 so that seems odd

if you `npm ls typescript` in that repo, do you see any older ones?

**Comment by ilrein** [comment]
I would imagine that vercel is agnostic, they deploy everything front-end.

I'm running `vercel dev` which calls `vite --port $PORT`

So I believe it's on the vite side 🤔
