### ISSUE TITLE
details about the pros/cons with htmlparser2

### ISSUE THREAD

**Issue by abarre** [inikulin/parse5#89]
Hello,

I recently discovered parse5 that clains to be the fastest parser on Node 
> It's the fastest spec-compliant HTML parser for Node to date. It parses HTML the way the latest version of your browser does.

We, at Fasterize, are using htmlparser2 for a long time. I would like to know if you have data that compare the performance of parse5 and htmlparser2. Also, can you explain if there is a main design difference between the two parsers that explain performance differences.

**Comment by inikulin** [comment]
It's the fastest spec-compliant browser. htmlparser2 is not spec-compliant. However, their performance is comparable, htmlparser2 is ~1.5x faster, but yet again, it's incompatible, so it parses incorrectly in the wide range of cases.
