### ISSUE TITLE
Attribute locations correct?

### ISSUE THREAD

**Issue by stevenvachon** [inikulin/parse5#93]
```js
var html = '<a href="file.html">link</a>';
var tree = require("parse5").parse(html, {locationInfo:true});
var link = tree.childNodes[0].childNodes[1].childNodes[0];
var location = link.__location.attrs.href;

console.log( html.split("\n")[location.line-1].substring(location.startOffset+location.col, location.endOffset) );
//-> ="file.html"
```
Wouldn't it be ideal for it to provide locations for `file.html` or `"file.html"` and not `="file.html"`?

I'm thinking that including the quotes (or lack thereof) might be a good idea to support the replacement of `attr=value` (no quotes) with a value that requires encapsulating quotes. However, including the `=` confuses me.

**Comment by skreborn** [comment]
This would be the correct position to return for an attribute with no value. Consider the following. You have an attribute `foo` that has no value specified. The location points to the end of `foo`, where you might add a value by appending `="bar"`. It works the other way around, too. If you would like to remove the value of `foo="bar"`, you are in luck, as location points to the end of `foo` once again. You can easily remove the entire value, including the equal (`=`) sign.

**Comment by stevenvachon** [comment]
Ah, yes. Thank you.
