### ISSUE TITLE
Foreign content attributes and tag names are not adjusted by the SAXParser

### ISSUE THREAD

**Issue by inikulin** [inikulin/parse5#99]

**Comment by pixelami** [comment]
I have noticed that when using the SAXParser to process a ReadableStream instance (containing latin and non latin characters). I notice the `location` objects passed to the 'startTag' and 'endTag' event handlers have incorrect `startOffset` and `endOffset` positions.

Does that seem to be a likely symptom of this issue of should I create a separate issue and investigate further?

**Comment by inikulin** [comment]
@pixelami Seems like it's completely different issue

**Comment by pixelami** [comment]
I created this issue,
https://github.com/inikulin/parse5/issues/103

Is it feature or a bug, I'll let you decide....
